{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField","text":"BorderedTextField"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfielddata\/textfield"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldData\/textField","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField"}],"title":"textField","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC13TextFieldDataV04textI0AA08BorderedhI0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldData"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField":{"role":"symbol","title":"BorderedTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BorderedTextField"}],"url":"\/documentation\/cshub_test\/borderedtextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/TextFieldData/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldData\/textField","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfielddata\/textfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/TextFieldData":{"role":"symbol","title":"ZenIDPersonalInfoCardView.TextFieldData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldData"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldData"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfielddata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView":{"role":"symbol","title":"ZenIDPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/title","value":"BorderedTextField"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/fragments","value":[{"kind":"identifier","text":"BorderedTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/title","value":"ZenIDPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}