{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwatchInitSuccessful"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/initoverlay\/airwatchinitsuccessful(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/initoverlay\/airwatchinitsuccessful(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay\/airwatchInitSuccessful(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwatchInitSuccessful"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"title":"airwatchInitSuccessful(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)InitOverlay(im)airwatchInitSuccessful:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"airwatchInitSuccessful:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/InitOverlay/airwatchInitSuccessful(_:)":{"role":"symbol","title":"airwatchInitSuccessful(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwatchInitSuccessful"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay\/airwatchInitSuccessful(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"airwatchInitSuccessful:"}],"url":"\/documentation\/cshub_test\/initoverlay\/airwatchinitsuccessful(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/InitOverlay":{"role":"symbol","title":"InitOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InitOverlay"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InitOverlay"}],"url":"\/documentation\/cshub_test\/initoverlay"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"airwatchInitSuccessful:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"airwatchInitSuccessful:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"airwatchInitSuccessful:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1InitOverlay~1airwatchInitSuccessful(_:)\/title","value":"airwatchInitSuccessful:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1InitOverlay~1airwatchInitSuccessful(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"airwatchInitSuccessful:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1InitOverlay\/title","value":"InitOverlay"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1InitOverlay\/fragments","value":[{"kind":"identifier","text":"InitOverlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}