{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ActivityView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ActivityView","text":"ActivityView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/initoverlay\/progressindicator"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay\/progressIndicator","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActivityView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ActivityView"}],"title":"progressIndicator","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test11InitOverlayC17progressIndicatorAA12ActivityViewCvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ActivityView":{"role":"symbol","title":"ActivityView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityView"}],"abstract":[{"type":"text","text":"custom animated activity indicator"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ActivityView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActivityView"}],"url":"\/documentation\/cshub_test\/activityview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/InitOverlay":{"role":"symbol","title":"InitOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InitOverlay"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InitOverlay"}],"url":"\/documentation\/cshub_test\/initoverlay"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/InitOverlay/progressIndicator":{"role":"symbol","title":"progressIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActivityView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ActivityView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/InitOverlay\/progressIndicator","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/initoverlay\/progressindicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ActivityView\/title","value":"ActivityView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ActivityView\/fragments","value":[{"kind":"identifier","text":"ActivityView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1InitOverlay\/title","value":"InitOverlay"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1InitOverlay\/fragments","value":[{"kind":"identifier","text":"InitOverlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}