{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBottomBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqCell","text":"FaqCell"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/faqviewcontroller\/handlebottomborder(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/handleBottomBorder(for:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBottomBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqCell","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqCell"},{"kind":"text","text":")"}],"title":"handleBottomBorder(for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:10CSHub_Test17FaqViewControllerC18handleBottomBorder3foryAA0C4CellC_tF","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController":{"role":"symbol","title":"FaqViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqViewController"}],"url":"\/documentation\/cshub_test\/faqviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/handleBottomBorder(for:)":{"role":"symbol","title":"handleBottomBorder(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBottomBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqCell","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqCell"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/handleBottomBorder(for:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/handlebottomborder(for:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqCell":{"role":"symbol","title":"FaqCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqCell"}],"url":"\/documentation\/cshub_test\/faqcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/title","value":"FaqViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/fragments","value":[{"kind":"identifier","text":"FaqViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/title","value":"FaqCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/fragments","value":[{"kind":"identifier","text":"FaqCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}