{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNeededSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView","text":"ZenIDSelectableView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ciampersonalinfocardview\/showneededselectview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showNeededSelectView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNeededSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"title":"showNeededSelectView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test24CiamPersonalInfoCardViewC016showNeededSelectG0AA015ZenIDSelectableG0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView":{"role":"symbol","title":"CiamPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/showNeededSelectView":{"role":"symbol","title":"showNeededSelectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNeededSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showNeededSelectView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/showneededselectview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSelectableView":{"role":"symbol","title":"ZenIDSelectableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSelectableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSelectableView"}],"url":"\/documentation\/cshub_test\/zenidselectableview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView\/title","value":"CiamPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSelectableView\/title","value":"ZenIDSelectableView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSelectableView\/fragments","value":[{"kind":"identifier","text":"ZenIDSelectableView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}