{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDifferent"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ciampersonalinfocardview\/showdifferent()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ciampersonalinfocardview\/showdifferent()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showDifferent()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDifferent"},{"kind":"text","text":"()"}],"title":"showDifferent()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)CiamPersonalInfoCardView(im)showDifferent","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"showDifferent"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/showDifferent()":{"role":"symbol","title":"showDifferent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDifferent"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showDifferent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showDifferent"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/showdifferent()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView":{"role":"symbol","title":"CiamPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showDifferent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showDifferent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showDifferent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1showDifferent()\/title","value":"showDifferent"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1showDifferent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showDifferent"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView\/title","value":"CiamPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}