{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongGesture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/documentscollection\/handlelonggesture(gesture:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/documentscollection\/handlelonggesture(gesture:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsCollection\/handleLongGesture(gesture:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongGesture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"title":"handleLongGesture(gesture:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)DocumentsCollection(im)handleLongGestureWithGesture:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"handleLongGestureWithGesture:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsCollection"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentsCollection":{"role":"symbol","title":"DocumentsCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentsCollection"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentsCollection"}],"url":"\/documentation\/cshub_test\/documentscollection"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentsCollection/handleLongGesture(gesture:)":{"role":"symbol","title":"handleLongGesture(gesture:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleLongGesture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsCollection\/handleLongGesture(gesture:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleLongGestureWithGesture:"}],"url":"\/documentation\/cshub_test\/documentscollection\/handlelonggesture(gesture:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handleLongGestureWithGesture:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleLongGestureWithGesture:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleLongGestureWithGesture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gesture"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentsCollection\/title","value":"DocumentsCollection"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentsCollection\/fragments","value":[{"kind":"identifier","text":"DocumentsCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentsCollection~1handleLongGesture(gesture:)\/title","value":"handleLongGestureWithGesture:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentsCollection~1handleLongGesture(gesture:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleLongGestureWithGesture:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}