{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPolygonView"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Future","preciseIdentifier":"s:10CSHub_Test6FutureC","text":"Future"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraPolygonView","text":"CameraPolygonView"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cameraeditview\/createpolygonview()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/createPolygonView()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"creates the view that allow user to see and edit detected points"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPolygonView"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CameraPolygonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraPolygonView"},{"kind":"text","text":">"}],"title":"createPolygonView()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:10CSHub_Test14CameraEditViewC013createPolygonE0AA6FutureCyAA0cgE0CGyF","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView/createPolygonView()":{"role":"symbol","title":"createPolygonView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPolygonView"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CameraPolygonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraPolygonView"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates the view that allow user to see and edit detected points"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/createPolygonView()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraeditview\/createpolygonview()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView":{"role":"symbol","title":"CameraPolygonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"abstract":[{"type":"text","text":"user interactive polygon view with 4 points and magnifier"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPolygonView"}],"url":"\/documentation\/cshub_test\/camerapolygonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Future":{"role":"symbol","title":"Future","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Future"}],"abstract":[{"type":"codeVoice","code":"Future"},{"type":"text","text":" type representing "},{"type":"strong","inlineContent":[{"type":"text","text":"asynchronous return value of the function"}]},{"type":"text","text":" "},{"type":"text","text":"that can be observed later on in the future. returned type will be either success"},{"type":"text","text":" "},{"type":"text","text":"with a value "},{"type":"codeVoice","code":"T"},{"type":"text","text":" or failure with an error "},{"type":"codeVoice","code":"E"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Future","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Future"}],"url":"\/documentation\/cshub_test\/future"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView":{"role":"symbol","title":"CameraEditView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraEditView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraEditView"}],"url":"\/documentation\/cshub_test\/cameraeditview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/title","value":"CameraPolygonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/fragments","value":[{"kind":"identifier","text":"CameraPolygonView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView\/title","value":"CameraEditView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView\/fragments","value":[{"kind":"identifier","text":"CameraEditView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}