{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraPolygonView","text":"CameraPolygonView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cameraeditview\/polygonview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/polygonView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPolygonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraPolygonView"},{"kind":"text","text":"?"}],"title":"polygonView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test14CameraEditViewC07polygonE0AA0c7PolygonE0CSgvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView":{"role":"symbol","title":"CameraPolygonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"abstract":[{"type":"text","text":"user interactive polygon view with 4 points and magnifier"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPolygonView"}],"url":"\/documentation\/cshub_test\/camerapolygonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView/polygonView":{"role":"symbol","title":"polygonView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPolygonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraPolygonView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/polygonView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraeditview\/polygonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView":{"role":"symbol","title":"CameraEditView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraEditView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraEditView"}],"url":"\/documentation\/cshub_test\/cameraeditview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/title","value":"CameraPolygonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/fragments","value":[{"kind":"identifier","text":"CameraPolygonView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView\/title","value":"CameraEditView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView\/fragments","value":[{"kind":"identifier","text":"CameraEditView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}