{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cameraeditview\/viewforzooming(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/cameraeditview\/viewforzooming(in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/viewForZooming(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIScrollViewDelegate.viewForZooming(in:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"title":"viewForZooming(in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)CameraEditView(im)viewForZoomingInScrollView:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"viewForZoomingInScrollView:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/UIScrollViewDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraeditview\/uiscrollviewdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView/viewForZooming(in:)":{"role":"symbol","title":"viewForZooming(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView\/viewForZooming(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewForZoomingInScrollView:"}],"url":"\/documentation\/cshub_test\/cameraeditview\/viewforzooming(in:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraEditView":{"role":"symbol","title":"CameraEditView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraEditView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraEditView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraEditView"}],"url":"\/documentation\/cshub_test\/cameraeditview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewForZoomingInScrollView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForZoomingInScrollView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"viewForZoomingInScrollView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView~1viewForZooming(in:)\/title","value":"viewForZoomingInScrollView:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView~1viewForZooming(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForZoomingInScrollView:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView\/title","value":"CameraEditView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraEditView\/fragments","value":[{"kind":"identifier","text":"CameraEditView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}