{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getErrorMsg"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/pkiappbio\/geterrormsg()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/pkiappbio\/geterrormsg()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getErrorMsg()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getErrorMsg"},{"kind":"text","text":"()"}],"title":"getErrorMsg()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)PKIAppBio(im)getErrorMsg","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"getErrorMsg"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio":{"role":"symbol","title":"PKIAppBio","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIAppBio"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PKIAppBio"}],"url":"\/documentation\/cshub_test\/pkiappbio"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/getErrorMsg()":{"role":"symbol","title":"getErrorMsg()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getErrorMsg"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getErrorMsg()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getErrorMsg"}],"url":"\/documentation\/cshub_test\/pkiappbio\/geterrormsg()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getErrorMsg"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getErrorMsg"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getErrorMsg"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio\/title","value":"PKIAppBio"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio\/fragments","value":[{"kind":"identifier","text":"PKIAppBio"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getErrorMsg()\/title","value":"getErrorMsg"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getErrorMsg()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getErrorMsg"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}