{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/drawingdevicetype\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/drawingdevicetype\/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/disabled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"title":"DrawingDeviceType.disabled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@DrawingDeviceType@DrawingDeviceDisabled","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceDisabled"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType":{"role":"symbol","title":"DrawingDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DrawingDeviceType"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceType"}],"url":"\/documentation\/cshub_test\/drawingdevicetype"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/disabled":{"role":"symbol","title":"DrawingDeviceType.disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/disabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceDisabled"}],"url":"\/documentation\/cshub_test\/drawingdevicetype\/disabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DrawingDeviceDisabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceDisabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DrawingDeviceDisabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType\/title","value":"DrawingDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceType"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1disabled\/title","value":"DrawingDeviceDisabled"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1disabled\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceDisabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}