{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWacom"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/drawingdevicetype\/typewacom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/drawingdevicetype\/typewacom"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeWacom","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWacom"}],"title":"DrawingDeviceType.typeWacom","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@DrawingDeviceType@DrawingDeviceTypeWacom","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/typeWacom":{"role":"symbol","title":"DrawingDeviceType.typeWacom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWacom"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeWacom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}],"url":"\/documentation\/cshub_test\/drawingdevicetype\/typewacom"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType":{"role":"symbol","title":"DrawingDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DrawingDeviceType"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceType"}],"url":"\/documentation\/cshub_test\/drawingdevicetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DrawingDeviceTypeWacom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1typeWacom\/title","value":"DrawingDeviceTypeWacom"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1typeWacom\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType\/title","value":"DrawingDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}