{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/backgroundimageview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/backgroundimageview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController\/backgroundImageView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"title":"backgroundImageView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)BioPadRemoteSignpadViewController(py)backgroundImageView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"backgroundImageView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteSignpadViewController/backgroundImageView":{"role":"symbol","title":"backgroundImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController\/backgroundImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundImageView"}],"url":"\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/backgroundimageview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteSignpadViewController":{"role":"symbol","title":"BioPadRemoteSignpadViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}],"url":"\/documentation\/cshub_test\/biopadremotesignpadviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"backgroundImageView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"backgroundImageView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"backgroundImageView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController~1backgroundImageView\/title","value":"backgroundImageView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController~1backgroundImageView\/fragments","value":[{"kind":"identifier","text":"backgroundImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController\/title","value":"BioPadRemoteSignpadViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}