{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate","text":"IOS_PadRemoteDelegate"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andSignpadDelegate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"signpadDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","preciseIdentifier":"c:objc(pl)SignpadViewControllerDelegate","text":"SignpadViewControllerDelegate"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/init(delegate:andsignpaddelegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/init(delegate:andsignpaddelegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController\/init(delegate:andSignpadDelegate:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andSignpadDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SignpadViewControllerDelegate","preciseIdentifier":"c:objc(pl)SignpadViewControllerDelegate"},{"kind":"text","text":"!)"}],"title":"init(delegate:andSignpadDelegate:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)BioPadRemoteSignpadViewController(im)initWithDelegate:andSignpadDelegate:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:andSignpadDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteSignpadViewController/init(delegate:andSignpadDelegate:)":{"role":"symbol","title":"init(delegate:andSignpadDelegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"andSignpadDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SignpadViewControllerDelegate","preciseIdentifier":"c:objc(pl)SignpadViewControllerDelegate"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController\/init(delegate:andSignpadDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:andSignpadDelegate:"}],"url":"\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/init(delegate:andsignpaddelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate":{"role":"symbol","title":"IOS_PadRemoteDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteSignpadViewController":{"role":"symbol","title":"BioPadRemoteSignpadViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}],"url":"\/documentation\/cshub_test\/biopadremotesignpadviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate":{"role":"symbol","title":"SignpadViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDelegate:andSignpadDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:andSignpadDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<IOS_PadRemoteDelegate>","preciseIdentifier":"c:Qoobjc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"andSignpadDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SignpadViewControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)SignpadViewControllerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"signpadDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController~1init(delegate:andSignpadDelegate:)\/title","value":"initWithDelegate:andSignpadDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController~1init(delegate:andSignpadDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:andSignpadDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/title","value":"IOS_PadRemoteDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController\/title","value":"BioPadRemoteSignpadViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/title","value":"SignpadViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}