{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","preciseIdentifier":"c:objc(pl)SignpadViewControllerDelegate","text":"SignpadViewControllerDelegate"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/signpaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/signpaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController\/signpadDelegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SignpadViewControllerDelegate","preciseIdentifier":"c:objc(pl)SignpadViewControllerDelegate"},{"kind":"text","text":"!"}],"title":"signpadDelegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)BioPadRemoteSignpadViewController(py)signpadDelegate","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"signpadDelegate"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteSignpadViewController/signpadDelegate":{"role":"symbol","title":"signpadDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SignpadViewControllerDelegate","preciseIdentifier":"c:objc(pl)SignpadViewControllerDelegate"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController\/signpadDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signpadDelegate"}],"url":"\/documentation\/cshub_test\/biopadremotesignpadviewcontroller\/signpaddelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate":{"role":"symbol","title":"SignpadViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteSignpadViewController":{"role":"symbol","title":"BioPadRemoteSignpadViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteSignpadViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}],"url":"\/documentation\/cshub_test\/biopadremotesignpadviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"signpadDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"signpadDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SignpadViewControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)SignpadViewControllerDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"signpadDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController~1signpadDelegate\/title","value":"signpadDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController~1signpadDelegate\/fragments","value":[{"kind":"identifier","text":"signpadDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/title","value":"SignpadViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController\/title","value":"BioPadRemoteSignpadViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteSignpadViewController\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteSignpadViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}