{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeatSigningButtonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)DocumentListButtonView","text":"DocumentListButtonView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/documentitemcell\/repeatsigningbuttonview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell\/repeatSigningButtonView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeatSigningButtonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentListButtonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)DocumentListButtonView"}],"title":"repeatSigningButtonView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test16DocumentItemCellC23repeatSigningButtonViewAA0c4ListhI0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentItemCell/repeatSigningButtonView":{"role":"symbol","title":"repeatSigningButtonView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"repeatSigningButtonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentListButtonView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)DocumentListButtonView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell\/repeatSigningButtonView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentitemcell\/repeatsigningbuttonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView":{"role":"symbol","title":"DocumentListButtonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentListButtonView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentListButtonView"}],"url":"\/documentation\/cshub_test\/documentlistbuttonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentItemCell":{"role":"symbol","title":"DocumentItemCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentItemCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentItemCell"}],"url":"\/documentation\/cshub_test\/documentitemcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentListButtonView\/title","value":"DocumentListButtonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentListButtonView\/fragments","value":[{"kind":"identifier","text":"DocumentListButtonView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentItemCell\/title","value":"DocumentItemCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentItemCell\/fragments","value":[{"kind":"identifier","text":"DocumentItemCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}