{"variants":[{"paths":["\/documentation\/cshub_test\/applepencilreachability\/cbcentralmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/applepencilreachability\/cbcentralmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/CBCentralManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didConnect:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didDisconnectPeripheral:error:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManagerDidUpdateState(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"CBCentralManagerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/centralManager(_:didConnect:)":{"role":"symbol","title":"centralManager(_:didConnect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didConnect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didConnect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"centralManager:didConnectPeripheral:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/centralmanager(_:didconnect:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/centralManager(_:didDisconnectPeripheral:error:)":{"role":"symbol","title":"centralManager(_:didDisconnectPeripheral:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didDisconnectPeripheral:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"centralManager:didDisconnectPeripheral:error:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/centralmanager(_:diddisconnectperipheral:error:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability":{"role":"symbol","title":"ApplePencilReachability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePencilReachability"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePencilReachability"}],"url":"\/documentation\/cshub_test\/applepencilreachability"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/centralManagerDidUpdateState(_:)":{"role":"symbol","title":"centralManagerDidUpdateState(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManagerDidUpdateState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManagerDidUpdateState(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"centralManagerDidUpdateState:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/centralmanagerdidupdatestate(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didConnect:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didDisconnectPeripheral:error:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManagerDidUpdateState(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManager(_:didConnect:)\/title","value":"centralManager:didConnectPeripheral:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManager(_:didConnect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:didConnectPeripheral:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManager(_:didDisconnectPeripheral:error:)\/title","value":"centralManager:didDisconnectPeripheral:error:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManager(_:didDisconnectPeripheral:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:didDisconnectPeripheral:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/title","value":"ApplePencilReachability"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/fragments","value":[{"kind":"identifier","text":"ApplePencilReachability"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManagerDidUpdateState(_:)\/title","value":"centralManagerDidUpdateState:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManagerDidUpdateState(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManagerDidUpdateState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}