{"variants":[{"paths":["\/documentation\/cshub_test\/applepencilreachability\/cbperipheraldelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/applepencilreachability\/cbperipheraldelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/CBPeripheralDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didDiscoverCharacteristicsFor:error:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didDiscoverServices:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didUpdateValueFor:error:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"CBPeripheralDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability":{"role":"symbol","title":"ApplePencilReachability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePencilReachability"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePencilReachability"}],"url":"\/documentation\/cshub_test\/applepencilreachability"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/peripheral(_:didDiscoverServices:)":{"role":"symbol","title":"peripheral(_:didDiscoverServices:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDiscoverServices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didDiscoverServices:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peripheral:didDiscoverServices:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/peripheral(_:diddiscoverservices:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/peripheral(_:didDiscoverCharacteristicsFor:error:)":{"role":"symbol","title":"peripheral(_:didDiscoverCharacteristicsFor:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDiscoverCharacteristicsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBService","preciseIdentifier":"c:objc(cs)CBService"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didDiscoverCharacteristicsFor:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peripheral:didDiscoverCharacteristicsForService:error:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/peripheral(_:diddiscovercharacteristicsfor:error:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/peripheral(_:didUpdateValueFor:error:)":{"role":"symbol","title":"peripheral(_:didUpdateValueFor:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateValueFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBCharacteristic","preciseIdentifier":"c:objc(cs)CBCharacteristic"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didUpdateValueFor:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peripheral:didUpdateValueForCharacteristic:error:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/peripheral(_:didupdatevaluefor:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didDiscoverCharacteristicsFor:error:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didDiscoverServices:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didUpdateValueFor:error:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/title","value":"ApplePencilReachability"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/fragments","value":[{"kind":"identifier","text":"ApplePencilReachability"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didDiscoverServices:)\/title","value":"peripheral:didDiscoverServices:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didDiscoverServices:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didDiscoverServices:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didDiscoverCharacteristicsFor:error:)\/title","value":"peripheral:didDiscoverCharacteristicsForService:error:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didDiscoverCharacteristicsFor:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didDiscoverCharacteristicsForService:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didUpdateValueFor:error:)\/title","value":"peripheral:didUpdateValueForCharacteristic:error:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didUpdateValueFor:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didUpdateValueForCharacteristic:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}