{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"central"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/applepencilreachability\/centralmanager(_:diddisconnectperipheral:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/applepencilreachability\/centralmanager(_:diddisconnectperipheral:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didDisconnectPeripheral:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CBCentralManagerDelegate.centralManager(_:didDisconnectPeripheral:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"centralManager:didDisconnectPeripheral:error:"}],"role":"symbol","title":"centralManager(_:didDisconnectPeripheral:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)ApplePencilReachability(im)centralManager:didDisconnectPeripheral:error:","extendedModule":"CSHub_Test","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/CBCentralManagerDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability":{"role":"symbol","title":"ApplePencilReachability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePencilReachability"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePencilReachability"}],"url":"\/documentation\/cshub_test\/applepencilreachability"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/centralManager(_:didDisconnectPeripheral:error:)":{"role":"symbol","title":"centralManager(_:didDisconnectPeripheral:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centralManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectPeripheral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/centralManager(_:didDisconnectPeripheral:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"centralManager:didDisconnectPeripheral:error:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/centralmanager(_:diddisconnectperipheral:error:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/CBCentralManagerDelegate-Implementations":{"role":"collectionGroup","title":"CBCentralManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/CBCentralManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/applepencilreachability\/cbcentralmanagerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"centralManager:didDisconnectPeripheral:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:didDisconnectPeripheral:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"centralManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCentralManager","preciseIdentifier":"c:objc(cs)CBCentralManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"central"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDisconnectPeripheral:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/title","value":"ApplePencilReachability"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/fragments","value":[{"kind":"identifier","text":"ApplePencilReachability"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManager(_:didDisconnectPeripheral:error:)\/title","value":"centralManager:didDisconnectPeripheral:error:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1centralManager(_:didDisconnectPeripheral:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centralManager:didDisconnectPeripheral:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}