{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBatteryLevel"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/applepencilreachability\/checkbatterylevel()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/applepencilreachability\/checkbatterylevel()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/checkBatteryLevel()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBatteryLevel"},{"kind":"text","text":"()"}],"title":"checkBatteryLevel()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)ApplePencilReachability(im)checkBatteryLevel","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"checkBatteryLevel"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/checkBatteryLevel()":{"role":"symbol","title":"checkBatteryLevel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBatteryLevel"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/checkBatteryLevel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkBatteryLevel"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/checkbatterylevel()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability":{"role":"symbol","title":"ApplePencilReachability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePencilReachability"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePencilReachability"}],"url":"\/documentation\/cshub_test\/applepencilreachability"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"checkBatteryLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkBatteryLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"checkBatteryLevel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1checkBatteryLevel()\/title","value":"checkBatteryLevel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1checkBatteryLevel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkBatteryLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/title","value":"ApplePencilReachability"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/fragments","value":[{"kind":"identifier","text":"ApplePencilReachability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}