{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateValueFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"characteristic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBCharacteristic","preciseIdentifier":"c:objc(cs)CBCharacteristic"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/applepencilreachability\/peripheral(_:didupdatevaluefor:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/applepencilreachability\/peripheral(_:didupdatevaluefor:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didUpdateValueFor:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CBPeripheralDelegate.peripheral(_:didUpdateValueFor:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateValueFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBCharacteristic","preciseIdentifier":"c:objc(cs)CBCharacteristic"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"peripheral(_:didUpdateValueFor:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)ApplePencilReachability(im)peripheral:didUpdateValueForCharacteristic:error:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"peripheral:didUpdateValueForCharacteristic:error:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/CBPeripheralDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/CBPeripheralDelegate-Implementations":{"role":"collectionGroup","title":"CBPeripheralDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/CBPeripheralDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/applepencilreachability\/cbperipheraldelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability":{"role":"symbol","title":"ApplePencilReachability","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePencilReachability"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePencilReachability"}],"url":"\/documentation\/cshub_test\/applepencilreachability"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplePencilReachability/peripheral(_:didUpdateValueFor:error:)":{"role":"symbol","title":"peripheral(_:didUpdateValueFor:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peripheral"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateValueFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CBCharacteristic","preciseIdentifier":"c:objc(cs)CBCharacteristic"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplePencilReachability\/peripheral(_:didUpdateValueFor:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peripheral:didUpdateValueForCharacteristic:error:"}],"url":"\/documentation\/cshub_test\/applepencilreachability\/peripheral(_:didupdatevaluefor:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"peripheral:didUpdateValueForCharacteristic:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didUpdateValueForCharacteristic:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"peripheral:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBPeripheral","preciseIdentifier":"c:objc(cs)CBPeripheral"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"peripheral"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateValueForCharacteristic:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBCharacteristic","preciseIdentifier":"c:objc(cs)CBCharacteristic"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"characteristic"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/title","value":"ApplePencilReachability"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability\/fragments","value":[{"kind":"identifier","text":"ApplePencilReachability"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didUpdateValueFor:error:)\/title","value":"peripheral:didUpdateValueForCharacteristic:error:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ApplePencilReachability~1peripheral(_:didUpdateValueFor:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peripheral:didUpdateValueForCharacteristic:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}