{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationResponse","preciseIdentifier":"c:objc(cs)WKNavigationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"WKNavigationResponsePolicy","preciseIdentifier":"c:@E@WKNavigationResponsePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/thumbnailgenerator\/webview(_:decidepolicyfor:decisionhandler:)-8yfdt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/thumbnailgenerator\/webview(_:decidepolicyfor:decisionhandler:)-8yfdt"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-8yfdt","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationResponse:decisionHandler:"}],"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationResponse","preciseIdentifier":"c:objc(cs)WKNavigationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationResponsePolicy","preciseIdentifier":"c:@E@WKNavigationResponsePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)ThumbnailGenerator(im)webView:decidePolicyForNavigationResponse:decisionHandler:","extendedModule":"CSHub_Test","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/WKNavigationDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator":{"role":"symbol","title":"ThumbnailGenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailGenerator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailGenerator"}],"url":"\/documentation\/cshub_test\/thumbnailgenerator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator/webView(_:decidePolicyFor:decisionHandler:)-8yfdt":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationResponse","preciseIdentifier":"c:objc(cs)WKNavigationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationResponsePolicy","preciseIdentifier":"c:@E@WKNavigationResponsePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-8yfdt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationResponse:decisionHandler:"}],"url":"\/documentation\/cshub_test\/thumbnailgenerator\/webview(_:decidepolicyfor:decisionhandler:)-8yfdt"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator/WKNavigationDelegate-Implementations":{"role":"collectionGroup","title":"WKNavigationDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/WKNavigationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/thumbnailgenerator\/wknavigationdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:decidePolicyForNavigationResponse:decisionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationResponse:decisionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"decidePolicyForNavigationResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKNavigationResponse","preciseIdentifier":"c:objc(cs)WKNavigationResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"navigationResponse"},{"kind":"text","text":" "},{"kind":"identifier","text":"decisionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum WKNavigationResponsePolicy)","preciseIdentifier":"c:BFv(#$@E@WKNavigationResponsePolicy)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"decisionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator\/title","value":"ThumbnailGenerator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator\/fragments","value":[{"kind":"identifier","text":"ThumbnailGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:decidePolicyFor:decisionHandler:)-8yfdt\/title","value":"webView:decidePolicyForNavigationResponse:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:decidePolicyFor:decisionHandler:)-8yfdt\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationResponse:decisionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}