{"variants":[{"paths":["\/documentation\/cshub_test\/thumbnailgenerator\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/thumbnailgenerator\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/WKNavigationDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-1zhjk","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-8yfdt","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:didFinish:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"WKNavigationDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator/webView(_:decidePolicyFor:decisionHandler:)-8yfdt":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationResponse","preciseIdentifier":"c:objc(cs)WKNavigationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationResponsePolicy","preciseIdentifier":"c:@E@WKNavigationResponsePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-8yfdt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationResponse:decisionHandler:"}],"url":"\/documentation\/cshub_test\/thumbnailgenerator\/webview(_:decidepolicyfor:decisionhandler:)-8yfdt"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator":{"role":"symbol","title":"ThumbnailGenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThumbnailGenerator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThumbnailGenerator"}],"url":"\/documentation\/cshub_test\/thumbnailgenerator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator/webView(_:decidePolicyFor:decisionHandler:)-1zhjk":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-1zhjk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"url":"\/documentation\/cshub_test\/thumbnailgenerator\/webview(_:decidepolicyfor:decisionhandler:)-1zhjk"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ThumbnailGenerator/webView(_:didFinish:)":{"role":"symbol","title":"webView(_:didFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:didFinish:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}],"url":"\/documentation\/cshub_test\/thumbnailgenerator\/webview(_:didfinish:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-1zhjk","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:decidePolicyFor:decisionHandler:)-8yfdt","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ThumbnailGenerator\/webView(_:didFinish:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:decidePolicyFor:decisionHandler:)-8yfdt\/title","value":"webView:decidePolicyForNavigationResponse:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:decidePolicyFor:decisionHandler:)-8yfdt\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationResponse:decisionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator\/title","value":"ThumbnailGenerator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator\/fragments","value":[{"kind":"identifier","text":"ThumbnailGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:decidePolicyFor:decisionHandler:)-1zhjk\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:decidePolicyFor:decisionHandler:)-1zhjk\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:didFinish:)\/title","value":"webView:didFinishNavigation:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ThumbnailGenerator~1webView(_:didFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFinishNavigation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}