{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"e2eTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pairs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Pair","text":"Pair"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Future","preciseIdentifier":"s:10CSHub_Test6FutureC","text":"Future"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Task","text":"Task"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"<#return value description#>"}]}]},{"kind":"parameters","parameters":[{"name":"appID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"<#appID description#>"}]}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"<#callback description#>"}]}]},{"name":"pairs","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"<#pairs description#>"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/task\/e2etask(for:callback:pairs:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/e2eTask(for:callback:pairs:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"creates mock "},{"type":"codeVoice","code":"Task"},{"type":"text","text":" from query data obtained via intercepted "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"codeVoice","code":"cshub:\/\/"},{"type":"text","text":" scheme during E2E process nextFlow handling"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"e2eTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pairs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Pair","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Pair"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Task","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Task"},{"kind":"text","text":">"}],"title":"e2eTask(for:callback:pairs:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"s:10CSHub_Test4TaskC03e2eC03for8callback5pairsAA6FutureCyACGSSSg_AKSayAA4PairCGSgtFZ","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Future":{"role":"symbol","title":"Future","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Future"}],"abstract":[{"type":"codeVoice","code":"Future"},{"type":"text","text":" type representing "},{"type":"strong","inlineContent":[{"type":"text","text":"asynchronous return value of the function"}]},{"type":"text","text":" "},{"type":"text","text":"that can be observed later on in the future. returned type will be either success"},{"type":"text","text":" "},{"type":"text","text":"with a value "},{"type":"codeVoice","code":"T"},{"type":"text","text":" or failure with an error "},{"type":"codeVoice","code":"E"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Future","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Future"}],"url":"\/documentation\/cshub_test\/future"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task":{"role":"symbol","title":"Task","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Task"}],"abstract":[{"type":"text","text":"object received from NOBE representing action for the consultant"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Task"}],"url":"\/documentation\/cshub_test\/task"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/e2eTask(for:callback:pairs:)":{"role":"symbol","title":"e2eTask(for:callback:pairs:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"e2eTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pairs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Pair","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Pair"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Task","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Task"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates mock "},{"type":"codeVoice","code":"Task"},{"type":"text","text":" from query data obtained via intercepted "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"codeVoice","code":"cshub:\/\/"},{"type":"text","text":" scheme during E2E process nextFlow handling"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/e2eTask(for:callback:pairs:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/e2etask(for:callback:pairs:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair":{"role":"symbol","title":"Pair","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pair"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pair"}],"url":"\/documentation\/cshub_test\/pair"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task\/title","value":"Task"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task\/fragments","value":[{"kind":"identifier","text":"Task"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair\/title","value":"Pair"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair\/fragments","value":[{"kind":"identifier","text":"Pair"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}