{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ios_padremotedelegate\/pdfdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ios_padremotedelegate\/pdfdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/pdfData()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"title":"pdfData()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)IOS_PadRemoteDelegate(im)pdfData","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"pdfData"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/pdfData()":{"role":"symbol","title":"pdfData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/pdfData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pdfData"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate\/pdfdata()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate":{"role":"symbol","title":"IOS_PadRemoteDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pdfData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pdfData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pdfData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1pdfData()\/title","value":"pdfData"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1pdfData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pdfData"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/title","value":"IOS_PadRemoteDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}