{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:decidepolicyfor:decisionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:decidepolicyfor:decisionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:decidePolicyFor:decisionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"webView(_:decidePolicyFor:decisionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)WebApplicationCoordinator(im)webView:decidePolicyForNavigationAction:decisionHandler:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/webView(_:decidePolicyFor:decisionHandler:)":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:decidePolicyFor:decisionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:decidepolicyfor:decisionhandler:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator":{"role":"symbol","title":"WebApplicationCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationCoordinator"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"decidePolicyForNavigationAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"navigationAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"decisionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum WKNavigationActionPolicy)","preciseIdentifier":"c:BFv(#$@E@WKNavigationActionPolicy)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"decisionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:decidePolicyFor:decisionHandler:)\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator\/title","value":"WebApplicationCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator\/fragments","value":[{"kind":"identifier","text":"WebApplicationCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}