{"variants":[{"paths":["\/documentation\/cshub_test\/defaultcameramanager\/avcapturevideodataoutputsamplebufferdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/defaultcameramanager\/avcapturevideodataoutputsamplebufferdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCameraManager\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCameraManager\/captureOutput(_:didOutput:from:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCameraManager"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCameraManager/captureOutput(_:didOutput:from:)":{"role":"symbol","title":"captureOutput(_:didOutput:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCameraManager\/captureOutput(_:didOutput:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}],"url":"\/documentation\/cshub_test\/defaultcameramanager\/captureoutput(_:didoutput:from:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCameraManager":{"role":"symbol","title":"DefaultCameraManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCameraManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCameraManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultCameraManager"}],"url":"\/documentation\/cshub_test\/defaultcameramanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCameraManager\/captureOutput(_:didOutput:from:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultCameraManager~1captureOutput(_:didOutput:from:)\/title","value":"captureOutput:didOutputSampleBuffer:fromConnection:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultCameraManager~1captureOutput(_:didOutput:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultCameraManager\/title","value":"DefaultCameraManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultCameraManager\/fragments","value":[{"kind":"identifier","text":"DefaultCameraManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}