{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cameraviewmodel\/collectionview(_:layout:sizeforitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/cameraviewmodel\/collectionview(_:layout:sizeforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/collectionView(_:layout:sizeForItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDelegateFlowLayout.collectionView(_:layout:sizeForItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"collectionView(_:layout:sizeForItemAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)CameraViewModel(im)collectionView:layout:sizeForItemAtIndexPath:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegateFlowLayout-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/UICollectionViewDelegateFlowLayout-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegateFlowLayout-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/uicollectionviewdelegateflowlayout-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel":{"role":"symbol","title":"CameraViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewModel"}],"url":"\/documentation\/cshub_test\/cameraviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/collectionView(_:layout:sizeForItemAt:)":{"role":"symbol","title":"collectionView(_:layout:sizeForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/collectionView(_:layout:sizeForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"url":"\/documentation\/cshub_test\/cameraviewmodel\/collectionview(_:layout:sizeforitemat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeForItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel\/title","value":"CameraViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel\/fragments","value":[{"kind":"identifier","text":"CameraViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}