{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishProcessingPhoto"},{"kind":"text","text":" "},{"kind":"internalParam","text":"photo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"find the polygon feature in the photo, overwrite the "},{"type":"codeVoice","code":"detectedImageProperty"},{"type":"text","text":" "},{"type":"text","text":"and the "},{"type":"codeVoice","code":"detectedFeatureProperty"},{"type":"text","text":" raw video frame with the newly captured"},{"type":"text","text":" "},{"type":"text","text":"photo and set the "},{"type":"codeVoice","code":"imageProperty"},{"type":"text","text":" to invoke the reactive chain in the"},{"type":"text","text":" "},{"type":"codeVoice","code":"CameraViewController"},{"type":"text","text":" (4032.0, 3024.0)"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cameraviewmodel\/photooutput(_:didfinishprocessingphoto:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/cameraviewmodel\/photooutput(_:didfinishprocessingphoto:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/photoOutput(_:didFinishProcessingPhoto:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"process the highres photo captured from the camera"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}],"role":"symbol","title":"photoOutput(_:didFinishProcessingPhoto:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishProcessingPhoto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)CameraViewModel(im)captureOutput:didFinishProcessingPhoto:error:","extendedModule":"CSHub_Test","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/AVCapturePhotoCaptureDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/AVCapturePhotoCaptureDelegate-Implementations":{"role":"collectionGroup","title":"AVCapturePhotoCaptureDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/AVCapturePhotoCaptureDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/avcapturephotocapturedelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel":{"role":"symbol","title":"CameraViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewModel"}],"url":"\/documentation\/cshub_test\/cameraviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/photoOutput(_:didFinishProcessingPhoto:error:)":{"role":"symbol","title":"photoOutput(_:didFinishProcessingPhoto:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishProcessingPhoto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"process the highres photo captured from the camera"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/photoOutput(_:didFinishProcessingPhoto:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}],"url":"\/documentation\/cshub_test\/cameraviewmodel\/photooutput(_:didfinishprocessingphoto:error:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"captureOutput:didFinishProcessingPhoto:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"captureOutput:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"output"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishProcessingPhoto:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"photo"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel\/title","value":"CameraViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel\/fragments","value":[{"kind":"identifier","text":"CameraViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel~1photoOutput(_:didFinishProcessingPhoto:error:)\/title","value":"captureOutput:didFinishProcessingPhoto:error:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel~1photoOutput(_:didFinishProcessingPhoto:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}