{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifyingGlass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraMagnifierView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraMagnifierView","text":"CameraMagnifierView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/camerapolygonview\/magnifyingglass"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/magnifyingGlass","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifyingGlass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraMagnifierView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraMagnifierView"},{"kind":"text","text":"?"}],"title":"magnifyingGlass","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test17CameraPolygonViewC15magnifyingGlassAA0c9MagnifierE0CSgvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/magnifyingGlass":{"role":"symbol","title":"magnifyingGlass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifyingGlass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraMagnifierView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraMagnifierView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/magnifyingGlass","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/magnifyingglass"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView":{"role":"symbol","title":"CameraPolygonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"abstract":[{"type":"text","text":"user interactive polygon view with 4 points and magnifier"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPolygonView"}],"url":"\/documentation\/cshub_test\/camerapolygonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraMagnifierView":{"role":"symbol","title":"CameraMagnifierView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraMagnifierView"}],"abstract":[{"type":"text","text":"View responsible for aiding the user during point repositioning"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraMagnifierView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraMagnifierView"}],"url":"\/documentation\/cshub_test\/cameramagnifierview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/title","value":"CameraPolygonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/fragments","value":[{"kind":"identifier","text":"CameraPolygonView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraMagnifierView\/title","value":"CameraMagnifierView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraMagnifierView\/fragments","value":[{"kind":"identifier","text":"CameraMagnifierView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}