{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"touches"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"touches","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A set of UITouch instances that represent the touches for the"},{"type":"text","text":" "},{"type":"text","text":"ending phase of the event represented by event. For touches in"},{"type":"text","text":" "},{"type":"text","text":"a view, this set contains only one touch by default. To receive"},{"type":"text","text":" "},{"type":"text","text":"multiple touches, you must set the view’s isMultipleTouchEnabled"},{"type":"text","text":" "},{"type":"text","text":"property to true."}]}]},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The event to which the touches belong."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/camerapolygonview\/touchescancelled(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/camerapolygonview\/touchescancelled(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesCancelled(_:with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"enforces the cleanup by calling the "},{"type":"codeVoice","code":"touchesEnded(_ touches, with event)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesCancelled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"title":"touchesCancelled(_:with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)CameraPolygonView(im)touchesCancelled:withEvent:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"touchesCancelled:withEvent:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/touchesCancelled(_:with:)":{"role":"symbol","title":"touchesCancelled(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesCancelled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"enforces the cleanup by calling the "},{"type":"codeVoice","code":"touchesEnded(_ touches, with event)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesCancelled(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchesCancelled:withEvent:"}],"url":"\/documentation\/cshub_test\/camerapolygonview\/touchescancelled(_:with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView":{"role":"symbol","title":"CameraPolygonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"abstract":[{"type":"text","text":"user interactive polygon view with 4 points and magnifier"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPolygonView"}],"url":"\/documentation\/cshub_test\/camerapolygonview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"touchesCancelled:withEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesCancelled:withEvent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"touchesCancelled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<UITouch *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"touches"},{"kind":"text","text":" "},{"kind":"identifier","text":"withEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesCancelled(_:with:)\/title","value":"touchesCancelled:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesCancelled(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesCancelled:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/title","value":"CameraPolygonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/fragments","value":[{"kind":"identifier","text":"CameraPolygonView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}