{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAction"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zeniddocumentselectionpopupview\/dismissaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zeniddocumentselectionpopupview\/dismissaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentSelectionPopupView\/dismissAction()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAction"},{"kind":"text","text":"()"}],"title":"dismissAction()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)ZenIDDocumentSelectionPopupView(im)dismissAction","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"dismissAction"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentSelectionPopupView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentSelectionPopupView/dismissAction()":{"role":"symbol","title":"dismissAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentSelectionPopupView\/dismissAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissAction"}],"url":"\/documentation\/cshub_test\/zeniddocumentselectionpopupview\/dismissaction()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentSelectionPopupView":{"role":"symbol","title":"ZenIDDocumentSelectionPopupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDDocumentSelectionPopupView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentSelectionPopupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDDocumentSelectionPopupView"}],"url":"\/documentation\/cshub_test\/zeniddocumentselectionpopupview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dismissAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismissAction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentSelectionPopupView~1dismissAction()\/title","value":"dismissAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentSelectionPopupView~1dismissAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentSelectionPopupView\/title","value":"ZenIDDocumentSelectionPopupView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentSelectionPopupView\/fragments","value":[{"kind":"identifier","text":"ZenIDDocumentSelectionPopupView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}