{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearBackground"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremoteviewcontroller\/clearbackground()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremoteviewcontroller\/clearbackground()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteViewController\/clearBackground()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearBackground"},{"kind":"text","text":"()"}],"title":"clearBackground()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)BioPadRemoteViewController(im)clearBackground","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"clearBackground"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteViewController"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteViewController/clearBackground()":{"role":"symbol","title":"clearBackground()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearBackground"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteViewController\/clearBackground()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearBackground"}],"url":"\/documentation\/cshub_test\/biopadremoteviewcontroller\/clearbackground()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteViewController":{"role":"symbol","title":"BioPadRemoteViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteViewController"}],"url":"\/documentation\/cshub_test\/biopadremoteviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearBackground"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearBackground"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearBackground"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteViewController~1clearBackground()\/title","value":"clearBackground"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteViewController~1clearBackground()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteViewController\/title","value":"BioPadRemoteViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteViewController\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}