{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"wholeViewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":" "},{"kind":"internalParam","text":"confirmSignatureFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDelegate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate","text":"IOS_PadRemoteDelegate"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ios_client\/init(wholeviewframe:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:anddelegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ios_client\/init(wholeviewframe:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:anddelegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"wholeViewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":"!)"}],"title":"init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)IOS_Client(im)initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client":{"role":"symbol","title":"IOS_Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_Client"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_Client"}],"url":"\/documentation\/cshub_test\/ios_client"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)":{"role":"symbol","title":"init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"wholeViewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"}],"url":"\/documentation\/cshub_test\/ios_client\/init(wholeviewframe:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:anddelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate":{"role":"symbol","title":"IOS_PadRemoteDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithWholeViewFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"wholeViewFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDpi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"dpi"},{"kind":"text","text":" "},{"kind":"identifier","text":"signingFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"signingFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSignatureButtonFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confirmSignatureFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearButtonFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"clearButtonFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"andCancelSigningButtonFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cancelSigningButtonFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"andDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<IOS_PadRemoteDelegate>","preciseIdentifier":"c:Qoobjc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client\/title","value":"IOS_Client"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client\/fragments","value":[{"kind":"identifier","text":"IOS_Client"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)\/title","value":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/title","value":"IOS_PadRemoteDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}