{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setViewFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"wholeViewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":" "},{"kind":"internalParam","text":"confirmSignatureFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ios_client\/setviewframe(_:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ios_client\/setviewframe(_:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setViewFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)IOS_Client(im)setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)":{"role":"symbol","title":"setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setViewFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}],"url":"\/documentation\/cshub_test\/ios_client\/setviewframe(_:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client":{"role":"symbol","title":"IOS_Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_Client"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_Client"}],"url":"\/documentation\/cshub_test\/ios_client"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setViewFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"wholeViewFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDpi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"dpi"},{"kind":"text","text":" "},{"kind":"identifier","text":"signingFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"signingFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSignatureButtonFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confirmSignatureFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearButtonFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"clearButtonFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"andCancelSigningButtonFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cancelSigningButtonFrame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)\/title","value":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client\/title","value":"IOS_Client"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client\/fragments","value":[{"kind":"identifier","text":"IOS_Client"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}