{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":" "},{"kind":"internalParam","text":"elementName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":" "},{"kind":"internalParam","text":"attributeDict"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"] = [:])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biocertificatemanager\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biocertificatemanager\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"XMLParserDelegate.parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"title":"parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)BioCertificateManager(im)parser:didStartElement:namespaceURI:qualifiedName:attributes:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/XMLParserDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)":{"role":"symbol","title":"parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}],"url":"\/documentation\/cshub_test\/biocertificatemanager\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager":{"role":"symbol","title":"BioCertificateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioCertificateManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioCertificateManager"}],"url":"\/documentation\/cshub_test\/biocertificatemanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/XMLParserDelegate-Implementations":{"role":"collectionGroup","title":"XMLParserDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/XMLParserDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/xmlparserdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"parser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSXMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parser"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartElement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"elementName"},{"kind":"text","text":" "},{"kind":"identifier","text":"namespaceURI:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"namespaceURI"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualifiedName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"qName"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"attributeDict"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/title","value":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager\/title","value":"BioCertificateManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager\/fragments","value":[{"kind":"identifier","text":"BioCertificateManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}