{"variants":[{"paths":["\/documentation\/cshub_test\/biocertificatemanager\/xmlparserdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biocertificatemanager\/xmlparserdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/XMLParserDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"XMLParserDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager":{"role":"symbol","title":"BioCertificateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioCertificateManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioCertificateManager"}],"url":"\/documentation\/cshub_test\/biocertificatemanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)":{"role":"symbol","title":"parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"XMLParser","preciseIdentifier":"c:objc(cs)NSXMLParser"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"namespaceURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualifiedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}],"url":"\/documentation\/cshub_test\/biocertificatemanager\/parser(_:didstartelement:namespaceuri:qualifiedname:attributes:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager\/title","value":"BioCertificateManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager\/fragments","value":[{"kind":"identifier","text":"BioCertificateManager"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/title","value":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager~1parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parser:didStartElement:namespaceURI:qualifiedName:attributes:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}