{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote","text":"IOS_PadRemote"},{"kind":"text","text":" * "},{"kind":"identifier","text":"padRemote"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview\/padremote"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemote","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"padRemote"}],"title":"padRemote","roleHeading":"Instance Variable","role":"symbol","symbolKind":"ivar","externalID":"c:objc(cs)BioPadRemoteDrawingView@padRemote","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"padRemote"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView":{"role":"symbol","title":"BioPadRemoteDrawingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/padRemote":{"role":"symbol","title":"padRemote","fragments":[{"kind":"identifier","text":"padRemote"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemote","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/padremote"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemote":{"role":"symbol","title":"IOS_PadRemote","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemote"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemote"}],"url":"\/documentation\/cshub_test\/ios_padremote"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/title","value":"BioPadRemoteDrawingView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemote\/title","value":"IOS_PadRemote"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemote\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemote"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}