{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteSizeCoefficient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview\/padremotesizecoefficient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview\/padremotesizecoefficient"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemoteSizeCoefficient","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteSizeCoefficient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"padRemoteSizeCoefficient","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)BioPadRemoteDrawingView(py)padRemoteSizeCoefficient","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"padRemoteSizeCoefficient"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView":{"role":"symbol","title":"BioPadRemoteDrawingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/padRemoteSizeCoefficient":{"role":"symbol","title":"padRemoteSizeCoefficient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteSizeCoefficient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemoteSizeCoefficient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"padRemoteSizeCoefficient"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/padremotesizecoefficient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"padRemoteSizeCoefficient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"padRemoteSizeCoefficient"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteSizeCoefficient"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/title","value":"BioPadRemoteDrawingView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1padRemoteSizeCoefficient\/title","value":"padRemoteSizeCoefficient"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1padRemoteSizeCoefficient\/fragments","value":[{"kind":"identifier","text":"padRemoteSizeCoefficient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}