{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOwn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"padRemote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote","text":"IOS_PadRemote"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview\/setown(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview\/setown(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setOwn(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOwn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote"},{"kind":"text","text":"!)"}],"title":"setOwn(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)BioPadRemoteDrawingView(im)setOwnPadRemote:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"setOwnPadRemote:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView":{"role":"symbol","title":"BioPadRemoteDrawingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemote":{"role":"symbol","title":"IOS_PadRemote","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemote"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemote"}],"url":"\/documentation\/cshub_test\/ios_padremote"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/setOwn(_:)":{"role":"symbol","title":"setOwn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOwn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setOwn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setOwnPadRemote:"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/setown(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setOwnPadRemote:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOwnPadRemote:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setOwnPadRemote:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote","text":"IOS_PadRemote"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"padRemote"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/title","value":"BioPadRemoteDrawingView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemote\/title","value":"IOS_PadRemote"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemote\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemote"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setOwn(_:)\/title","value":"setOwnPadRemote:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setOwn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOwnPadRemote:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}