{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCertficate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identityRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bioSignDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SecCertificate","preciseIdentifier":"c:@T@SecCertificateRef"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/bioidentitymanager\/getcertficate(identityref:biosigndelegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/bioidentitymanager\/getcertficate(identityref:biosigndelegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager\/getCertficate(identityRef:bioSignDelegate:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCertficate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identityRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bioSignDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SecCertificate","preciseIdentifier":"c:@T@SecCertificateRef"},{"kind":"text","text":"?"}],"title":"getCertficate(identityRef:bioSignDelegate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)BioIdentityManager(im)getCertficateWithIdentityRef:bioSignDelegate:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"getCertficateWithIdentityRef:bioSignDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioIdentityManager":{"role":"symbol","title":"BioIdentityManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioIdentityManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioIdentityManager"}],"url":"\/documentation\/cshub_test\/bioidentitymanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioIdentityManager/getCertficate(identityRef:bioSignDelegate:)":{"role":"symbol","title":"getCertficate(identityRef:bioSignDelegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCertficate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identityRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bioSignDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SecCertificate","preciseIdentifier":"c:@T@SecCertificateRef"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager\/getCertficate(identityRef:bioSignDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCertficateWithIdentityRef:bioSignDelegate:"}],"url":"\/documentation\/cshub_test\/bioidentitymanager\/getcertficate(identityref:biosigndelegate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getCertficateWithIdentityRef:bioSignDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCertficateWithIdentityRef:bioSignDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__SecCertificate","preciseIdentifier":"c:@S@__SecCertificate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getCertficateWithIdentityRef:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"identityRef"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioSignDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bioSignDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager\/title","value":"BioIdentityManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager\/fragments","value":[{"kind":"identifier","text":"BioIdentityManager"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager~1getCertficate(identityRef:bioSignDelegate:)\/title","value":"getCertficateWithIdentityRef:bioSignDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager~1getCertficate(identityRef:bioSignDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCertficateWithIdentityRef:bioSignDelegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}