{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BioIdentityManager","text":"BioIdentityManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/bioidentitymanager\/getinstance()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/bioidentitymanager\/getinstance()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager\/getInstance()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"BioIdentityManager","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BioIdentityManager"}],"title":"getInstance()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)BioIdentityManager(cm)getInstance","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"getInstance"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioIdentityManager/getInstance()":{"role":"symbol","title":"getInstance()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"BioIdentityManager","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BioIdentityManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager\/getInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getInstance"}],"url":"\/documentation\/cshub_test\/bioidentitymanager\/getinstance()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioIdentityManager":{"role":"symbol","title":"BioIdentityManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioIdentityManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioIdentityManager"}],"url":"\/documentation\/cshub_test\/bioidentitymanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getInstance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInstance"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioIdentityManager","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BioIdentityManager","text":"BioIdentityManager"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getInstance"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager~1getInstance()\/title","value":"getInstance"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager~1getInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager\/title","value":"BioIdentityManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioIdentityManager\/fragments","value":[{"kind":"identifier","text":"BioIdentityManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}