{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView","text":"ZenIDCardFooterView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidconfirmpopupview\/footerview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDConfirmPopupView\/footerView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"title":"footerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test21ZenIDConfirmPopupViewC06footerF0AA0c12IDCardFooterF0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDConfirmPopupView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDConfirmPopupView":{"role":"symbol","title":"ZenIDConfirmPopupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDConfirmPopupView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDConfirmPopupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDConfirmPopupView"}],"url":"\/documentation\/cshub_test\/zenidconfirmpopupview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDConfirmPopupView/footerView":{"role":"symbol","title":"footerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDConfirmPopupView\/footerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidconfirmpopupview\/footerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCardFooterView":{"role":"symbol","title":"ZenIDCardFooterView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCardFooterView"}],"url":"\/documentation\/cshub_test\/zenidcardfooterview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDConfirmPopupView\/title","value":"ZenIDConfirmPopupView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDConfirmPopupView\/fragments","value":[{"kind":"identifier","text":"ZenIDConfirmPopupView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardFooterView\/title","value":"ZenIDCardFooterView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardFooterView\/fragments","value":[{"kind":"identifier","text":"ZenIDCardFooterView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}