{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCallback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":" "},{"kind":"internalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forFunction"},{"kind":"text","text":" "},{"kind":"internalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/sendcallback(withpayload:forfunction:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/sendcallback(withpayload:forfunction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendCallback(withPayload:forFunction:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sendCallbackWithPayload:forFunction:"}],"role":"symbol","title":"sendCallback(withPayload:forFunction:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCallback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forFunction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)SignpadViewControllerDelegate(im)sendCallbackWithPayload:forFunction:","required":true,"modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate/sendCallback(withPayload:forFunction:)":{"navigatorTitle":[{"kind":"identifier","text":"sendCallbackWithPayload:forFunction:"}],"role":"symbol","title":"sendCallback(withPayload:forFunction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCallback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forFunction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendCallback(withPayload:forFunction:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/sendcallback(withpayload:forfunction:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate":{"role":"symbol","title":"SignpadViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendCallbackWithPayload:forFunction:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendCallbackWithPayload:forFunction:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendCallbackWithPayload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"payload"},{"kind":"text","text":" "},{"kind":"identifier","text":"forFunction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"function"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1sendCallback(withPayload:forFunction:)\/title","value":"sendCallbackWithPayload:forFunction:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1sendCallback(withPayload:forFunction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendCallbackWithPayload:forFunction:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/title","value":"SignpadViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}