{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadSizeCoefficient"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/signpadsizecoefficient()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/signpadsizecoefficient()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/signpadSizeCoefficient()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"signpadSizeCoefficient"}],"role":"symbol","title":"signpadSizeCoefficient()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadSizeCoefficient"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"symbolKind":"method","externalID":"c:objc(pl)SignpadViewControllerDelegate(im)signpadSizeCoefficient","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate":{"role":"symbol","title":"SignpadViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate/signpadSizeCoefficient()":{"navigatorTitle":[{"kind":"identifier","text":"signpadSizeCoefficient"}],"role":"symbol","title":"signpadSizeCoefficient()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadSizeCoefficient"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/signpadSizeCoefficient()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/signpadsizecoefficient()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"signpadSizeCoefficient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signpadSizeCoefficient"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"identifier","text":"signpadSizeCoefficient"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/title","value":"SignpadViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1signpadSizeCoefficient()\/title","value":"signpadSizeCoefficient"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1signpadSizeCoefficient()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signpadSizeCoefficient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}