{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/appdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)FIRMessagingDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIApplicationDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UNUserNotificationCenterDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/airwatch","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/appLinkManager","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationStepper","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/asamManager","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/featureFlagProvider","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/gcmMessageIDKey","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/hardwareIDRepository","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/monitoringManager","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/orientationLock","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/pushManager","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:open:options:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationDidBecomeActive(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationDidEnterBackground(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillEnterForeground(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillResignActive(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillTerminate(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/isNewDay(storedDate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/messaging(_:didRefreshRegistrationToken:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/removeCachedDocumentsIfNecessary()"]},{"title":"Type Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/lockCurrentOrientation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/lockOrientation(withMask:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/lockOrientation(withMask:andRotateTo:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/unlockOrientation()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/MessagingDelegate-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"title":"AppDelegate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)AppDelegate","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(cs)UIResponder":{"type":"unresolvable","title":"UIResponder","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIResponder"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/monitoringManager":{"role":"symbol","title":"monitoringManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitoringManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MonitoringManager","preciseIdentifier":"s:10CSHub_Test17MonitoringManagerP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/monitoringManager","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/monitoringmanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationWillResignActive(_:)":{"role":"symbol","title":"applicationWillResignActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillResignActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillResignActive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillResignActive:"}],"url":"\/documentation\/cshub_test\/appdelegate\/applicationwillresignactive(_:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationDidEnterBackground(_:)":{"role":"symbol","title":"applicationDidEnterBackground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidEnterBackground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method to release shared resources, save user data, invalidate timers, and store enough application state"},{"type":"text","text":" "},{"type":"text","text":"information to restore your application to its current state in case it is terminated later. If your application"},{"type":"text","text":" "},{"type":"text","text":"supports background execution, this method is called instead of applicationWillTerminate: when the user quits."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationDidEnterBackground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidEnterBackground:"}],"url":"\/documentation\/cshub_test\/appdelegate\/applicationdidenterbackground(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/window":{"role":"symbol","title":"window","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/window","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"window"}],"url":"\/documentation\/cshub_test\/appdelegate\/window"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/airwatch":{"role":"symbol","title":"airwatch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"airwatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Airwatch","preciseIdentifier":"s:10CSHub_Test8AirwatchP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/airwatch","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/airwatch"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/cshub_test\/appdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/asamManager":{"role":"symbol","title":"asamManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"asamManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AsamManager","preciseIdentifier":"s:10CSHub_Test11AsamManagerP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/asamManager","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/asammanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationWillTerminate(_:)":{"role":"symbol","title":"applicationWillTerminate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillTerminate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the application is about to terminate. Save data if appropriate."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillTerminate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillTerminate:"}],"url":"\/documentation\/cshub_test\/appdelegate\/applicationwillterminate(_:)"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/appLinkManager":{"role":"symbol","title":"appLinkManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appLinkManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppLinkManager","preciseIdentifier":"s:10CSHub_Test14AppLinkManagerP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/appLinkManager","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/applinkmanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationWillEnterForeground(_:)":{"role":"symbol","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called as part of the transition from the background to the active state; here you can"},{"type":"text","text":" "},{"type":"text","text":"undo many of the changes made on entering the background."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillEnterForeground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"url":"\/documentation\/cshub_test\/appdelegate\/applicationwillenterforeground(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/removeCachedDocumentsIfNecessary()":{"role":"symbol","title":"removeCachedDocumentsIfNecessary()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCachedDocumentsIfNecessary"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/removeCachedDocumentsIfNecessary()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/removecacheddocumentsifnecessary()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationDidBecomeActive(_:)":{"role":"symbol","title":"applicationDidBecomeActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidBecomeActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Restart any tasks that were paused (or not yet started) while the application was inactive."},{"type":"text","text":" "},{"type":"text","text":"If the application was previously in the background, optionally refresh the user interface."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationDidBecomeActive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidBecomeActive:"}],"url":"\/documentation\/cshub_test\/appdelegate\/applicationdidbecomeactive(_:)"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(pl)FIRMessagingDelegate":{"type":"unresolvable","title":"FirebaseMessaging.MessagingDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)FIRMessagingDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/UIApplicationDelegate-Implementations":{"role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/uiapplicationdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/MessagingDelegate-Implementations":{"role":"collectionGroup","title":"MessagingDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/MessagingDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/messagingdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/featureFlagProvider":{"role":"symbol","title":"featureFlagProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureFlagProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FeatureFlagProviderProtocol","preciseIdentifier":"s:18FeatureFlagLibrary0aB16ProviderProtocolP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/featureFlagProvider","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/featureflagprovider"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/hardwareIDRepository":{"role":"symbol","title":"hardwareIDRepository","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardwareIDRepository"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HardwareIDRepository","preciseIdentifier":"s:10CSHub_Test20HardwareIDRepositoryP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/hardwareIDRepository","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/hardwareidrepository"},"doc://cz.csas.app.cshub.test/objc(pl)UIApplicationDelegate":{"type":"unresolvable","title":"UIApplicationDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIApplicationDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/unlockOrientation()":{"role":"symbol","title":"unlockOrientation()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlockOrientation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/unlockOrientation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/unlockorientation()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationStepper":{"role":"symbol","title":"applicationStepper","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationStepper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppStepper","preciseIdentifier":"s:10CSHub_Test10AppStepperP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationStepper","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/applicationstepper"},"doc://cz.csas.app.cshub.test/objc(pl)UNUserNotificationCenterDelegate":{"type":"unresolvable","title":"UserNotifications.UNUserNotificationCenterDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UNUserNotificationCenterDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/application(_:didFinishLaunchingWithOptions:)":{"role":"symbol","title":"application(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"url":"\/documentation\/cshub_test\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/messaging(_:didRefreshRegistrationToken:)":{"role":"symbol","title":"messaging(_:didRefreshRegistrationToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRefreshRegistrationToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/messaging(_:didRefreshRegistrationToken:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/messaging(_:didrefreshregistrationtoken:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/gcmMessageIDKey":{"role":"symbol","title":"gcmMessageIDKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"gcmMessageIDKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/gcmMessageIDKey","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/gcmmessageidkey"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/orientationLock":{"role":"symbol","title":"orientationLock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/orientationLock","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/orientationlock"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cshub_test\/appdelegate\/init"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/lockOrientation(withMask:)":{"role":"symbol","title":"lockOrientation(withMask:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/lockOrientation(withMask:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/lockorientation(withmask:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/lockOrientation(withMask:andRotateTo:)":{"role":"symbol","title":"lockOrientation(withMask:andRotateTo:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andRotateTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientation","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/lockOrientation(withMask:andRotateTo:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/lockorientation(withmask:androtateto:)"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/pushManager":{"role":"symbol","title":"pushManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushManager","preciseIdentifier":"s:10CSHub_Test11PushManagerP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/pushManager","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/pushmanager"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/application(_:open:options:)":{"role":"symbol","title":"application(_:open:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"OpenURLOptionsKey","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"called from share extension after the file has been saved to shared container allowing cshub to"},{"type":"text","text":" "},{"type":"text","text":"access it. filesystem path is transfered via the "},{"type":"codeVoice","code":"sharedFile"},{"type":"text","text":" key inside the "},{"type":"codeVoice","code":"appdata"},{"type":"text","text":" section"},{"type":"text","text":" "},{"type":"text","text":"in the "},{"type":"codeVoice","code":"cshubappdata"},{"type":"text","text":" part of the url query"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:open:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:openURL:options:"}],"url":"\/documentation\/cshub_test\/appdelegate\/application(_:open:options:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/application(_:supportedInterfaceOrientationsFor:)":{"role":"symbol","title":"application(_:supportedInterfaceOrientationsFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedInterfaceOrientationsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}],"url":"\/documentation\/cshub_test\/appdelegate\/application(_:supportedinterfaceorientationsfor:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/lockCurrentOrientation()":{"role":"symbol","title":"lockCurrentOrientation()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockCurrentOrientation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/lockCurrentOrientation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/lockcurrentorientation()"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/isNewDay(storedDate:)":{"role":"symbol","title":"isNewDay(storedDate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNewDay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"storedDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/isNewDay(storedDate:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/isnewday(storeddate:)"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AppDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:open:options:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationDidBecomeActive(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationDidEnterBackground(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillEnterForeground(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillResignActive(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillTerminate(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/init"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/MessagingDelegate-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIApplicationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIResponder","preciseIdentifier":"c:objc(cs)UIResponder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillResignActive(_:)\/title","value":"applicationWillResignActive:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillResignActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillResignActive:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationDidEnterBackground(_:)\/title","value":"applicationDidEnterBackground:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationDidEnterBackground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidEnterBackground:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1window\/title","value":"window"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillTerminate(_:)\/title","value":"applicationWillTerminate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillTerminate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillTerminate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillEnterForeground(_:)\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillEnterForeground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationDidBecomeActive(_:)\/title","value":"applicationDidBecomeActive:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationDidBecomeActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidBecomeActive:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:open:options:)\/title","value":"application:openURL:options:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:open:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:openURL:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/title","value":"application:supportedInterfaceOrientationsForWindow:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}