{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appointmentview"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ChooseTermViewStep1","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ConfirmView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CreateNoteView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DoneView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/render()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/resolveConstraints()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/setupBindings(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/unsetupBindings()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentView"}],"title":"AppointmentView","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test15AppointmentViewP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"AppointmentView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ChooseTermViewStep1":{"role":"symbol","title":"ChooseTermViewStep1","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChooseTermViewStep1"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ChooseTermViewStep1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChooseTermViewStep1"}],"url":"\/documentation\/cshub_test\/choosetermviewstep1"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RecapitulationViewStep2":{"role":"symbol","title":"RecapitulationViewStep2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecapitulationViewStep2"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecapitulationViewStep2"}],"url":"\/documentation\/cshub_test\/recapitulationviewstep2"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentView":{"role":"symbol","title":"AppointmentView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentView"}],"url":"\/documentation\/cshub_test\/appointmentview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DoneView":{"role":"symbol","title":"DoneView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DoneView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DoneView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DoneView"}],"url":"\/documentation\/cshub_test\/doneview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ConfirmView":{"role":"symbol","title":"ConfirmView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfirmView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ConfirmView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfirmView"}],"url":"\/documentation\/cshub_test\/confirmview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentView/unsetupBindings()":{"role":"symbol","title":"unsetupBindings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsetupBindings"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/unsetupBindings()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/appointmentview\/unsetupbindings()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentView/render()":{"role":"symbol","title":"render()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/render()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/appointmentview\/render()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentView/setupBindings(with:)":{"role":"symbol","title":"setupBindings(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OldAppointmentViewModel","preciseIdentifier":"s:10CSHub_Test23OldAppointmentViewModelC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/setupBindings(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/appointmentview\/setupbindings(with:)"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIKit.UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentView/resolveConstraints()":{"role":"symbol","title":"resolveConstraints()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolveConstraints"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentView\/resolveConstraints()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/appointmentview\/resolveconstraints()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CreateNoteView":{"role":"symbol","title":"CreateNoteView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateNoteView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CreateNoteView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreateNoteView"}],"url":"\/documentation\/cshub_test\/createnoteview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ChooseTermViewStep1\/title","value":"ChooseTermViewStep1"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ChooseTermViewStep1\/fragments","value":[{"kind":"identifier","text":"ChooseTermViewStep1"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2\/title","value":"RecapitulationViewStep2"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2\/fragments","value":[{"kind":"identifier","text":"RecapitulationViewStep2"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DoneView\/title","value":"DoneView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DoneView\/fragments","value":[{"kind":"identifier","text":"DoneView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ConfirmView\/title","value":"ConfirmView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ConfirmView\/fragments","value":[{"kind":"identifier","text":"ConfirmView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CreateNoteView\/title","value":"CreateNoteView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CreateNoteView\/fragments","value":[{"kind":"identifier","text":"CreateNoteView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}