{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioCertificateManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biocertificatemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biocertificatemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSXMLParserDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/bioDataCertificateConfigFileData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/bioDataCertificateConfigFileSignatureData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/bioDataCertificateData"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/certificateDataFromAppProfile(callback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/downloadOrRefreshCertificateAndConfigurationForEncryptedBioData(authToken:callback:)"]},{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/shared"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/XMLParserDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioCertificateManager"}],"title":"BioCertificateManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)BioCertificateManager","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"BioCertificateManager"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/XMLParserDelegate-Implementations":{"role":"collectionGroup","title":"XMLParserDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/XMLParserDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/xmlparserdelegate-implementations"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/downloadOrRefreshCertificateAndConfigurationForEncryptedBioData(authToken:callback:)":{"role":"symbol","title":"downloadOrRefreshCertificateAndConfigurationForEncryptedBioData(authToken:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadOrRefreshCertificateAndConfigurationForEncryptedBioData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/downloadOrRefreshCertificateAndConfigurationForEncryptedBioData(authToken:callback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/downloadorrefreshcertificateandconfigurationforencryptedbiodata(authtoken:callback:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BioCertificateManager","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BioCertificateManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/shared","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/shared"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager":{"role":"symbol","title":"BioCertificateManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioCertificateManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioCertificateManager"}],"url":"\/documentation\/cshub_test\/biocertificatemanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/bioDataCertificateConfigFileData":{"role":"symbol","title":"bioDataCertificateConfigFileData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioDataCertificateConfigFileData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/bioDataCertificateConfigFileData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/biodatacertificateconfigfiledata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cshub_test\/biocertificatemanager\/init"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/bioDataCertificateConfigFileSignatureData":{"role":"symbol","title":"bioDataCertificateConfigFileSignatureData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioDataCertificateConfigFileSignatureData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/bioDataCertificateConfigFileSignatureData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/biodatacertificateconfigfilesignaturedata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/bioDataCertificateData":{"role":"symbol","title":"bioDataCertificateData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioDataCertificateData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/bioDataCertificateData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/biodatacertificatedata"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioCertificateManager/certificateDataFromAppProfile(callback:)":{"role":"symbol","title":"certificateDataFromAppProfile(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"certificateDataFromAppProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/certificateDataFromAppProfile(callback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biocertificatemanager\/certificatedatafromappprofile(callback:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)NSXMLParserDelegate":{"type":"unresolvable","title":"Foundation.XMLParserDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSXMLParserDelegate"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BioCertificateManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BioCertificateManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BioCertificateManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/init"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioCertificateManager\/XMLParserDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioCertificateManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager\/title","value":"BioCertificateManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioCertificateManager\/fragments","value":[{"kind":"identifier","text":"BioCertificateManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}