{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biopadremotedrawingview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/initOpenGL","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemoteSizeCoefficient"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/cleanup()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/clearCallback()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/erase()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getDrawingDevice()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getPadRemote()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getPointsCount()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setConfirmButtonPosition(_:andCallback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setDrawingDeviceType(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setOwn(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setupBrush(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"title":"BioPadRemoteDrawingView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)BioPadRemoteDrawingView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/getPadRemote()":{"role":"symbol","title":"getPadRemote()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPadRemote"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getPadRemote()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPadRemote"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/getpadremote()"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/padRemoteSizeCoefficient":{"role":"symbol","title":"padRemoteSizeCoefficient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteSizeCoefficient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemoteSizeCoefficient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"padRemoteSizeCoefficient"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/padremotesizecoefficient"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/setDrawingDeviceType(_:)":{"role":"symbol","title":"setDrawingDeviceType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDrawingDeviceType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DrawingDeviceType","preciseIdentifier":"c:@E@DrawingDeviceType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setDrawingDeviceType(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDrawingDeviceType:"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/setdrawingdevicetype(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/padRemote":{"role":"symbol","title":"padRemote","fragments":[{"kind":"identifier","text":"padRemote"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemote","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/padremote"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/backingHeight":{"role":"symbol","title":"backingHeight","fragments":[{"kind":"identifier","text":"backingHeight"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/backingHeight","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/backingheight"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/setOwn(_:)":{"role":"symbol","title":"setOwn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOwn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setOwn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setOwnPadRemote:"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/setown(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/getDrawingDevice()":{"role":"symbol","title":"getDrawingDevice()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDrawingDevice"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DrawingDeviceType","preciseIdentifier":"c:@E@DrawingDeviceType"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getDrawingDevice()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDrawingDevice"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/getdrawingdevice()"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/bgTexture":{"role":"symbol","title":"bgTexture","fragments":[{"kind":"identifier","text":"bgTexture"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/bgTexture","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/bgtexture"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView":{"role":"symbol","title":"BioPadRemoteDrawingView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/depthRenderbuffer":{"role":"symbol","title":"depthRenderbuffer","fragments":[{"kind":"identifier","text":"depthRenderbuffer"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/depthRenderbuffer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/depthrenderbuffer"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/getPointsCount()":{"role":"symbol","title":"getPointsCount()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPointsCount"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getPointsCount()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPointsCount"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/getpointscount()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/clearCallback()":{"role":"symbol","title":"clearCallback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCallback"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/clearCallback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearCallback"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/clearcallback()"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/brushTexture":{"role":"symbol","title":"brushTexture","fragments":[{"kind":"identifier","text":"brushTexture"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/brushTexture","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/brushtexture"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/context":{"role":"symbol","title":"context","fragments":[{"kind":"identifier","text":"context"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/context","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/context"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/setConfirmButtonPosition(_:andCallback:)":{"role":"symbol","title":"setConfirmButtonPosition(_:andCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfirmButtonPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCallback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setConfirmButtonPosition(_:andCallback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setConfirmButtonPosition:andCallback:"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/setconfirmbuttonposition(_:andcallback:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/cleanup()":{"role":"symbol","title":"cleanup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/cleanup()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanup"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/cleanup()"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/erase()":{"role":"symbol","title":"erase()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"erase"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/erase()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"erase"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/erase()"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/initOpenGL":{"role":"symbol","title":"initOpenGL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initOpenGL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/initOpenGL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOpenGL"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/initopengl"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/viewRenderbuffer":{"role":"symbol","title":"viewRenderbuffer","fragments":[{"kind":"identifier","text":"viewRenderbuffer"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/viewRenderbuffer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/viewrenderbuffer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/viewFramebuffer":{"role":"symbol","title":"viewFramebuffer","fragments":[{"kind":"identifier","text":"viewFramebuffer"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/viewFramebuffer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/viewframebuffer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/setupBrush(_:)":{"role":"symbol","title":"setupBrush(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBrush"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setupBrush(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupBrush:"}],"url":"\/documentation\/cshub_test\/biopadremotedrawingview\/setupbrush(_:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteDrawingView/backingWidth":{"role":"symbol","title":"backingWidth","fragments":[{"kind":"identifier","text":"backingWidth"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/backingWidth","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biopadremotedrawingview\/backingwidth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BioPadRemoteDrawingView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Variables","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/backingHeight","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/backingWidth","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/bgTexture","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/brushTexture","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/context","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/depthRenderbuffer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemote","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/viewFramebuffer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/viewRenderbuffer"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/initOpenGL","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/padRemoteSizeCoefficient"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/cleanup()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/clearCallback()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/erase()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getDrawingDevice()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getPadRemote()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/getPointsCount()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setConfirmButtonPosition(_:andCallback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setDrawingDeviceType(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setOwn(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteDrawingView\/setupBrush(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteDrawingView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1getPadRemote()\/title","value":"getPadRemote"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1getPadRemote()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPadRemote"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1padRemoteSizeCoefficient\/title","value":"padRemoteSizeCoefficient"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1padRemoteSizeCoefficient\/fragments","value":[{"kind":"identifier","text":"padRemoteSizeCoefficient"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setDrawingDeviceType(_:)\/title","value":"setDrawingDeviceType:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setDrawingDeviceType(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDrawingDeviceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setOwn(_:)\/title","value":"setOwnPadRemote:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setOwn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOwnPadRemote:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1getDrawingDevice()\/title","value":"getDrawingDevice"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1getDrawingDevice()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDrawingDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/title","value":"BioPadRemoteDrawingView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteDrawingView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1getPointsCount()\/title","value":"getPointsCount"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1getPointsCount()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPointsCount"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1clearCallback()\/title","value":"clearCallback"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1clearCallback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setConfirmButtonPosition(_:andCallback:)\/title","value":"setConfirmButtonPosition:andCallback:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setConfirmButtonPosition(_:andCallback:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConfirmButtonPosition:andCallback:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1cleanup()\/title","value":"cleanup"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1cleanup()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanup"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1erase()\/title","value":"erase"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1erase()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"erase"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1initOpenGL\/title","value":"initOpenGL"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1initOpenGL\/fragments","value":[{"kind":"identifier","text":"initOpenGL"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setupBrush(_:)\/title","value":"setupBrush:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteDrawingView~1setupBrush(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupBrush:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}