{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignpadTransactionManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biosignpadtransactionmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/biosignpadtransactionmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionInjectable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/accessToken","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/bioDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/deleteParty(withCallback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/downloadImage(url:callback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/getAccessToken()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/registerOrSyncParty(withCallback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/removeCurrentTransaction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/sendMessage(ofType:forFunction:withPayload:callId:callback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/set(accessToken:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/showSyncFailedDialog(inController:tryAgainAction:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/startListening(controllerForPresentingOfDialogs:withCallback:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/startNewTransaction(bioDelegate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/stopListening()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/tranactionInProgress()"]},{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/shared"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignpadTransactionManager"}],"title":"BioSignpadTransactionManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)BioSignpadTransactionManager","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"BioSignpadTransactionManager"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/set(accessToken:)":{"role":"symbol","title":"set(accessToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/set(accessToken:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/set(accesstoken:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/startNewTransaction(bioDelegate:)":{"role":"symbol","title":"startNewTransaction(bioDelegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startNewTransaction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bioDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BioSignDelegate","preciseIdentifier":"s:10CSHub_Test15BioSignDelegateP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/startNewTransaction(bioDelegate:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/startnewtransaction(biodelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/sendMessage(ofType:forFunction:withPayload:callId:callback:)":{"role":"symbol","title":"sendMessage(ofType:forFunction:withPayload:callId:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forFunction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/sendMessage(ofType:forFunction:withPayload:callId:callback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/sendmessage(oftype:forfunction:withpayload:callid:callback:)"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/showSyncFailedDialog(inController:tryAgainAction:)":{"role":"symbol","title":"showSyncFailedDialog(inController:tryAgainAction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSyncFailedDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tryAgainAction"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/showSyncFailedDialog(inController:tryAgainAction:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/showsyncfaileddialog(incontroller:tryagainaction:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BioSignpadTransactionManager","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BioSignpadTransactionManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/shared","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/shared"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/removeCurrentTransaction()":{"role":"symbol","title":"removeCurrentTransaction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCurrentTransaction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/removeCurrentTransaction()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/removecurrenttransaction()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/registerOrSyncParty(withCallback:)":{"role":"symbol","title":"registerOrSyncParty(withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOrSyncParty"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/registerOrSyncParty(withCallback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/registerorsyncparty(withcallback:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/downloadImage(url:callback:)":{"role":"symbol","title":"downloadImage(url:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/downloadImage(url:callback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/downloadimage(url:callback:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/accessToken":{"role":"symbol","title":"accessToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/accessToken","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/accesstoken"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/stopListening()":{"role":"symbol","title":"stopListening()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopListening"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/stopListening()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/stoplistening()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/getAccessToken()":{"role":"symbol","title":"getAccessToken()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAccessToken"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/getAccessToken()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/getaccesstoken()"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/deleteParty(withCallback:)":{"role":"symbol","title":"deleteParty(withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteParty"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/deleteParty(withCallback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/deleteparty(withcallback:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/startListening(controllerForPresentingOfDialogs:withCallback:)":{"role":"symbol","title":"startListening(controllerForPresentingOfDialogs:withCallback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startListening"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controllerForPresentingOfDialogs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCallback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"BiosignMessage","preciseIdentifier":"s:10CSHub_Test14BiosignMessageC"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/startListening(controllerForPresentingOfDialogs:withCallback:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/startlistening(controllerforpresentingofdialogs:withcallback:)"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/bioDelegate":{"role":"symbol","title":"bioDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BioSignDelegate","preciseIdentifier":"s:10CSHub_Test15BioSignDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/bioDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/biodelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionInjectable":{"role":"symbol","title":"BioSignpadTransactionInjectable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignpadTransactionInjectable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionInjectable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignpadTransactionInjectable"}],"url":"\/documentation\/cshub_test\/biosignpadtransactioninjectable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager/tranactionInProgress()":{"role":"symbol","title":"tranactionInProgress()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tranactionInProgress"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager\/tranactionInProgress()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignpadtransactionmanager\/tranactioninprogress()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignpadTransactionManager":{"role":"symbol","title":"BioSignpadTransactionManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignpadTransactionManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignpadTransactionManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignpadTransactionManager"}],"url":"\/documentation\/cshub_test\/biosignpadtransactionmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BioSignpadTransactionManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BioSignpadTransactionManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BioSignpadTransactionManager"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignpadTransactionManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioSignpadTransactionManager\/title","value":"BioSignpadTransactionManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioSignpadTransactionManager\/fragments","value":[{"kind":"identifier","text":"BioSignpadTransactionManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}