{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/biosignatureoverlaycontroller"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteViewControllerDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Chainable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSExtensionRequestHandling","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NibLoadable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Progressable","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Reusable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIContentContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIStateRestoring","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/bioDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/bottomConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/cancelButtonView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/confirmButtonView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/cornersView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/coveringViews","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/identityRef","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/leftConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/padRemoteContainer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/retryButtonView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/retryConfirmEnabled","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/rightConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/topConstraint"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/bioDidUpdate(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/deviceId()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/envelopeCertificateData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/getUsername()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/handle(toServer:internalSignatureData:signatureRenderData:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/isRetryConfirmEnabled()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/padRemoteController()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/pdfData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/refreshSignatureSpace()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/removeOverlay()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/removeOverlayDueCancellation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/removeOverlayDueConfirmation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/set(signatureRectangle:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/setStyle()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/showErrorDialog(withMessage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewDidAppear(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewDidLayoutSubviews()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewDidLoad()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewWillDisappear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"title":"BioSignatureOverlayController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:10CSHub_Test29BioSignatureOverlayControllerC","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"BioSignatureOverlayController"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/removeOverlayDueConfirmation()":{"role":"symbol","title":"removeOverlayDueConfirmation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeOverlayDueConfirmation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/removeOverlayDueConfirmation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/removeoverlaydueconfirmation()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/coveringViews":{"role":"symbol","title":"coveringViews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coveringViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/coveringViews","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/coveringviews"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/topConstraint":{"role":"symbol","title":"topConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/topConstraint","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/topconstraint"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ViewControllerStyleable":{"role":"symbol","title":"ViewControllerStyleable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewControllerStyleable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewControllerStyleable"}],"url":"\/documentation\/cshub_test\/viewcontrollerstyleable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/bioDelegate":{"role":"symbol","title":"bioDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BioSignDelegate","preciseIdentifier":"s:10CSHub_Test15BioSignDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/bioDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/biodelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NibLoadable":{"role":"symbol","title":"NibLoadable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NibLoadable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NibLoadable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NibLoadable"}],"url":"\/documentation\/cshub_test\/nibloadable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Presentable":{"role":"symbol","title":"Presentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presentable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Presentable"}],"url":"\/documentation\/cshub_test\/presentable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/cshub_test\/baseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/refreshSignatureSpace()":{"role":"symbol","title":"refreshSignatureSpace()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshSignatureSpace"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/refreshSignatureSpace()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/refreshsignaturespace()"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIContentContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/leftConstraint":{"role":"symbol","title":"leftConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/leftConstraint","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/leftconstraint"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/set(signatureRectangle:)":{"role":"symbol","title":"set(signatureRectangle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"signatureRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/set(signatureRectangle:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/set(signaturerectangle:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/showErrorDialog(withMessage:)":{"role":"symbol","title":"showErrorDialog(withMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showErrorDialog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/showErrorDialog(withMessage:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/showerrordialog(withmessage:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/confirmButtonView":{"role":"symbol","title":"confirmButtonView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmButtonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/confirmButtonView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/confirmbuttonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/removeOverlay()":{"role":"symbol","title":"removeOverlay()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeOverlay"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/removeOverlay()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/removeoverlay()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/cancelButtonView":{"role":"symbol","title":"cancelButtonView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/cancelButtonView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/cancelbuttonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Reusable":{"role":"symbol","title":"Reusable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Reusable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Reusable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Reusable"}],"url":"\/documentation\/cshub_test\/reusable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate":{"role":"symbol","title":"IOS_PadRemoteDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/handle(toServer:internalSignatureData:signatureRenderData:)":{"role":"symbol","title":"handle(toServer:internalSignatureData:signatureRenderData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toServer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"internalSignatureData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"signatureRenderData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/handle(toServer:internalSignatureData:signatureRenderData:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/handle(toserver:internalsignaturedata:signaturerenderdata:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/deviceId()":{"role":"symbol","title":"deviceId()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/deviceId()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/deviceid()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/envelopeCertificateData()":{"role":"symbol","title":"envelopeCertificateData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeCertificateData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/envelopeCertificateData()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/envelopecertificatedata()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/padRemoteController()":{"role":"symbol","title":"padRemoteController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteController"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/padRemoteController()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/padremotecontroller()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/padRemoteContainer":{"role":"symbol","title":"padRemoteContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/padRemoteContainer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/padremotecontainer"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController":{"role":"symbol","title":"BioSignatureOverlayController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignatureOverlayController"}],"url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/pdfData()":{"role":"symbol","title":"pdfData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/pdfData()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/pdfdata()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/bioDidUpdate(_:)":{"role":"symbol","title":"bioDidUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/bioDidUpdate(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/biodidupdate(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/bottomConstraint":{"role":"symbol","title":"bottomConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/bottomConstraint","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/bottomconstraint"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Progressable":{"role":"symbol","title":"Progressable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Progressable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Progressable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Progressable"}],"url":"\/documentation\/cshub_test\/progressable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Chainable":{"role":"symbol","title":"Chainable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chainable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Chainable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chainable"}],"url":"\/documentation\/cshub_test\/chainable"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/viewwilldisappear(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/identityRef":{"role":"symbol","title":"identityRef","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identityRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/identityRef","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/identityref"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/cornersView":{"role":"symbol","title":"cornersView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornersView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/cornersView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/cornersview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/setStyle()":{"role":"symbol","title":"setStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStyle"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/setStyle()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/setstyle()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewDidLoad()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/viewdidload()"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/viewdidlayoutsubviews()"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSExtensionRequestHandling"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/isRetryConfirmEnabled()":{"role":"symbol","title":"isRetryConfirmEnabled()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRetryConfirmEnabled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/isRetryConfirmEnabled()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/isretryconfirmenabled()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/retryButtonView":{"role":"symbol","title":"retryButtonView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryButtonView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/retryButtonView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/retrybuttonview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/getUsername()":{"role":"symbol","title":"getUsername()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUsername"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/getUsername()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/getusername()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/rightConstraint":{"role":"symbol","title":"rightConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/rightConstraint","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/rightconstraint"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioPadRemoteViewControllerDelegate":{"role":"symbol","title":"BioPadRemoteViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioPadRemoteViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioPadRemoteViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioPadRemoteViewControllerDelegate"}],"url":"\/documentation\/cshub_test\/biopadremoteviewcontrollerdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/removeOverlayDueCancellation()":{"role":"symbol","title":"removeOverlayDueCancellation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeOverlayDueCancellation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/removeOverlayDueCancellation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/removeoverlayduecancellation()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/retryConfirmEnabled":{"role":"symbol","title":"retryConfirmEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryConfirmEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/retryConfirmEnabled","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/retryconfirmenabled"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIStateRestoring"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController\/viewDidAppear(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller\/viewdidappear(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/title","value":"IOS_PadRemoteDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteViewControllerDelegate\/title","value":"BioPadRemoteViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BioPadRemoteViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"BioPadRemoteViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}