{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cameraviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/cameraviewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)AVCapturePhotoCaptureDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModelInputs","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModelOutputs","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IViewModel","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICollectionViewDataSource","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICollectionViewDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/captureProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/context","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/coreImageContext","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/deleteFlag","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/generateProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/items","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/pdfLocationProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/renderBuffer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/session","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/throttleTimer"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/capturePhoto()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/createCGBackedUIImageFromCIImage(image:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/createCIContext(from:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/createOpenGLContext()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/disableTorch()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/enableTorch()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/export(image:quality:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/generatePDF(documentName:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/imageRotatedBy(image:deg:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/initBindings(for:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/perspectiveCorrected(image:feature:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/pointsFromViewToPhoto(image:polyPoints:toSize:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/setupGLKView()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/transform(image:withFeature:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/AVCapturePhotoCaptureDelegate-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDataSource-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegate-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegateFlowLayout-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModel"}],"title":"CameraViewModel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)CameraViewModel","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"CameraViewModel"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/renderBuffer":{"role":"symbol","title":"renderBuffer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GLuint","preciseIdentifier":"c:@T@GLuint"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/renderBuffer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/renderbuffer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/context":{"role":"symbol","title":"context","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EAGLContext","preciseIdentifier":"c:objc(cs)EAGLContext"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/context","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/context"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/coreImageContext":{"role":"symbol","title":"coreImageContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coreImageContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/coreImageContext","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/coreimagecontext"},"doc://cz.csas.app.cshub.test/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UIKit.UICollectionViewDataSource","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICollectionViewDataSource"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/uicollectionviewdatasource-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/session":{"role":"symbol","title":"session","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraSession","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraSession"}],"abstract":[{"type":"text","text":"responsible for camera setup"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/session","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/session"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/initBindings(for:)":{"role":"symbol","title":"initBindings(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraViewModel","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraViewModel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Disposable","preciseIdentifier":"s:13ReactiveSwift10DisposableP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/initBindings(for:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/initbindings(for:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/items":{"role":"symbol","title":"items","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PhotoDataStore","preciseIdentifier":"s:10CSHub_Test14PhotoDataStoreC"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/items","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/items"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/AVCapturePhotoCaptureDelegate-Implementations":{"role":"collectionGroup","title":"AVCapturePhotoCaptureDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/AVCapturePhotoCaptureDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/avcapturephotocapturedelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/generatePDF(documentName:)":{"role":"symbol","title":"generatePDF(documentName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generatePDF"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/generatePDF(documentName:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/generatepdf(documentname:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/disableTorch()":{"role":"symbol","title":"disableTorch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableTorch"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/disableTorch()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/disabletorch()"},"doc://cz.csas.app.cshub.test/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cshub_test\/cameraviewmodel\/init()"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/perspectiveCorrected(image:feature:)":{"role":"symbol","title":"perspectiveCorrected(image:feature:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perspectiveCorrected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Quadrilateral","preciseIdentifier":"s:10CSHub_Test13QuadrilateralP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"corects the skewed image based on given coordinates"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/perspectiveCorrected(image:feature:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/perspectivecorrected(image:feature:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/imageRotatedBy(image:deg:)":{"role":"symbol","title":"imageRotatedBy(image:deg:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageRotatedBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deg"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"rotates the image by number of degrees"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/imageRotatedBy(image:deg:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/imagerotatedby(image:deg:)"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/captureProperty":{"role":"symbol","title":"captureProperty","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/captureProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/captureproperty"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/createCGBackedUIImageFromCIImage(image:)":{"role":"symbol","title":"createCGBackedUIImageFromCIImage(image:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCGBackedUIImageFromCIImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" backed by "},{"type":"codeVoice","code":"CGContext"},{"type":"text","text":" so we can obtain the cgImage"},{"type":"text","text":" "},{"type":"text","text":"later on during"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/createCGBackedUIImageFromCIImage(image:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/createcgbackeduiimagefromciimage(image:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/generateProperty":{"role":"symbol","title":"generateProperty","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/generateProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/generateproperty"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/enableTorch()":{"role":"symbol","title":"enableTorch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTorch"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/enableTorch()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/enabletorch()"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/throttleTimer":{"role":"symbol","title":"throttleTimer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"throttleTimer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Timer","preciseIdentifier":"c:objc(cs)NSTimer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/throttleTimer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/throttletimer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/UICollectionViewDelegateFlowLayout-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegateFlowLayout-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/uicollectionviewdelegateflowlayout-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/deleteFlag":{"role":"symbol","title":"deleteFlag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteFlag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageArrayRep","preciseIdentifier":"s:10CSHub_Test13ImageArrayRepV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/deleteFlag","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/deleteflag"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/capturePhoto()":{"role":"symbol","title":"capturePhoto()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturePhoto"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"start the photo capture"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/capturePhoto()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/capturephoto()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModelInputs":{"role":"symbol","title":"CameraViewModelInputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModelInputs"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModelInputs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewModelInputs"}],"url":"\/documentation\/cshub_test\/cameraviewmodelinputs"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/createOpenGLContext()":{"role":"symbol","title":"createOpenGLContext()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenGLContext"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"EAGLContext","preciseIdentifier":"c:objc(cs)EAGLContext"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates OpenGL context used for camera frame and overlay feature drawing"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/createOpenGLContext()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/createopenglcontext()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/pointsFromViewToPhoto(image:polyPoints:toSize:)":{"role":"symbol","title":"pointsFromViewToPhoto(image:polyPoints:toSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pointsFromViewToPhoto"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polyPoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"toSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"transforms the "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" coordinates back to the "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" coordinate space"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/pointsFromViewToPhoto(image:polyPoints:toSize:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/pointsfromviewtophoto(image:polypoints:tosize:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/pdfLocationProperty":{"role":"symbol","title":"pdfLocationProperty","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfLocationProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?>"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/pdfLocationProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/pdflocationproperty"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/setupGLKView()":{"role":"symbol","title":"setupGLKView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupGLKView"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<("},{"kind":"typeIdentifier","text":"GLKView","preciseIdentifier":"c:objc(cs)GLKView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"EAGLContext","preciseIdentifier":"c:objc(cs)EAGLContext"},{"kind":"text","text":")>"}],"abstract":[{"type":"text","text":"top function responsible for "},{"type":"codeVoice","code":"OpenGL"},{"type":"text","text":" view setup with all the"},{"type":"text","text":" "},{"type":"text","text":"objects needed for successful display (contexts & constraints)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/setupGLKView()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/setupglkview()"},"doc://cz.csas.app.cshub.test/objc(pl)AVCapturePhotoCaptureDelegate":{"type":"unresolvable","title":"AVFoundation.AVCapturePhotoCaptureDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)AVCapturePhotoCaptureDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModelOutputs":{"role":"symbol","title":"CameraViewModelOutputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModelOutputs"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModelOutputs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewModelOutputs"}],"url":"\/documentation\/cshub_test\/cameraviewmodeloutputs"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IViewModel":{"role":"symbol","title":"IViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IViewModel"}],"url":"\/documentation\/cshub_test\/iviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/createCIContext(from:)":{"role":"symbol","title":"createCIContext(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCIContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EAGLContext","preciseIdentifier":"c:objc(cs)EAGLContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"EAGLContext","preciseIdentifier":"c:objc(cs)EAGLContext"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" context passing the input parameter as output"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/createCIContext(from:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/createcicontext(from:)"},"doc://cz.csas.app.cshub.test/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICollectionViewDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/transform(image:withFeature:)":{"role":"symbol","title":"transform(image:withFeature:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withFeature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Quadrilateral","preciseIdentifier":"s:10CSHub_Test13QuadrilateralP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates matrix transformed image from the captured image"},{"type":"text","text":" "},{"type":"text","text":"from the supplied feature that has been previously specified"},{"type":"text","text":" "},{"type":"text","text":"by the user"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/transform(image:withFeature:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/transform(image:withfeature:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/export(image:quality:)":{"role":"symbol","title":"export(image:quality:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"export"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JPEGQuality","preciseIdentifier":"s:10CSHub_Test11JPEGQualityO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"drops the image to the local store to be used L8R to create a pdf"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/export(image:quality:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/export(image:quality:)"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/cameraviewmodel\/uicollectionviewdelegate-implementations"},"doc://cz.csas.app.cshub.test/objc(pl)UICollectionViewDelegateFlowLayout":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegateFlowLayout","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICollectionViewDelegateFlowLayout"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewModel":{"role":"symbol","title":"CameraViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewModel"}],"url":"\/documentation\/cshub_test\/cameraviewmodel"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraViewModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraViewModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraViewModel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/init()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/AVCapturePhotoCaptureDelegate-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDataSource-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegate-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewModel\/UICollectionViewDelegateFlowLayout-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel\/title","value":"CameraViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraViewModel\/fragments","value":[{"kind":"identifier","text":"CameraViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}