{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraSession"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Credits: https:\/\/github.com\/navoshta\/MetalRenderCamera"}]}]}]},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Keep in mind that frames arrive in a hardware orientation by default, e.g. "},{"type":"codeVoice","code":".LandscapeRight"},{"type":"text","text":" "},{"type":"text","text":"for the rear camera. You can set the "},{"type":"codeVoice","code":"frameOrientation"},{"type":"text","text":" property to override this behavior"},{"type":"text","text":" "},{"type":"text","text":"and apply auto rotation to each frame."}]}],"type":"aside","name":"Warning"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/camerasession"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/camerasession"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"setups a video camera session"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraSession"}],"title":"CameraSession","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)CameraSession","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"CameraSession"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/borderDetectFrame","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/borderDetectLastRectangleFeature","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/cameraOutput","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureDevice","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureSession","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureSessionQueue","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/detectedFeatureProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/detectedImageProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/device","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/flashModeProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/frameOrientation","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/inputDevice","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/outputData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/previousOrientation","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/rectangleDetector","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/stateProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/torchEnabled","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/videoFrameImage"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/ciImageFromSampleBuffer(for:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/featureFromImage(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/start()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/startSession()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/stop()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true}],"references":{"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/captureSession":{"role":"symbol","title":"captureSession","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureSession","preciseIdentifier":"c:objc(cs)AVCaptureSession"},{"kind":"text","text":"?"}],"abstract":[{"type":"codeVoice","code":"AVFoundation"},{"type":"text","text":" capture session object."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureSession","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/capturesession"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/flashModeProperty":{"role":"symbol","title":"flashModeProperty","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashModeProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FlashMode","preciseIdentifier":"c:@E@AVCaptureFlashMode"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/flashModeProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/flashmodeproperty"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/captureSessionQueue":{"role":"symbol","title":"captureSessionQueue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureSessionQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"}],"abstract":[{"type":"text","text":"Dispatch queue for capture session events."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureSessionQueue","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/capturesessionqueue"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/detectedFeatureProperty":{"role":"symbol","title":"detectedFeatureProperty","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFeatureProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Quadrilateral","preciseIdentifier":"s:10CSHub_Test13QuadrilateralP"},{"kind":"text","text":"?>"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/detectedFeatureProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/detectedfeatureproperty"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/rectangleDetector":{"role":"symbol","title":"rectangleDetector","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectangleDetector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIDetector","preciseIdentifier":"c:objc(cs)CIDetector"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/rectangleDetector","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/rectangledetector"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/start()":{"role":"symbol","title":"start()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts the capture session. Call this method to start receiving delegate updates"},{"type":"text","text":" "},{"type":"text","text":"with the sample buffers."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/start()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/start()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/startSession()":{"role":"symbol","title":"startSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"starts the "},{"type":"codeVoice","code":"captureSession"},{"type":"text","text":" and sets the "},{"type":"codeVoice","code":"CameraGrabPhase"},{"type":"text","text":" to "},{"type":"codeVoice","code":"streaming"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/startSession()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/startsession()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/frameOrientation":{"role":"symbol","title":"frameOrientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Frame orienation. If you want to receive frames in orientation other than the hardware default one,"},{"type":"text","text":" "},{"type":"text","text":"set this "},{"type":"codeVoice","code":"var"},{"type":"text","text":" and this value will be picked up when converting next frame. Although keep in mind"},{"type":"text","text":" "},{"type":"text","text":"that any rotation comes at a performance cost."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/frameOrientation","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/frameorientation"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/inputDevice":{"role":"symbol","title":"inputDevice","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureDeviceInput","preciseIdentifier":"c:objc(cs)AVCaptureDeviceInput"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Current capture input device."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/inputDevice","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/inputdevice"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/previousOrientation":{"role":"symbol","title":"previousOrientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/previousOrientation","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/previousorientation"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/stop()":{"role":"symbol","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the capture session."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/stop()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/stop()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/featureFromImage(_:)":{"role":"symbol","title":"featureFromImage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureFromImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CIRectangleFeature","preciseIdentifier":"c:objc(cs)CIRectangleFeature"},{"kind":"text","text":"?)>"}],"abstract":[{"type":"text","text":"detects rectangle feature in the image"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/featureFromImage(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/featurefromimage(_:)"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/captureDevice":{"role":"symbol","title":"captureDevice","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraCaptureDevice","preciseIdentifier":"s:10CSHub_Test19CameraCaptureDeviceC"}],"abstract":[{"type":"text","text":"Our internal wrapper for the "},{"type":"codeVoice","code":"AVCaptureDevice"},{"type":"text","text":". Making it internal to stub during testing."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureDevice","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/capturedevice"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cshub_test\/camerasession\/init()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/device":{"role":"symbol","title":"device","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/device","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/device"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/borderDetectFrame":{"role":"symbol","title":"borderDetectFrame","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderDetectFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/borderDetectFrame","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/borderdetectframe"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/ciImageFromSampleBuffer(for:)":{"role":"symbol","title":"ciImageFromSampleBuffer(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ciImageFromSampleBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"transforms raw "},{"type":"codeVoice","code":"CMSampleBuffer"},{"type":"text","text":" data received from camera to "},{"type":"codeVoice","code":"CIImage"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/ciImageFromSampleBuffer(for:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/ciimagefromsamplebuffer(for:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/outputData":{"role":"symbol","title":"outputData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoDataOutput","preciseIdentifier":"c:objc(cs)AVCaptureVideoDataOutput"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"video capture data stream output"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/outputData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/outputdata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/detectedImageProperty":{"role":"symbol","title":"detectedImageProperty","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedImageProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":"?>"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/detectedImageProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/detectedimageproperty"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/stateProperty":{"role":"symbol","title":"stateProperty","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CameraGrabPhase","preciseIdentifier":"s:10CSHub_Test15CameraGrabPhaseO"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Current session state."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/stateProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/stateproperty"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession":{"role":"symbol","title":"CameraSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraSession"}],"abstract":[{"type":"text","text":"setups a video camera session"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"url":"\/documentation\/cshub_test\/camerasession"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/borderDetectLastRectangleFeature":{"role":"symbol","title":"borderDetectLastRectangleFeature","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderDetectLastRectangleFeature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIRectangleFeature","preciseIdentifier":"c:objc(cs)CIRectangleFeature"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"preserves the previously detected feature for multiple frames durng capture"},{"type":"text","text":" "},{"type":"text","text":"to allow dection throttle while allowing the display of the feature"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/borderDetectLastRectangleFeature","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/borderdetectlastrectanglefeature"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate":{"type":"unresolvable","title":"AVFoundation.AVCaptureVideoDataOutputSampleBufferDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/cameraOutput":{"role":"symbol","title":"cameraOutput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"}],"abstract":[{"type":"text","text":"video capture photo output"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/cameraOutput","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/cameraoutput"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/torchEnabled":{"role":"symbol","title":"torchEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"torchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/torchEnabled","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/torchenabled"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/videoFrameImage":{"role":"symbol","title":"videoFrameImage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrameImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":"?>"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/videoFrameImage","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerasession\/videoframeimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraSession"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraSession"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraSession"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/init()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraSession"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession\/title","value":"CameraSession"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession\/fragments","value":[{"kind":"identifier","text":"CameraSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}