{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Credits: Javier Berlana https:\/\/github.com\/jberlana\/JBCroppableView\/blob\/master\/JBCroppableView\/JBCroppableLayer.m"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/camerapolygonview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/camerapolygonview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"user interactive polygon view with 4 points and magnifier"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"title":"CameraPolygonView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)CameraPolygonView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPolygonView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/init(delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/activePoint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/delegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/draggedDot","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/lineColor","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/magnifyingGlass","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/pointColor","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/referencePoints","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/strokeColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/addMagnifyingGlassAtPoint(point:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/addPointsAt(points:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/draw(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/drawPageOverlay(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/getPointView(num:at:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/removeMagnifyingGlass()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesBegan(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesCancelled(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesEnded(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesMoved(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/updateMagnifyingGlassAtPoint(point:)"]},{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/magnifyingGlassShowDelay","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/pointWidth"]}],"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/draggedDot":{"role":"symbol","title":"draggedDot","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"draggedDot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/draggedDot","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/draggeddot"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/strokeColor":{"role":"symbol","title":"strokeColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/strokeColor","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/strokecolor"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PolPositionEditing","preciseIdentifier":"s:10CSHub_Test18PolPositionEditingP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/init(delegate:)"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView":{"role":"symbol","title":"CameraPolygonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"}],"abstract":[{"type":"text","text":"user interactive polygon view with 4 points and magnifier"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPolygonView"}],"url":"\/documentation\/cshub_test\/camerapolygonview"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/updateMagnifyingGlassAtPoint(point:)":{"role":"symbol","title":"updateMagnifyingGlassAtPoint(point:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMagnifyingGlassAtPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/updateMagnifyingGlassAtPoint(point:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/updatemagnifyingglassatpoint(point:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/referencePoints":{"role":"symbol","title":"referencePoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referencePoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/referencePoints","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/referencepoints"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PolPositionEditing","preciseIdentifier":"s:10CSHub_Test18PolPositionEditingP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/delegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/touchesBegan(_:with:)":{"role":"symbol","title":"touchesBegan(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesBegan"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"obtains the initial touch position and selects relevant view if grabbed"},{"type":"text","text":" "},{"type":"text","text":"and assigns it into the "},{"type":"codeVoice","code":"draggedDot"},{"type":"text","text":". then adds magnifier to aid the user"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesBegan(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchesBegan:withEvent:"}],"url":"\/documentation\/cshub_test\/camerapolygonview\/touchesbegan(_:with:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/magnifyingGlassShowDelay":{"role":"symbol","title":"magnifyingGlassShowDelay","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifyingGlassShowDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/magnifyingGlassShowDelay","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/magnifyingglassshowdelay"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/drawPageOverlay(_:)":{"role":"symbol","title":"drawPageOverlay(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawPageOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"draws the actual polygon area with altered color"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/drawPageOverlay(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/drawpageoverlay(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/magnifyingGlass":{"role":"symbol","title":"magnifyingGlass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifyingGlass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraMagnifierView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraMagnifierView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/magnifyingGlass","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/magnifyingglass"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/activePoint":{"role":"symbol","title":"activePoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activePoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/activePoint","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/activepoint"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/removeMagnifyingGlass()":{"role":"symbol","title":"removeMagnifyingGlass()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMagnifyingGlass"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/removeMagnifyingGlass()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/removemagnifyingglass()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/touchesCancelled(_:with:)":{"role":"symbol","title":"touchesCancelled(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesCancelled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"enforces the cleanup by calling the "},{"type":"codeVoice","code":"touchesEnded(_ touches, with event)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesCancelled(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchesCancelled:withEvent:"}],"url":"\/documentation\/cshub_test\/camerapolygonview\/touchescancelled(_:with:)"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/getPointView(num:at:)":{"role":"symbol","title":"getPointView(num:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPointView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"num"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"<#Description#>"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/getPointView(num:at:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/getpointview(num:at:)"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/addPointsAt(points:)":{"role":"symbol","title":"addPointsAt(points:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPointsAt"},{"kind":"text","text":"("},{"kind":"externalParam","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"appends rectangle feature corner coordinates to the points array"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/addPointsAt(points:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/addpointsat(points:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/lineColor":{"role":"symbol","title":"lineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/lineColor","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/linecolor"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/draw(_:)":{"role":"symbol","title":"draw(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/draw(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"url":"\/documentation\/cshub_test\/camerapolygonview\/draw(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/addMagnifyingGlassAtPoint(point:)":{"role":"symbol","title":"addMagnifyingGlassAtPoint(point:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addMagnifyingGlassAtPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"draws magnifying glass in the middle of the view to aid users vision"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/addMagnifyingGlassAtPoint(point:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/addmagnifyingglassatpoint(point:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/touchesEnded(_:with:)":{"role":"symbol","title":"touchesEnded(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesEnded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"cleans up the "},{"type":"codeVoice","code":"draggedDot"},{"type":"text","text":" reference to previously moved view, and removes"},{"type":"text","text":" "},{"type":"text","text":"the magnifier view"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesEnded(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchesEnded:withEvent:"}],"url":"\/documentation\/cshub_test\/camerapolygonview\/touchesended(_:with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/touchesMoved(_:with:)":{"role":"symbol","title":"touchesMoved(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesMoved"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"obtains the moved touch position and updates the center value in"},{"type":"text","text":" "},{"type":"codeVoice","code":"draggedDot"},{"type":"text","text":" view. then updates the magnifier view"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesMoved(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchesMoved:withEvent:"}],"url":"\/documentation\/cshub_test\/camerapolygonview\/touchesmoved(_:with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/pointWidth":{"role":"symbol","title":"pointWidth","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pointWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/pointWidth","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/pointwidth"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraPolygonView/pointColor":{"role":"symbol","title":"pointColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pointColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/pointColor","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/camerapolygonview\/pointcolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraPolygonView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraPolygonView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraPolygonView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/draw(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesBegan(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesCancelled(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesEnded(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraPolygonView\/touchesMoved(_:with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPolygonView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/title","value":"CameraPolygonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView\/fragments","value":[{"kind":"identifier","text":"CameraPolygonView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesBegan(_:with:)\/title","value":"touchesBegan:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesBegan(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesBegan:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesCancelled(_:with:)\/title","value":"touchesCancelled:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesCancelled(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesCancelled:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1draw(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesEnded(_:with:)\/title","value":"touchesEnded:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesEnded(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesEnded:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesMoved(_:with:)\/title","value":"touchesMoved:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraPolygonView~1touchesMoved(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesMoved:withEvent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}