{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CellCustomizable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/cellcustomizable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CellCustomizable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CellCustomizable\/configureCell(with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CellCustomizable"}],"title":"CellCustomizable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test16CellCustomizableP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"CellCustomizable"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqCell":{"role":"symbol","title":"FaqCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqCell"}],"url":"\/documentation\/cshub_test\/faqcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentCell":{"role":"symbol","title":"E2eDocumentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentCell"}],"abstract":[{"type":"text","text":"cell with image of first pdf file page"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentCell"}],"url":"\/documentation\/cshub_test\/e2edocumentcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CellCustomizable":{"role":"symbol","title":"CellCustomizable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CellCustomizable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CellCustomizable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CellCustomizable"}],"url":"\/documentation\/cshub_test\/cellcustomizable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CellCustomizable/configureCell(with:)":{"role":"symbol","title":"configureCell(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureCell"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"T","preciseIdentifier":"s:10CSHub_Test16CellCustomizableP09configureC04withyqd___tlF1TL_qd__mfp"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"encapsulated cell setup"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CellCustomizable\/configureCell(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/cellcustomizable\/configurecell(with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/title","value":"FaqCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/fragments","value":[{"kind":"identifier","text":"FaqCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentCell\/title","value":"E2eDocumentCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentCell\/fragments","value":[{"kind":"identifier","text":"E2eDocumentCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}