{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIAMProductView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ciamproductview"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamBSProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamCSPOJProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamCTSProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamDONProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamEDOCProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamEIGERProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamMuinProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPSCSProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPWCProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamRVHPProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamS24ProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSBProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSCOProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSPZProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSSCSProductView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamVKLProductView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView\/contactsStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView\/addViewToStackView(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIAMProductView"}],"title":"CIAMProductView","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test15CIAMProductViewP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"CIAMProductView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamSBProductView":{"role":"symbol","title":"CiamSBProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamSBProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSBProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamSBProductView"}],"url":"\/documentation\/cshub_test\/ciamsbproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamEIGERProductView":{"role":"symbol","title":"CiamEIGERProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamEIGERProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamEIGERProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamEIGERProductView"}],"url":"\/documentation\/cshub_test\/ciameigerproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPSCSProductView":{"role":"symbol","title":"CiamPSCSProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPSCSProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPSCSProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamPSCSProductView"}],"url":"\/documentation\/cshub_test\/ciampscsproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CIAMProductView/contactsStack":{"role":"symbol","title":"contactsStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactsStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView\/contactsStack","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ciamproductview\/contactsstack"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIKit.UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamDONProductView":{"role":"symbol","title":"CiamDONProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamDONProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamDONProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamDONProductView"}],"url":"\/documentation\/cshub_test\/ciamdonproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CIAMProductView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CiamExpandableProductView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CiamExpandableProductView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ciamproductview\/delegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamBSProductView":{"role":"symbol","title":"CiamBSProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamBSProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamBSProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamBSProductView"}],"url":"\/documentation\/cshub_test\/ciambsproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamSSCSProductView":{"role":"symbol","title":"CiamSSCSProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamSSCSProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSSCSProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamSSCSProductView"}],"url":"\/documentation\/cshub_test\/ciamsscsproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamVKLProductView":{"role":"symbol","title":"CiamVKLProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamVKLProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamVKLProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamVKLProductView"}],"url":"\/documentation\/cshub_test\/ciamvklproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamEDOCProductView":{"role":"symbol","title":"CiamEDOCProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamEDOCProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamEDOCProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamEDOCProductView"}],"url":"\/documentation\/cshub_test\/ciamedocproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CIAMProductView/addViewToStackView(_:)":{"role":"symbol","title":"addViewToStackView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addViewToStackView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView\/addViewToStackView(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciamproductview\/addviewtostackview(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamS24ProductView":{"role":"symbol","title":"CiamS24ProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamS24ProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamS24ProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamS24ProductView"}],"url":"\/documentation\/cshub_test\/ciams24productview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamMuinProductView":{"role":"symbol","title":"CiamMuinProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamMuinProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamMuinProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamMuinProductView"}],"url":"\/documentation\/cshub_test\/ciammuinproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPWCProductView":{"role":"symbol","title":"CiamPWCProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPWCProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPWCProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamPWCProductView"}],"url":"\/documentation\/cshub_test\/ciampwcproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamCSPOJProductView":{"role":"symbol","title":"CiamCSPOJProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamCSPOJProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamCSPOJProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamCSPOJProductView"}],"url":"\/documentation\/cshub_test\/ciamcspojproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamSCOProductView":{"role":"symbol","title":"CiamSCOProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamSCOProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSCOProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamSCOProductView"}],"url":"\/documentation\/cshub_test\/ciamscoproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamCTSProductView":{"role":"symbol","title":"CiamCTSProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamCTSProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamCTSProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamCTSProductView"}],"url":"\/documentation\/cshub_test\/ciamctsproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamRVHPProductView":{"role":"symbol","title":"CiamRVHPProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamRVHPProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamRVHPProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamRVHPProductView"}],"url":"\/documentation\/cshub_test\/ciamrvhpproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CIAMProductView":{"role":"symbol","title":"CIAMProductView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIAMProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CIAMProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CIAMProductView"}],"url":"\/documentation\/cshub_test\/ciamproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamSPZProductView":{"role":"symbol","title":"CiamSPZProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamSPZProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSPZProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamSPZProductView"}],"url":"\/documentation\/cshub_test\/ciamspzproductview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSBProductView\/title","value":"CiamSBProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSBProductView\/fragments","value":[{"kind":"identifier","text":"CiamSBProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamEIGERProductView\/title","value":"CiamEIGERProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamEIGERProductView\/fragments","value":[{"kind":"identifier","text":"CiamEIGERProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPSCSProductView\/title","value":"CiamPSCSProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPSCSProductView\/fragments","value":[{"kind":"identifier","text":"CiamPSCSProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamDONProductView\/title","value":"CiamDONProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamDONProductView\/fragments","value":[{"kind":"identifier","text":"CiamDONProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamBSProductView\/title","value":"CiamBSProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamBSProductView\/fragments","value":[{"kind":"identifier","text":"CiamBSProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSSCSProductView\/title","value":"CiamSSCSProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSSCSProductView\/fragments","value":[{"kind":"identifier","text":"CiamSSCSProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamVKLProductView\/title","value":"CiamVKLProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamVKLProductView\/fragments","value":[{"kind":"identifier","text":"CiamVKLProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamEDOCProductView\/title","value":"CiamEDOCProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamEDOCProductView\/fragments","value":[{"kind":"identifier","text":"CiamEDOCProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamS24ProductView\/title","value":"CiamS24ProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamS24ProductView\/fragments","value":[{"kind":"identifier","text":"CiamS24ProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamMuinProductView\/title","value":"CiamMuinProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamMuinProductView\/fragments","value":[{"kind":"identifier","text":"CiamMuinProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPWCProductView\/title","value":"CiamPWCProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPWCProductView\/fragments","value":[{"kind":"identifier","text":"CiamPWCProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamCSPOJProductView\/title","value":"CiamCSPOJProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamCSPOJProductView\/fragments","value":[{"kind":"identifier","text":"CiamCSPOJProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSCOProductView\/title","value":"CiamSCOProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSCOProductView\/fragments","value":[{"kind":"identifier","text":"CiamSCOProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamCTSProductView\/title","value":"CiamCTSProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamCTSProductView\/fragments","value":[{"kind":"identifier","text":"CiamCTSProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamRVHPProductView\/title","value":"CiamRVHPProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamRVHPProductView\/fragments","value":[{"kind":"identifier","text":"CiamRVHPProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSPZProductView\/title","value":"CiamSPZProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSPZProductView\/fragments","value":[{"kind":"identifier","text":"CiamSPZProductView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}