{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ciampersonalinfocardview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ciampersonalinfocardview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/init(coder:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/hSpacing","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/parentDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/selectionView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showAllSelectView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showNeededSelectView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/vSpacing"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/addressSearchButtonTap()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/setupBindings(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showAll()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showDifferent()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"title":"CiamPersonalInfoCardView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)CiamPersonalInfoCardView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/showDifferent()":{"role":"symbol","title":"showDifferent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDifferent"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showDifferent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showDifferent"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/showdifferent()"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/selectionView":{"role":"symbol","title":"selectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/selectionView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/selectionview"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/init(frame:)"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/setupBindings(with:)":{"role":"symbol","title":"setupBindings(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CDMViewModel","preciseIdentifier":"s:10CSHub_Test12CDMViewModelC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Disposable","preciseIdentifier":"s:13ReactiveSwift10DisposableP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/setupBindings(with:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/setupbindings(with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView":{"role":"symbol","title":"CiamPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/showAllSelectView":{"role":"symbol","title":"showAllSelectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAllSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showAllSelectView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/showallselectview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/vSpacing":{"role":"symbol","title":"vSpacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"vSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/vSpacing","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/vspacing"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/showNeededSelectView":{"role":"symbol","title":"showNeededSelectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNeededSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showNeededSelectView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/showneededselectview"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/addressSearchButtonTap()":{"role":"symbol","title":"addressSearchButtonTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressSearchButtonTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/addressSearchButtonTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressSearchButtonTap"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/addresssearchbuttontap()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/showAll()":{"role":"symbol","title":"showAll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAll"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showAll()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showAll"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/showall()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/parentDelegate":{"role":"symbol","title":"parentDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDPersonalInfoViewController","preciseIdentifier":"s:10CSHub_Test31ZenIDPersonalInfoViewControllerC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/parentDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/parentdelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/init(coder:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamPersonalInfoCardView/hSpacing":{"role":"symbol","title":"hSpacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/hSpacing","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciampersonalinfocardview\/hspacing"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CiamPersonalInfoCardView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/addressSearchButtonTap()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/init(coder:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/init(frame:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showAll()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamPersonalInfoCardView\/showDifferent()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamPersonalInfoCardView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1showDifferent()\/title","value":"showDifferent"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1showDifferent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showDifferent"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView\/title","value":"CiamPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"CiamPersonalInfoCardView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1addressSearchButtonTap()\/title","value":"addressSearchButtonTap"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1addressSearchButtonTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addressSearchButtonTap"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1showAll()\/title","value":"showAll"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1showAll()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAll"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamPersonalInfoCardView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}