{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/defaultcshubbiosigndelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/defaultcshubbiosigndelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CShubBioSignDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/init(pencilStatus:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/authorizePublisher","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/completedPublisher"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/authorizeBanker(completion:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/bioSignCompleted(result:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/isApplePencilConnected()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/lockDeviceCurrentOrientation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/logEvent(message:parameters:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/unlockDeviceOrientation()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}],"title":"DefaultCSHubBioSignDelegate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)DefaultCSHubBioSignDelegate","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignDelegate":{"role":"symbol","title":"BioSignDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignDelegate"}],"url":"\/documentation\/cshub_test\/biosigndelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/authorizePublisher":{"role":"symbol","title":"authorizePublisher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizePublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/authorizePublisher","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/authorizepublisher"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/authorizeBanker(completion:)":{"role":"symbol","title":"authorizeBanker(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizeBanker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/authorizeBanker(completion:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/authorizebanker(completion:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/isApplePencilConnected()":{"role":"symbol","title":"isApplePencilConnected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isApplePencilConnected"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/isApplePencilConnected()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/isapplepencilconnected()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/logEvent(message:parameters:)":{"role":"symbol","title":"logEvent(message:parameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : (value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", anonymize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/logEvent(message:parameters:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/logevent(message:parameters:)"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/lockDeviceCurrentOrientation()":{"role":"symbol","title":"lockDeviceCurrentOrientation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockDeviceCurrentOrientation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/lockDeviceCurrentOrientation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/lockdevicecurrentorientation()"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/bioSignCompleted(result:)":{"role":"symbol","title":"bioSignCompleted(result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bioSignCompleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/bioSignCompleted(result:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/biosigncompleted(result:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CShubBioSignDelegate":{"role":"symbol","title":"CShubBioSignDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CShubBioSignDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CShubBioSignDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CShubBioSignDelegate"}],"url":"\/documentation\/cshub_test\/cshubbiosigndelegate"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/completedPublisher":{"role":"symbol","title":"completedPublisher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completedPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/completedPublisher","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/completedpublisher"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate":{"role":"symbol","title":"DefaultCSHubBioSignDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}],"url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/init(pencilStatus:)":{"role":"symbol","title":"init(pencilStatus:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pencilStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApplePencilStatus","preciseIdentifier":"s:10CSHub_Test17ApplePencilStatusP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/init(pencilStatus:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/init(pencilstatus:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultCSHubBioSignDelegate/unlockDeviceOrientation()":{"role":"symbol","title":"unlockDeviceOrientation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlockDeviceOrientation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultCSHubBioSignDelegate\/unlockDeviceOrientation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/defaultcshubbiosigndelegate\/unlockdeviceorientation()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DefaultCSHubBioSignDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultCSHubBioSignDelegate\/title","value":"DefaultCSHubBioSignDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultCSHubBioSignDelegate\/fragments","value":[{"kind":"identifier","text":"DefaultCSHubBioSignDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}