{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Delegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/@M@Alamofire@objc(cs)SessionDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionDataDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionDownloadDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/init(ssl:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/urlSession(_:task:didReceive:completionHandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Delegate"}],"title":"Delegate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)Delegate","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"Delegate"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/@M@Alamofire@objc(cs)SessionDelegate":{"type":"unresolvable","title":"_TtC9Alamofire15SessionDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/@M@Alamofire@objc(cs)SessionDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)NSURLSessionDataDelegate":{"type":"unresolvable","title":"Foundation.URLSessionDataDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionDataDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)NSURLSessionDownloadDelegate":{"type":"unresolvable","title":"Foundation.URLSessionDownloadDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionDownloadDelegate"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Delegate/urlSession(_:task:didReceive:completionHandler:)":{"role":"symbol","title":"urlSession(_:task:didReceive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/urlSession(_:task:didReceive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}],"url":"\/documentation\/cshub_test\/delegate\/urlsession(_:task:didreceive:completionhandler:)"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/objc(pl)NSURLSessionTaskDelegate":{"type":"unresolvable","title":"Foundation.URLSessionTaskDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionTaskDelegate"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Delegate/init(ssl:)":{"role":"symbol","title":"init(ssl:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ssl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SSLPinningManager","preciseIdentifier":"s:10CSHub_Test17SSLPinningManagerP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/init(ssl:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/delegate\/init(ssl:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Delegate":{"role":"symbol","title":"Delegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Delegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Delegate"}],"url":"\/documentation\/cshub_test\/delegate"},"doc://cz.csas.app.cshub.test/objc(pl)NSURLSessionDelegate":{"type":"unresolvable","title":"Foundation.URLSessionDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSURLSessionDelegate"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Delegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Delegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/urlSession(_:task:didReceive:completionHandler:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/@M@Alamofire@objc(cs)SessionDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Delegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"SessionDelegate","preciseIdentifier":"c:@M@Alamofire@objc(cs)SessionDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate~1urlSession(_:task:didReceive:completionHandler:)\/title","value":"URLSession:task:didReceiveChallenge:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate~1urlSession(_:task:didReceive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate\/title","value":"Delegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate\/fragments","value":[{"kind":"identifier","text":"Delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}