{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/device_digitizer_coefficient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/device_digitizer_coefficient"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DEVICE_DIGITIZER_COEFFICIENT","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"DEVICE_DIGITIZER_COEFFICIENT","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@DEVICE_DIGITIZER_COEFFICIENT","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DEVICE_DIGITIZER_COEFFICIENT":{"role":"symbol","title":"DEVICE_DIGITIZER_COEFFICIENT","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DEVICE_DIGITIZER_COEFFICIENT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"}],"url":"\/documentation\/cshub_test\/device_digitizer_coefficient"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"DEVICE_DIGITIZER_COEFFICIENT"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DEVICE_DIGITIZER_COEFFICIENT\/title","value":"DEVICE_DIGITIZER_COEFFICIENT"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DEVICE_DIGITIZER_COEFFICIENT\/fragments","value":[{"kind":"identifier","text":"DEVICE_DIGITIZER_COEFFICIENT"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}