{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentListButtonView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/documentlistbuttonview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/documentlistbuttonview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/init(ofType:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/iconImageView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/lastStyle","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/titleLabel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/verticalBar"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/setStyle(style:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/setTitle(title:andStyle:)"]},{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/resetWidth"]},{"title":"Enumerations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/ButtonType","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/Style"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentListButtonView"}],"title":"DocumentListButtonView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)DocumentListButtonView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentListButtonView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/iconImageView":{"role":"symbol","title":"iconImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/iconImageView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/iconimageview"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/documentlistbuttonview\/initwithframe:"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/Style":{"role":"symbol","title":"DocumentListButtonView.Style","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/Style","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/cshub_test\/documentlistbuttonview\/style"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/documentlistbuttonview\/initwithcoder:"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/lastStyle":{"role":"symbol","title":"lastStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:10CSHub_Test22DocumentListButtonViewC5StyleO"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/lastStyle","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/laststyle"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/titlelabel"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/resetWidth":{"role":"symbol","title":"resetWidth","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/resetWidth","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/resetwidth"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView":{"role":"symbol","title":"DocumentListButtonView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentListButtonView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentListButtonView"}],"url":"\/documentation\/cshub_test\/documentlistbuttonview"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/setStyle(style:)":{"role":"symbol","title":"setStyle(style:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:10CSHub_Test22DocumentListButtonViewC5StyleO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/setStyle(style:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/setstyle(style:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/verticalBar":{"role":"symbol","title":"verticalBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/verticalBar","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/verticalbar"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/setTitle(title:andStyle:)":{"role":"symbol","title":"setTitle(title:andStyle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTitle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:10CSHub_Test22DocumentListButtonViewC5StyleO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/setTitle(title:andStyle:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/settitle(title:andstyle:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/init(ofType:)":{"role":"symbol","title":"init(ofType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ButtonType","preciseIdentifier":"s:10CSHub_Test22DocumentListButtonViewC0E4TypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/init(ofType:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/documentlistbuttonview\/init(oftype:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentListButtonView/ButtonType":{"role":"symbol","title":"DocumentListButtonView.ButtonType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonType"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/ButtonType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ButtonType"}],"url":"\/documentation\/cshub_test\/documentlistbuttonview\/buttontype"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DocumentListButtonView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DocumentListButtonView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DocumentListButtonView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/initWithCoder:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentListButtonView\/initWithFrame:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentListButtonView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentListButtonView\/title","value":"DocumentListButtonView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentListButtonView\/fragments","value":[{"kind":"identifier","text":"DocumentListButtonView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}