{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DrawingDeviceType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/drawingdevicetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/drawingdevicetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/SY","doc:\/\/cz.csas.app.cshub.test\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/disabled","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeApplePencil","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeWacom"]},{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/Equatable-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DrawingDeviceType"}],"title":"DrawingDeviceType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@DrawingDeviceType","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceType"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/typeWacom":{"role":"symbol","title":"DrawingDeviceType.typeWacom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWacom"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeWacom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}],"url":"\/documentation\/cshub_test\/drawingdevicetype\/typewacom"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/drawingdevicetype\/init(rawvalue:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/disabled":{"role":"symbol","title":"DrawingDeviceType.disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/disabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceDisabled"}],"url":"\/documentation\/cshub_test\/drawingdevicetype\/disabled"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/drawingdevicetype\/equatable-implementations"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType":{"role":"symbol","title":"DrawingDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DrawingDeviceType"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceType"}],"url":"\/documentation\/cshub_test\/drawingdevicetype"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/typeApplePencil":{"role":"symbol","title":"DrawingDeviceType.typeApplePencil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeApplePencil"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeApplePencil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DrawingDeviceTypeApplePencil"}],"url":"\/documentation\/cshub_test\/drawingdevicetype\/typeapplepencil"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DrawingDeviceType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/drawingdevicetype\/rawrepresentable-implementations"},"doc://cz.csas.app.cshub.test/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DrawingDeviceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DrawingDeviceType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/disabled","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeApplePencil","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DrawingDeviceType\/typeWacom"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DrawingDeviceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1typeWacom\/title","value":"DrawingDeviceTypeWacom"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1typeWacom\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceTypeWacom"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1disabled\/title","value":"DrawingDeviceDisabled"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1disabled\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType\/title","value":"DrawingDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceType"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1typeApplePencil\/title","value":"DrawingDeviceTypeApplePencil"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DrawingDeviceType~1typeApplePencil\/fragments","value":[{"kind":"identifier","text":"DrawingDeviceTypeApplePencil"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}