{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/faqviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/faqviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSExtensionRequestHandling","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIContentContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIStateRestoring","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDataSource","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/init(for:endStep:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/expandedRows","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/items","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/steps","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/didReceiveMemoryWarning()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/handleBottomBorder(for:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/handleTopBorderForCellBelow(cell:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/setStyle()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/Presentable-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/Stepper-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/UITableViewDataSource-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"title":"FaqViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)FaqViewController","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"FaqViewController"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/init(for:endStep:)":{"role":"symbol","title":"init(for:endStep:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqSetupStyle","preciseIdentifier":"s:10CSHub_Test13FaqSetupStyleO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endStep"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Step","preciseIdentifier":"s:10CSHub_Test4StepP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"convenience initializer handling init for multiple setups"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/init(for:endStep:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/init(for:endstep:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/tableView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/tableview"},"doc://cz.csas.app.cshub.test/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIStateRestoring"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIContentContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/uitableviewdelegate-implementations"},"doc://cz.csas.app.cshub.test/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSExtensionRequestHandling"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/uitableviewdatasource-implementations"},"doc://cz.csas.app.cshub.test/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDataSource"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/steps":{"role":"symbol","title":"steps","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"steps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Step","preciseIdentifier":"s:10CSHub_Test4StepP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/steps","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/steps"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Presentable":{"role":"symbol","title":"Presentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presentable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Presentable"}],"url":"\/documentation\/cshub_test\/presentable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/handleTopBorderForCellBelow(cell:)":{"role":"symbol","title":"handleTopBorderForCellBelow(cell:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleTopBorderForCellBelow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqCell","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqCell"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/handleTopBorderForCellBelow(cell:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/handletopborderforcellbelow(cell:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/expandedRows":{"role":"symbol","title":"expandedRows","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expandedRows"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/expandedRows","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/expandedrows"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper":{"role":"symbol","title":"Stepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stepper"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Stepper"}],"url":"\/documentation\/cshub_test\/stepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/Presentable-Implementations":{"role":"collectionGroup","title":"Presentable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/Presentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/presentable-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/Stepper-Implementations":{"role":"collectionGroup","title":"Stepper Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/Stepper-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/stepper-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/setStyle()":{"role":"symbol","title":"setStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStyle"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/setStyle()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/setstyle()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/cshub_test\/faqviewcontroller\/initwithnibname:bundle:"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ViewControllerStyleable":{"role":"symbol","title":"ViewControllerStyleable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewControllerStyleable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewControllerStyleable"}],"url":"\/documentation\/cshub_test\/viewcontrollerstyleable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/handleBottomBorder(for:)":{"role":"symbol","title":"handleBottomBorder(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleBottomBorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqCell","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqCell"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/handleBottomBorder(for:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/handlebottomborder(for:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/faqviewcontroller\/initwithcoder:"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/didReceiveMemoryWarning()":{"role":"symbol","title":"didReceiveMemoryWarning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveMemoryWarning"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/didReceiveMemoryWarning()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveMemoryWarning"}],"url":"\/documentation\/cshub_test\/faqviewcontroller\/didreceivememorywarning()"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController":{"role":"symbol","title":"FaqViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqViewController"}],"url":"\/documentation\/cshub_test\/faqviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/items":{"role":"symbol","title":"items","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"OldFaq","preciseIdentifier":"s:10CSHub_Test6OldFaqV"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/items","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqviewcontroller\/items"},"doc://cz.csas.app.cshub.test/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIViewController"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/cshub_test\/faqviewcontroller\/viewdidload()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FaqViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FaqViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FaqViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/didReceiveMemoryWarning()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/initWithCoder:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/initWithNibName:bundle:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/UITableViewDataSource-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController~1didReceiveMemoryWarning()\/title","value":"didReceiveMemoryWarning"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController~1didReceiveMemoryWarning()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveMemoryWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/title","value":"FaqViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/fragments","value":[{"kind":"identifier","text":"FaqViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}