{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"g_pPadRemote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote","text":"IOS_PadRemote"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/g_ppadremote"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/g_ppadremote"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/g_pPadRemote","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"g_pPadRemote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote"},{"kind":"text","text":"!"}],"title":"g_pPadRemote","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@g_pPadRemote","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"g_pPadRemote"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemote":{"role":"symbol","title":"IOS_PadRemote","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemote"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemote"}],"url":"\/documentation\/cshub_test\/ios_padremote"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/g_pPadRemote":{"role":"symbol","title":"g_pPadRemote","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"g_pPadRemote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/g_pPadRemote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"g_pPadRemote"}],"url":"\/documentation\/cshub_test\/g_ppadremote"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"g_pPadRemote"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"g_pPadRemote"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemote","preciseIdentifier":"c:objc(cs)IOS_PadRemote","text":"IOS_PadRemote"},{"kind":"text","text":" * "},{"kind":"identifier","text":"g_pPadRemote"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemote\/title","value":"IOS_PadRemote"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemote\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemote"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1g_pPadRemote\/title","value":"g_pPadRemote"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1g_pPadRemote\/fragments","value":[{"kind":"identifier","text":"g_pPadRemote"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}