{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ios_padremotedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ios_padremotedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/deviceId()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/envelopeCertificateData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/getUsername()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/handle(toServer:internalSignatureData:signatureRenderData:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/isRetryConfirmEnabled()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/padRemoteController()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/pdfData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/removeOverlayDueCancellation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/removeOverlayDueConfirmation()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"title":"IOS_PadRemoteDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)IOS_PadRemoteDelegate","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/removeOverlayDueConfirmation()":{"navigatorTitle":[{"kind":"identifier","text":"removeOverlayDueConfirmation"}],"role":"symbol","title":"removeOverlayDueConfirmation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeOverlayDueConfirmation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/removeOverlayDueConfirmation()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/removeoverlaydueconfirmation()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/deviceId()":{"navigatorTitle":[{"kind":"identifier","text":"deviceId"}],"role":"symbol","title":"deviceId()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/deviceId()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/deviceid()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/pdfData()":{"role":"symbol","title":"pdfData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/pdfData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pdfData"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate\/pdfdata()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/isRetryConfirmEnabled()":{"navigatorTitle":[{"kind":"identifier","text":"isRetryConfirmEnabled"}],"role":"symbol","title":"isRetryConfirmEnabled()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRetryConfirmEnabled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/isRetryConfirmEnabled()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/isretryconfirmenabled()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate":{"role":"symbol","title":"IOS_PadRemoteDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}],"url":"\/documentation\/cshub_test\/ios_padremotedelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/padRemoteController()":{"navigatorTitle":[{"kind":"identifier","text":"padRemoteController"}],"role":"symbol","title":"padRemoteController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"padRemoteController"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/padRemoteController()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/padremotecontroller()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignatureOverlayViewController":{"role":"symbol","title":"SignatureOverlayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignatureOverlayViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignatureOverlayViewController"}],"url":"\/documentation\/cshub_test\/signatureoverlayviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/removeOverlayDueCancellation()":{"navigatorTitle":[{"kind":"identifier","text":"removeOverlayDueCancellation"}],"role":"symbol","title":"removeOverlayDueCancellation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeOverlayDueCancellation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/removeOverlayDueCancellation()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/removeoverlayduecancellation()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/getUsername()":{"navigatorTitle":[{"kind":"identifier","text":"getUsername"}],"role":"symbol","title":"getUsername()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUsername"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/getUsername()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/getusername()"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController":{"role":"symbol","title":"BioSignatureOverlayController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignatureOverlayController"}],"url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/envelopeCertificateData()":{"navigatorTitle":[{"kind":"identifier","text":"envelopeCertificateData"}],"role":"symbol","title":"envelopeCertificateData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeCertificateData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/envelopeCertificateData()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/envelopecertificatedata()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_PadRemoteDelegate/handle(toServer:internalSignatureData:signatureRenderData:)":{"navigatorTitle":[{"kind":"identifier","text":"handleToServer:internalSignatureData:signatureRenderData:"}],"role":"symbol","title":"handle(toServer:internalSignatureData:signatureRenderData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toServer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"internalSignatureData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"signatureRenderData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/handle(toServer:internalSignatureData:signatureRenderData:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/ios_padremotedelegate\/handle(toserver:internalsignaturedata:signaturerenderdata:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IOS_PadRemoteDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/deviceId()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/envelopeCertificateData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/getUsername()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/handle(toServer:internalSignatureData:signatureRenderData:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/isRetryConfirmEnabled()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/padRemoteController()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/pdfData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/removeOverlayDueCancellation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_PadRemoteDelegate\/removeOverlayDueConfirmation()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_PadRemoteDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1removeOverlayDueConfirmation()\/title","value":"removeOverlayDueConfirmation"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1removeOverlayDueConfirmation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeOverlayDueConfirmation"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1deviceId()\/title","value":"deviceId"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1deviceId()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deviceId"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1pdfData()\/title","value":"pdfData"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1pdfData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pdfData"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1isRetryConfirmEnabled()\/title","value":"isRetryConfirmEnabled"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1isRetryConfirmEnabled()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isRetryConfirmEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/title","value":"IOS_PadRemoteDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate\/fragments","value":[{"kind":"identifier","text":"IOS_PadRemoteDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1padRemoteController()\/title","value":"padRemoteController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1padRemoteController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"padRemoteController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1removeOverlayDueCancellation()\/title","value":"removeOverlayDueCancellation"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1removeOverlayDueCancellation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeOverlayDueCancellation"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1getUsername()\/title","value":"getUsername"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1getUsername()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUsername"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1envelopeCertificateData()\/title","value":"envelopeCertificateData"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1envelopeCertificateData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"envelopeCertificateData"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1handle(toServer:internalSignatureData:signatureRenderData:)\/title","value":"handleToServer:internalSignatureData:signatureRenderData:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_PadRemoteDelegate~1handle(toServer:internalSignatureData:signatureRenderData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleToServer:internalSignatureData:signatureRenderData:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}