{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_Client"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ios_client"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ios_client"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/cancelSignature(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/captureSignature()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/cleanParams()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/clearBackground()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/confirmSignature(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/confirmSignatureSignpad(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/drawBackground(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/failedStatus(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/finalize()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/finalized()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/jumpBack()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/onTick(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/restart()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setIdentityRef(_:withBioSignDelegate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startLoop()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startSigning()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/stopTimer()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_Client"}],"title":"IOS_Client","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)IOS_Client","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"IOS_Client"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/bioSignDelegate":{"role":"symbol","title":"bioSignDelegate","fragments":[{"kind":"identifier","text":"bioSignDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/bioSignDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ios_client\/biosigndelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/confirmSignatureSignpad(_:)":{"role":"symbol","title":"confirmSignatureSignpad(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSignatureSignpad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">!) -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/confirmSignatureSignpad(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmSignatureSignpad:"}],"url":"\/documentation\/cshub_test\/ios_client\/confirmsignaturesignpad(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)":{"role":"symbol","title":"init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"wholeViewFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"}],"url":"\/documentation\/cshub_test\/ios_client\/init(wholeviewframe:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:anddelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/startSigning()":{"role":"symbol","title":"startSigning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSigning"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startSigning()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSigning"}],"url":"\/documentation\/cshub_test\/ios_client\/startsigning()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/failedStatus(_:)":{"role":"symbol","title":"failedStatus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedStatus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/failedStatus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedStatus:"}],"url":"\/documentation\/cshub_test\/ios_client\/failedstatus(_:)"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/stopTimer()":{"role":"symbol","title":"stopTimer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimer"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/stopTimer()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopTimer"}],"url":"\/documentation\/cshub_test\/ios_client\/stoptimer()"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/jumpBack()":{"role":"symbol","title":"jumpBack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jumpBack"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/jumpBack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jumpBack"}],"url":"\/documentation\/cshub_test\/ios_client\/jumpback()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/setIdentityRef(_:withBioSignDelegate:)":{"role":"symbol","title":"setIdentityRef(_:withBioSignDelegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentityRef"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withBioSignDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setIdentityRef(_:withBioSignDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setIdentityRef:withBioSignDelegate:"}],"url":"\/documentation\/cshub_test\/ios_client\/setidentityref(_:withbiosigndelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/clearBackground()":{"role":"symbol","title":"clearBackground()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearBackground"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/clearBackground()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearBackground"}],"url":"\/documentation\/cshub_test\/ios_client\/clearbackground()"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client":{"role":"symbol","title":"IOS_Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_Client"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IOS_Client"}],"url":"\/documentation\/cshub_test\/ios_client"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/restart()":{"role":"symbol","title":"restart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/restart()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restartClient"}],"url":"\/documentation\/cshub_test\/ios_client\/restart()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/confirmSignature(_:)":{"role":"symbol","title":"confirmSignature(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSignature"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/confirmSignature(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmSignature:"}],"url":"\/documentation\/cshub_test\/ios_client\/confirmsignature(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/identityReference":{"role":"symbol","title":"identityReference","fragments":[{"kind":"identifier","text":"identityReference"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/identityReference","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ios_client\/identityreference"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/startLoop()":{"role":"symbol","title":"startLoop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLoop"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startLoop()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLoop"}],"url":"\/documentation\/cshub_test\/ios_client\/startloop()"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/drawBackground(_:)":{"role":"symbol","title":"drawBackground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawBackground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/drawBackground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawBackground:"}],"url":"\/documentation\/cshub_test\/ios_client\/drawbackground(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/m_pSignThread":{"role":"symbol","title":"m_pSignThread","fragments":[{"kind":"identifier","text":"m_pSignThread"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/m_pSignThread","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ios_client\/m_psignthread"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)":{"role":"symbol","title":"setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setViewFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withDpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signingFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}],"url":"\/documentation\/cshub_test\/ios_client\/setviewframe(_:withdpi:signingframe:confirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOS_PadRemoteDelegate","preciseIdentifier":"c:objc(pl)IOS_PadRemoteDelegate"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/cshub_test\/ios_client\/delegate"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/cancelSignature(_:)":{"role":"symbol","title":"cancelSignature(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelSignature"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/cancelSignature(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelSignature:"}],"url":"\/documentation\/cshub_test\/ios_client\/cancelsignature(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/finalize()":{"role":"symbol","title":"finalize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalize"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/finalize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalize"}],"url":"\/documentation\/cshub_test\/ios_client\/finalize()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/finalized()":{"role":"symbol","title":"finalized()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalized"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/finalized()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalized"}],"url":"\/documentation\/cshub_test\/ios_client\/finalized()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/captureSignature()":{"role":"symbol","title":"captureSignature()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureSignature"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/captureSignature()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureSignature"}],"url":"\/documentation\/cshub_test\/ios_client\/capturesignature()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/onTick(_:)":{"role":"symbol","title":"onTick(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Timer","preciseIdentifier":"c:objc(cs)NSTimer"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/onTick(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTick:"}],"url":"\/documentation\/cshub_test\/ios_client\/ontick(_:)"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)":{"role":"symbol","title":"startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSigning"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inCustomFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withConfirmSignatureButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andCancelSigningButtonFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startSigningInCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}],"url":"\/documentation\/cshub_test\/ios_client\/startsigning(incustomframe:withconfirmsignaturebuttonframe:clearbuttonframe:andcancelsigningbuttonframe:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IOS_Client/cleanParams()":{"role":"symbol","title":"cleanParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanParams"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/cleanParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanParams"}],"url":"\/documentation\/cshub_test\/ios_client\/cleanparams()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IOS_Client"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IOS_Client"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IOS_Client"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Variables","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/bioSignDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/identityReference","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/m_pSignThread"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/cancelSignature(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/captureSignature()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/cleanParams()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/clearBackground()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/confirmSignature(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/confirmSignatureSignpad(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/drawBackground(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/failedStatus(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/finalize()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/finalized()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/jumpBack()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/onTick(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/restart()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setIdentityRef(_:withBioSignDelegate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startLoop()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startSigning()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IOS_Client\/stopTimer()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IOS_Client"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1confirmSignatureSignpad(_:)\/title","value":"confirmSignatureSignpad:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1confirmSignatureSignpad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmSignatureSignpad:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)\/title","value":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1init(wholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWholeViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:andDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1startSigning()\/title","value":"startSigning"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1startSigning()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startSigning"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1failedStatus(_:)\/title","value":"failedStatus:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1failedStatus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"failedStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1stopTimer()\/title","value":"stopTimer"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1stopTimer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopTimer"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1jumpBack()\/title","value":"jumpBack"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1jumpBack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jumpBack"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1setIdentityRef(_:withBioSignDelegate:)\/title","value":"setIdentityRef:withBioSignDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1setIdentityRef(_:withBioSignDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIdentityRef:withBioSignDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1clearBackground()\/title","value":"clearBackground"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1clearBackground()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client\/title","value":"IOS_Client"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client\/fragments","value":[{"kind":"identifier","text":"IOS_Client"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1restart()\/title","value":"restartClient"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1restart()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restartClient"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1confirmSignature(_:)\/title","value":"confirmSignature:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1confirmSignature(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmSignature:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1startLoop()\/title","value":"startLoop"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1startLoop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLoop"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1drawBackground(_:)\/title","value":"drawBackground:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1drawBackground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawBackground:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)\/title","value":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1setViewFrame(_:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setViewFrame:withDpi:signingFrame:confirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1cancelSignature(_:)\/title","value":"cancelSignature:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1cancelSignature(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelSignature:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1finalize()\/title","value":"finalize"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1finalize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finalize"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1finalized()\/title","value":"finalized"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1finalized()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finalized"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1captureSignature()\/title","value":"captureSignature"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1captureSignature()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureSignature"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1onTick(_:)\/title","value":"onTick:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1onTick(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTick:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)\/title","value":"startSigningInCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1startSigning(inCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startSigningInCustomFrame:withConfirmSignatureButtonFrame:clearButtonFrame:andCancelSigningButtonFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1cleanParams()\/title","value":"cleanParams"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IOS_Client~1cleanParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}