{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPKIMobileManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ipkimobilemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ipkimobilemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addPEMWrapping(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addPolicyParam(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addRecipientCert(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/base64Decode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/base64Encode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/changeKeyStoragePassword(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/clearPolicyParams()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/createCertRequest()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/decryptData(_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/decryptDataPBE(_:_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/derEncoder(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/developeDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/encryptDataPBE(_:_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/envelopeDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getDeviceFingerprint()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getErrorInfo()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getFromKeyStorage(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getPKCS12Certificates(_:_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getVersion()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/initializeKeyStorage(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/loginIOS(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/loginPKCS12(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/logout()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/prepareCryptData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/put(inKeyStorage:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/remove(fromKeyStorage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/removeAllFromKeyStorage()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/resetRecipients()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/saveLogsToZIP()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setCustomSignDataHandler(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setDevCert()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setPKCS12Password(_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/signData(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/signDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/startInitialCertGenProcess(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/switchUser(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/toCertInfo(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/updateCert(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPKIMobileManager"}],"title":"IPKIMobileManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)IPKIMobileManager","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"IPKIMobileManager"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/loginPKCS12(_:_:_:)":{"role":"symbol","title":"loginPKCS12(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginPKCS12"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Login to the PKCS#12 crypto device, using the key storage identifier and a combined"},{"type":"text","text":" "},{"type":"text","text":"client and server password."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/loginPKCS12(_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginPKCS12:::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/loginpkcs12(_:_:_:)"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/developeDataBase64(_:)":{"role":"symbol","title":"developeDataBase64(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"developeDataBase64"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"develope (i.e. de-envelope) data - decrypt PKCS#7 enveloped message (base64 in on input and output)."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/developeDataBase64(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"developeDataBase64:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/developedatabase64(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/toCertInfo(_:)":{"role":"symbol","title":"toCertInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toCertInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Parse the certificate and return the certificate properties."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/toCertInfo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toCertInfo:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/tocertinfo(_:)"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/removeAllFromKeyStorage()":{"role":"symbol","title":"removeAllFromKeyStorage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllFromKeyStorage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Remove all values from the mobile keystorage."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/removeAllFromKeyStorage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeAllFromKeyStorage"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/removeallfromkeystorage()"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/changeKeyStoragePassword(_:_:_:)":{"role":"symbol","title":"changeKeyStoragePassword(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeKeyStoragePassword"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Change the key storage password for the mobile device."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/changeKeyStoragePassword(_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeKeyStoragePassword:::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/changekeystoragepassword(_:_:_:)"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/clearPolicyParams()":{"role":"symbol","title":"clearPolicyParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearPolicyParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Clear policy parameters - call before the new certificate creation process."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/clearPolicyParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearPolicyParams"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/clearpolicyparams()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/switchUser(_:)":{"role":"symbol","title":"switchUser(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Globally switch user profile."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/switchUser(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchUser:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/switchuser(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/getVersion()":{"role":"symbol","title":"getVersion()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVersion"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"get version of the library."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getVersion()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVersion"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/getversion()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/initializeKeyStorage(_:_:)":{"role":"symbol","title":"initializeKeyStorage(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeKeyStorage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Initialize the key storage for the mobile device."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/initializeKeyStorage(_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeKeyStorage::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/initializekeystorage(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/decryptData(_:_:_:_:)":{"role":"symbol","title":"decryptData(_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Decrypt data, like server password."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/decryptData(_:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decryptData::::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/decryptdata(_:_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/addPEMWrapping(_:)":{"role":"symbol","title":"addPEMWrapping(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPEMWrapping"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Add PEM wrapping to a String value."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addPEMWrapping(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPEMWrapping:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/addpemwrapping(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/signDataBase64(_:)":{"role":"symbol","title":"signDataBase64(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signDataBase64"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Sign the data"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/signDataBase64(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signDataBase64:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/signdatabase64(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/decryptDataPBE(_:_:_:_:_:)":{"role":"symbol","title":"decryptDataPBE(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptDataPBE"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"decrypt data PBE(Password-Based Encryption)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/decryptDataPBE(_:_:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decryptDataPBE:::::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/decryptdatapbe(_:_:_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/startInitialCertGenProcess(_:_:_:)":{"role":"symbol","title":"startInitialCertGenProcess(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startInitialCertGenProcess"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Note: invoke only in INITIAL, not PROLONG certificate generation."},{"type":"text","text":" "},{"type":"text","text":"This function initializes the PKI API’s internal data state before the initial certificate generation."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/startInitialCertGenProcess(_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startInitialCertGenProcess:::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/startinitialcertgenprocess(_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/setDevCert()":{"role":"symbol","title":"setDevCert()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDevCert"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Helper function for dev purposes"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setDevCert()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDevCert"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/setdevcert()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/base64Encode(_:)":{"role":"symbol","title":"base64Encode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"base64Encode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Base64Encode function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/base64Encode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"base64Encode:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/base64encode(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/getFromKeyStorage(_:)":{"role":"symbol","title":"getFromKeyStorage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFromKeyStorage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Get a value from the mobile keystorage."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getFromKeyStorage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFromKeyStorage:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/getfromkeystorage(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/envelopeDataBase64(_:)":{"role":"symbol","title":"envelopeDataBase64(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeDataBase64"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"envelope data - generate PKCS#7 enveloped message (base64 in on input and output)."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/envelopeDataBase64(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"envelopeDataBase64:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/envelopedatabase64(_:)"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/getPKCS12Certificates(_:_:_:_:_:)":{"role":"symbol","title":"getPKCS12Certificates(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPKCS12Certificates"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"List certificates in the PKCS#12 in the key storage."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getPKCS12Certificates(_:_:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPKCS12Certificates:::::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/getpkcs12certificates(_:_:_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/derEncoder(_:)":{"role":"symbol","title":"derEncoder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"derEncoder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Create DER Sequence from input data"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/derEncoder(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"derEncoder:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/derencoder(_:)"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/signData(_:_:)":{"role":"symbol","title":"signData(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Sign the data using the key that chosen in loginPKCS12."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/signData(_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signData::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/signdata(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/getErrorInfo()":{"role":"symbol","title":"getErrorInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getErrorInfo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Retrieve error information in a JSON object, in case there is an error."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getErrorInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getErrorInfo"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/geterrorinfo()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/setPKCS12Password(_:_:_:_:)":{"role":"symbol","title":"setPKCS12Password(_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPKCS12Password"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the PKCS#12 file password for SIGNCERT and NEWCERT."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setPKCS12Password(_:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPKCS12Password::::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/setpkcs12password(_:_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/base64Decode(_:)":{"role":"symbol","title":"base64Decode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"base64Decode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Base64Decode function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/base64Decode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"base64Decode:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/base64decode(_:)"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/addPolicyParam(_:_:)":{"role":"symbol","title":"addPolicyParam(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPolicyParam"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Add policy parameter - values like certificate dname, extension, but also keyStorageID."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addPolicyParam(_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPolicyParam::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/addpolicyparam(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/encryptDataPBE(_:_:_:_:_:)":{"role":"symbol","title":"encryptDataPBE(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptDataPBE"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"encrypt data PBE(Password-Based Encryption)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/encryptDataPBE(_:_:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encryptDataPBE:::::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/encryptdatapbe(_:_:_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/createCertRequest()":{"role":"symbol","title":"createCertRequest()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCertRequest"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Generate private\/public key, create the PKCS#10 certificate request and a self-signed certificate"},{"type":"text","text":" "},{"type":"text","text":"in the key storage"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/createCertRequest()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCertRequest"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/createcertrequest()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/prepareCryptData()":{"role":"symbol","title":"prepareCryptData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCryptData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Prepare crypto data like RSA keypair for later certificate request generation."},{"type":"text","text":" "},{"type":"text","text":"This function opens a new background thread with a low priority and finishes immediately,"},{"type":"text","text":" "},{"type":"text","text":"the mobile application can continue its operation."},{"type":"text","text":" "},{"type":"text","text":"This function call should be preceded at least by a call specifying the key size - i.e."},{"type":"text","text":" "},{"type":"text","text":"clearPolicyParams"},{"type":"text","text":" and "},{"type":"text","text":"addPolicyParam(“keySize”, 2048)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/prepareCryptData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareCryptData"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/preparecryptdata()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/updateCert(_:)":{"role":"symbol","title":"updateCert(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Import\/update certificate in the key storage (self-identifying the key storage ID)."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/updateCert(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateCert:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/updatecert(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/remove(fromKeyStorage:)":{"role":"symbol","title":"remove(fromKeyStorage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromKeyStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Remove a value from the mobile keystorage."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/remove(fromKeyStorage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFromKeyStorage:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/remove(fromkeystorage:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager":{"role":"symbol","title":"IPKIMobileManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPKIMobileManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IPKIMobileManager"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/addRecipientCert(_:)":{"role":"symbol","title":"addRecipientCert(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRecipientCert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Add the recipient certificate encoded in Base64, to be used in PKCS#7 enveloped message."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addRecipientCert(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRecipientCert:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/addrecipientcert(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/setCustomSignDataHandler(_:_:)":{"role":"symbol","title":"setCustomSignDataHandler(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomSignDataHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CustomSignDataHandler","preciseIdentifier":"c:IPKIMobileManager.h@T@CustomSignDataHandler"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the handler to sign function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setCustomSignDataHandler(_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCustomSignDataHandler::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/setcustomsigndatahandler(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/logout()":{"role":"symbol","title":"logout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Logout from the device keystore."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/logout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logout"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/logout()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/loginIOS(_:)":{"role":"symbol","title":"loginIOS(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginIOS"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Create the iOS Device and set the certificate"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/loginIOS(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginIOS:"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/loginios(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/saveLogsToZIP()":{"role":"symbol","title":"saveLogsToZIP()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveLogsToZIP"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Save log files to a single ZIP."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/saveLogsToZIP()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"saveLogsToZIP"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/savelogstozip()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/put(inKeyStorage:_:)":{"role":"symbol","title":"put(inKeyStorage:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"put"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inKeyStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Put a value into the mobile keystorage."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/put(inKeyStorage:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"putInKeyStorage::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/put(inkeystorage:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/getDeviceFingerprint()":{"role":"symbol","title":"getDeviceFingerprint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeviceFingerprint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Get the device fingerprint."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getDeviceFingerprint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDeviceFingerprint"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/getdevicefingerprint()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/resetRecipients()":{"role":"symbol","title":"resetRecipients()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetRecipients"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Reset certificate list used for encryption."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/resetRecipients()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetRecipients"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/resetrecipients()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IPKIMobileManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IPKIMobileManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IPKIMobileManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addPEMWrapping(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addPolicyParam(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/addRecipientCert(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/base64Decode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/base64Encode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/changeKeyStoragePassword(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/clearPolicyParams()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/createCertRequest()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/decryptData(_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/decryptDataPBE(_:_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/derEncoder(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/developeDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/encryptDataPBE(_:_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/envelopeDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getDeviceFingerprint()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getErrorInfo()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getFromKeyStorage(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getPKCS12Certificates(_:_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/getVersion()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/initializeKeyStorage(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/loginIOS(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/loginPKCS12(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/logout()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/prepareCryptData()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/put(inKeyStorage:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/remove(fromKeyStorage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/removeAllFromKeyStorage()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/resetRecipients()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/saveLogsToZIP()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setCustomSignDataHandler(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setDevCert()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setPKCS12Password(_:_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/signData(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/signDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/startInitialCertGenProcess(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/switchUser(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/toCertInfo(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/updateCert(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPKIMobileManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1loginPKCS12(_:_:_:)\/title","value":"loginPKCS12:::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1loginPKCS12(_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginPKCS12:::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1developeDataBase64(_:)\/title","value":"developeDataBase64:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1developeDataBase64(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"developeDataBase64:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1toCertInfo(_:)\/title","value":"toCertInfo:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1toCertInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toCertInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1removeAllFromKeyStorage()\/title","value":"removeAllFromKeyStorage"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1removeAllFromKeyStorage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllFromKeyStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1changeKeyStoragePassword(_:_:_:)\/title","value":"changeKeyStoragePassword:::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1changeKeyStoragePassword(_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeKeyStoragePassword:::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1clearPolicyParams()\/title","value":"clearPolicyParams"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1clearPolicyParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearPolicyParams"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1switchUser(_:)\/title","value":"switchUser:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1switchUser(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getVersion()\/title","value":"getVersion"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getVersion()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1initializeKeyStorage(_:_:)\/title","value":"initializeKeyStorage::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1initializeKeyStorage(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeKeyStorage::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1decryptData(_:_:_:_:)\/title","value":"decryptData::::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1decryptData(_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decryptData::::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1addPEMWrapping(_:)\/title","value":"addPEMWrapping:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1addPEMWrapping(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPEMWrapping:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1signDataBase64(_:)\/title","value":"signDataBase64:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1signDataBase64(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signDataBase64:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1decryptDataPBE(_:_:_:_:_:)\/title","value":"decryptDataPBE:::::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1decryptDataPBE(_:_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decryptDataPBE:::::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1startInitialCertGenProcess(_:_:_:)\/title","value":"startInitialCertGenProcess:::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1startInitialCertGenProcess(_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startInitialCertGenProcess:::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setDevCert()\/title","value":"setDevCert"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setDevCert()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDevCert"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1base64Encode(_:)\/title","value":"base64Encode:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1base64Encode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"base64Encode:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getFromKeyStorage(_:)\/title","value":"getFromKeyStorage:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getFromKeyStorage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFromKeyStorage:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1envelopeDataBase64(_:)\/title","value":"envelopeDataBase64:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1envelopeDataBase64(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"envelopeDataBase64:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getPKCS12Certificates(_:_:_:_:_:)\/title","value":"getPKCS12Certificates:::::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getPKCS12Certificates(_:_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPKCS12Certificates:::::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1derEncoder(_:)\/title","value":"derEncoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1derEncoder(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"derEncoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1signData(_:_:)\/title","value":"signData::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1signData(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signData::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getErrorInfo()\/title","value":"getErrorInfo"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getErrorInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getErrorInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setPKCS12Password(_:_:_:_:)\/title","value":"setPKCS12Password::::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setPKCS12Password(_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPKCS12Password::::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1base64Decode(_:)\/title","value":"base64Decode:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1base64Decode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"base64Decode:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1addPolicyParam(_:_:)\/title","value":"addPolicyParam::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1addPolicyParam(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPolicyParam::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1encryptDataPBE(_:_:_:_:_:)\/title","value":"encryptDataPBE:::::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1encryptDataPBE(_:_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encryptDataPBE:::::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1createCertRequest()\/title","value":"createCertRequest"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1createCertRequest()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCertRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1prepareCryptData()\/title","value":"prepareCryptData"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1prepareCryptData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareCryptData"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1updateCert(_:)\/title","value":"updateCert:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1updateCert(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCert:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1remove(fromKeyStorage:)\/title","value":"removeFromKeyStorage:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1remove(fromKeyStorage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFromKeyStorage:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager\/title","value":"IPKIMobileManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager\/fragments","value":[{"kind":"identifier","text":"IPKIMobileManager"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1addRecipientCert(_:)\/title","value":"addRecipientCert:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1addRecipientCert(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRecipientCert:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setCustomSignDataHandler(_:_:)\/title","value":"setCustomSignDataHandler::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setCustomSignDataHandler(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomSignDataHandler::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1logout()\/title","value":"logout"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1logout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logout"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1loginIOS(_:)\/title","value":"loginIOS:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1loginIOS(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginIOS:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1saveLogsToZIP()\/title","value":"saveLogsToZIP"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1saveLogsToZIP()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveLogsToZIP"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1put(inKeyStorage:_:)\/title","value":"putInKeyStorage::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1put(inKeyStorage:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"putInKeyStorage::"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getDeviceFingerprint()\/title","value":"getDeviceFingerprint"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1getDeviceFingerprint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeviceFingerprint"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1resetRecipients()\/title","value":"resetRecipients"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1resetRecipients()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetRecipients"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}