{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"KS_UNSUCC_LOGIN_ATTEMPTS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ks_unsucc_login_attempts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ks_unsucc_login_attempts"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KS_UNSUCC_LOGIN_ATTEMPTS","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"KS_UNSUCC_LOGIN_ATTEMPTS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"KS_UNSUCC_LOGIN_ATTEMPTS","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:IPKIMobileManager.h@160@macro@KS_UNSUCC_LOGIN_ATTEMPTS","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"KS_UNSUCC_LOGIN_ATTEMPTS"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/KS_UNSUCC_LOGIN_ATTEMPTS":{"role":"symbol","title":"KS_UNSUCC_LOGIN_ATTEMPTS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"KS_UNSUCC_LOGIN_ATTEMPTS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KS_UNSUCC_LOGIN_ATTEMPTS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KS_UNSUCC_LOGIN_ATTEMPTS"}],"url":"\/documentation\/cshub_test\/ks_unsucc_login_attempts"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"KS_UNSUCC_LOGIN_ATTEMPTS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"KS_UNSUCC_LOGIN_ATTEMPTS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1KS_UNSUCC_LOGIN_ATTEMPTS\/title","value":"KS_UNSUCC_LOGIN_ATTEMPTS"}],"traits":[{"interfaceLanguage":"occ"}]}]}