{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/loglevel-4cq3g"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/loglevel-4cq3g"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/SY","doc:\/\/cz.csas.app.cshub.test\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/debug-ueag","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/error-3fyyj","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/info-9hcnu","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/verbose","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/init(rawValue:)-8eikd"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/Equatable-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"title":"LogLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@LogLevel","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/cshub_test\/loglevel-4cq3g"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/info-9hcnu":{"role":"symbol","title":"LogLevel.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/info-9hcnu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelInfo"}],"url":"\/documentation\/cshub_test\/loglevel-4cq3g\/info-9hcnu"},"doc://cz.csas.app.cshub.test/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SY"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/verbose":{"role":"symbol","title":"LogLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelVerbose"}],"url":"\/documentation\/cshub_test\/loglevel-4cq3g\/verbose"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/init(rawValue:)-8eikd":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/init(rawValue:)-8eikd","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/loglevel-4cq3g\/init(rawvalue:)-8eikd"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/debug-ueag":{"role":"symbol","title":"LogLevel.debug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/debug-ueag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelDebug"}],"url":"\/documentation\/cshub_test\/loglevel-4cq3g\/debug-ueag"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/error-3fyyj":{"role":"symbol","title":"LogLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/error-3fyyj","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelError"}],"url":"\/documentation\/cshub_test\/loglevel-4cq3g\/error-3fyyj"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/loglevel-4cq3g\/rawrepresentable-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/loglevel-4cq3g\/equatable-implementations"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LogLevel-4cq3g/warning":{"role":"symbol","title":"LogLevel.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelWarning"}],"url":"\/documentation\/cshub_test\/loglevel-4cq3g\/warning"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"LogLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/debug-ueag","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/error-3fyyj","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/info-9hcnu","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/verbose","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LogLevel-4cq3g\/warning"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g\/title","value":"LogLevel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1info-9hcnu\/title","value":"LogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1info-9hcnu\/fragments","value":[{"kind":"identifier","text":"LogLevelInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1verbose\/title","value":"LogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1verbose\/fragments","value":[{"kind":"identifier","text":"LogLevelVerbose"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1debug-ueag\/title","value":"LogLevelDebug"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1debug-ueag\/fragments","value":[{"kind":"identifier","text":"LogLevelDebug"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1error-3fyyj\/title","value":"LogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1error-3fyyj\/fragments","value":[{"kind":"identifier","text":"LogLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1warning\/title","value":"LogLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1LogLevel-4cq3g~1warning\/fragments","value":[{"kind":"identifier","text":"LogLevelWarning"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}