{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumericKeyboard"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/numerickeyboard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/numerickeyboard"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/backwardButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/eightButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/fiveButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/fourButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/logoButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/mainLeadingConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/mainTrailingConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/maxLength","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/nineButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/oneButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/sevenButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/sixButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/textField","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/threeButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/twoButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/zeroButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/awakeFromNib()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/deleteWasTapped(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/layoutSubviews()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/numberWasTapped(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/createKeyboard(textField:maxLength:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumericKeyboard"}],"title":"NumericKeyboard","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)NumericKeyboard","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"NumericKeyboard"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/textField","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/numerickeyboard\/textfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/eightButton":{"role":"symbol","title":"eightButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eightButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/eightButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eightButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/eightbutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/awakefromnib()"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/logoButton":{"role":"symbol","title":"logoButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logoButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/logoButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logoButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/logobutton"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/maxLength":{"role":"symbol","title":"maxLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/maxLength","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/numerickeyboard\/maxlength"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/sixButton":{"role":"symbol","title":"sixButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sixButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/sixButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sixButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/sixbutton"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/fiveButton":{"role":"symbol","title":"fiveButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fiveButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/fiveButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fiveButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/fivebutton"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/oneButton":{"role":"symbol","title":"oneButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/oneButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oneButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/onebutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/nineButton":{"role":"symbol","title":"nineButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nineButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/nineButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nineButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/ninebutton"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/backwardButton":{"role":"symbol","title":"backwardButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backwardButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/backwardButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backwardButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/backwardbutton"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/sevenButton":{"role":"symbol","title":"sevenButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sevenButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/sevenButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sevenButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/sevenbutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/mainLeadingConstraint":{"role":"symbol","title":"mainLeadingConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainLeadingConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/mainLeadingConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mainLeadingConstraint"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/mainleadingconstraint"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/createKeyboard(textField:maxLength:)":{"role":"symbol","title":"createKeyboard(textField:maxLength:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createKeyboard"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"NumericKeyboard","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)NumericKeyboard"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/createKeyboard(textField:maxLength:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/numerickeyboard\/createkeyboard(textfield:maxlength:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/initwithcoder:"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/deleteWasTapped(_:)":{"role":"symbol","title":"deleteWasTapped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteWasTapped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/deleteWasTapped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteWasTapped:"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/deletewastapped(_:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard":{"role":"symbol","title":"NumericKeyboard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumericKeyboard"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NumericKeyboard"}],"url":"\/documentation\/cshub_test\/numerickeyboard"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/threeButton":{"role":"symbol","title":"threeButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/threeButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threeButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/threebutton"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/twoButton":{"role":"symbol","title":"twoButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"twoButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/twoButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"twoButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/twobutton"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/fourButton":{"role":"symbol","title":"fourButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fourButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/fourButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fourButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/fourbutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/initwithframe:"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/layoutsubviews()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/zeroButton":{"role":"symbol","title":"zeroButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/zeroButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zeroButton"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/zerobutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/mainTrailingConstraint":{"role":"symbol","title":"mainTrailingConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mainTrailingConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/mainTrailingConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mainTrailingConstraint"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/maintrailingconstraint"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NumericKeyboard/numberWasTapped(_:)":{"role":"symbol","title":"numberWasTapped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberWasTapped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/numberWasTapped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberWasTapped:"}],"url":"\/documentation\/cshub_test\/numerickeyboard\/numberwastapped(_:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NumericKeyboard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NumericKeyboard"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NumericKeyboard"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/backwardButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/eightButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/fiveButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/fourButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/logoButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/mainLeadingConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/mainTrailingConstraint","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/nineButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/oneButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/sevenButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/sixButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/threeButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/twoButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/zeroButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/awakeFromNib()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/deleteWasTapped(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/initWithCoder:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/initWithFrame:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/layoutSubviews()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NumericKeyboard\/numberWasTapped(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumericKeyboard"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1eightButton\/title","value":"eightButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1eightButton\/fragments","value":[{"kind":"identifier","text":"eightButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1logoButton\/title","value":"logoButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1logoButton\/fragments","value":[{"kind":"identifier","text":"logoButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1sixButton\/title","value":"sixButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1sixButton\/fragments","value":[{"kind":"identifier","text":"sixButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1fiveButton\/title","value":"fiveButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1fiveButton\/fragments","value":[{"kind":"identifier","text":"fiveButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1oneButton\/title","value":"oneButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1oneButton\/fragments","value":[{"kind":"identifier","text":"oneButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1nineButton\/title","value":"nineButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1nineButton\/fragments","value":[{"kind":"identifier","text":"nineButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1backwardButton\/title","value":"backwardButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1backwardButton\/fragments","value":[{"kind":"identifier","text":"backwardButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1sevenButton\/title","value":"sevenButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1sevenButton\/fragments","value":[{"kind":"identifier","text":"sevenButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1mainLeadingConstraint\/title","value":"mainLeadingConstraint"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1mainLeadingConstraint\/fragments","value":[{"kind":"identifier","text":"mainLeadingConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1deleteWasTapped(_:)\/title","value":"deleteWasTapped:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1deleteWasTapped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteWasTapped:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard\/title","value":"NumericKeyboard"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard\/fragments","value":[{"kind":"identifier","text":"NumericKeyboard"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1threeButton\/title","value":"threeButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1threeButton\/fragments","value":[{"kind":"identifier","text":"threeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1twoButton\/title","value":"twoButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1twoButton\/fragments","value":[{"kind":"identifier","text":"twoButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1fourButton\/title","value":"fourButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1fourButton\/fragments","value":[{"kind":"identifier","text":"fourButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1zeroButton\/title","value":"zeroButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1zeroButton\/fragments","value":[{"kind":"identifier","text":"zeroButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1mainTrailingConstraint\/title","value":"mainTrailingConstraint"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1mainTrailingConstraint\/fragments","value":[{"kind":"identifier","text":"mainTrailingConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1numberWasTapped(_:)\/title","value":"numberWasTapped:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1NumericKeyboard~1numberWasTapped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberWasTapped:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}