{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pair"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/pair"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/pair"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper12BaseMappableP","doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper8MappableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/Se","doc:\/\/cz.csas.app.cshub.test\/SE","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(coder:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(from:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(map:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(name:value:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/debugDescription","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/name","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/encode(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/mapping(map:)"]},{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/appData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/appID","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/appQuit","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/callBack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/callbackData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/callbackIdentifier","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/caseID","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/meetingTopic","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/meetingType","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/nextFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/nextFlowCase","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/nextFlowJS","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/refreshTasks","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/returnAction","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/startWith"]},{"title":"Enumerations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/Keys"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/BaseMappable-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/Mappable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pair"}],"title":"Pair","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)Pair","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"Pair"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/cz.csas.app.cshub.test\/Se"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/debugDescription":{"role":"symbol","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/debugDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"url":"\/documentation\/cshub_test\/pair\/debugdescription"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/callbackData":{"role":"symbol","title":"callbackData","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"callbackData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/callbackData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/callbackdata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/init(map:)":{"role":"symbol","title":"init(map:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:12ObjectMapper3MapC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(map:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/init(map:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/nextFlowCase":{"role":"symbol","title":"nextFlowCase","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextFlowCase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/nextFlowCase","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/nextflowcase"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/appData":{"role":"symbol","title":"appData","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"appData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/appData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/appdata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/refreshTasks":{"role":"symbol","title":"refreshTasks","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshTasks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/refreshTasks","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/refreshtasks"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/init(name:value:)":{"role":"symbol","title":"init(name:value:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(name:value:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/init(name:value:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/appQuit":{"role":"symbol","title":"appQuit","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"appQuit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/appQuit","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/appquit"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/callbackIdentifier":{"role":"symbol","title":"callbackIdentifier","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"callbackIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/callbackIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/callbackidentifier"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/callBack":{"role":"symbol","title":"callBack","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"callBack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/callBack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/callback"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/returnAction":{"role":"symbol","title":"returnAction","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/returnAction","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/returnaction"},"doc://cz.csas.app.cshub.test/12ObjectMapper12BaseMappableP":{"type":"unresolvable","title":"ObjectMapper.BaseMappable","identifier":"doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper12BaseMappableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/caseID":{"role":"symbol","title":"caseID","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"caseID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/caseID","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/caseid"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/BaseMappable-Implementations":{"role":"collectionGroup","title":"BaseMappable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/BaseMappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/pair\/basemappable-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair":{"role":"symbol","title":"Pair","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pair"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Pair"}],"url":"\/documentation\/cshub_test\/pair"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/appID":{"role":"symbol","title":"appID","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"appID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/appID","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/appid"},"doc://cz.csas.app.cshub.test/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SE"},"doc://cz.csas.app.cshub.test/12ObjectMapper8MappableP":{"type":"unresolvable","title":"ObjectMapper.Mappable","identifier":"doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper8MappableP"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/pair\/init(coder:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/startWith":{"role":"symbol","title":"startWith","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"startWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/startWith","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/startwith"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/encode(with:)":{"role":"symbol","title":"encode(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/encode(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"url":"\/documentation\/cshub_test\/pair\/encode(with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/meetingType":{"role":"symbol","title":"meetingType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"meetingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/meetingType","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/meetingtype"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/pair\/mappable-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/name","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/name"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/meetingTopic":{"role":"symbol","title":"meetingTopic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"meetingTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/meetingTopic","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/meetingtopic"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/Keys":{"role":"symbol","title":"Pair.Keys","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Keys"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/Keys","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Keys"}],"url":"\/documentation\/cshub_test\/pair\/keys"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/mapping(map:)":{"role":"symbol","title":"mapping(map:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapping"},{"kind":"text","text":"("},{"kind":"externalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:12ObjectMapper3MapC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/mapping(map:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/mapping(map:)"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/value":{"role":"symbol","title":"value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/value","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/value"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/init(from:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/nextFlowJS":{"role":"symbol","title":"nextFlowJS","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextFlowJS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"as comming from the e2e cshub:\/\/ url"},{"type":"text","text":" "},{"type":"text","text":"this will get transformed to "},{"type":"codeVoice","code":"Pair.nextFlow"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/nextFlowJS","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/nextflowjs"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Pair/nextFlow":{"role":"symbol","title":"nextFlow","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextFlow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"as comming from NOBE and used in app"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/nextFlow","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pair\/nextflow"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Pair"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Pair"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Pair"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/debugDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/encode(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Pair\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pair"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair\/title","value":"Pair"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair\/fragments","value":[{"kind":"identifier","text":"Pair"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair~1encode(with:)\/title","value":"encodeWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Pair~1encode(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}