{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/init()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/init(withDocument:withView:withMetadata:delegate:elementsActive:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/currentPageIndex","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/delegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/document","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/drawingElements","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/elementsActive","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/metadata","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/originalDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/pdfAnnotations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/view"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/checkboxButtonAction(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/convertElementPosition(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/convertElementSize(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/disableInteraction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/enableInteraction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/handlePageChange(notification:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/removeDrawingElements()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scroll(toPage:animated:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidChangeAdjustedContentInset(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndDecelerating(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndScrollingAnimation(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidScroll(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidScrollToTop(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidZoom(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewShouldScrollToTop(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginDecelerating(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginDragging(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginZooming(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/signAction(forItem:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/signButtonAction(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/startSigning(ofFieldWithId:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/viewForZooming(in:)"]},{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/buttonFontSize","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypeCheckbox","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypePushButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypeSignature","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypeText"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}],"title":"PdfDocumentComponentsDrawer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)PdfDocumentComponentsDrawer","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidEndDragging(_:willDecelerate:)":{"role":"symbol","title":"scrollViewDidEndDragging(_:willDecelerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndDragging(_:willDecelerate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidenddragging(_:willdecelerate:)"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/enableInteraction()":{"role":"symbol","title":"enableInteraction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableInteraction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/enableInteraction()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/enableinteraction()"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/view":{"role":"symbol","title":"view","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFView","preciseIdentifier":"c:objc(cs)PDFView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/view","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/view"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/drawingElements":{"role":"symbol","title":"drawingElements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawingElements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PdfKitDrawingElement","preciseIdentifier":"s:10CSHub_Test20PdfKitDrawingElementC"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/drawingElements","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/drawingelements"},"doc://cz.csas.app.cshub.test/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIScrollViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidZoom(_:)":{"role":"symbol","title":"scrollViewDidZoom(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidZoom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidZoom(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidZoom:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidzoom(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/startSigning(ofFieldWithId:)":{"role":"symbol","title":"startSigning(ofFieldWithId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSigning"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofFieldWithId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/startSigning(ofFieldWithId:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/startsigning(offieldwithid:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/document":{"role":"symbol","title":"document","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDocument","preciseIdentifier":"c:objc(cs)PDFDocument"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/document","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/document"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidEndZooming(_:with:atScale:)":{"role":"symbol","title":"scrollViewDidEndZooming(_:with:atScale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndZooming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"atScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndZooming(_:with:atScale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidendzooming(_:with:atscale:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)":{"role":"symbol","title":"scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillEndDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withVelocity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetContentOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":">)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewwillenddragging(_:withvelocity:targetcontentoffset:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/init()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/currentPageIndex":{"role":"symbol","title":"currentPageIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentPageIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/currentPageIndex","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/currentpageindex"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/signAction(forItem:)":{"role":"symbol","title":"signAction(forItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PdfKitDrawingElement","preciseIdentifier":"s:10CSHub_Test20PdfKitDrawingElementC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/signAction(forItem:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/signaction(foritem:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/elementsActive":{"role":"symbol","title":"elementsActive","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"elementsActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/elementsActive","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/elementsactive"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/removeDrawingElements()":{"role":"symbol","title":"removeDrawingElements()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDrawingElements"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/removeDrawingElements()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/removedrawingelements()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scroll(toPage:animated:)":{"role":"symbol","title":"scroll(toPage:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toPage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scroll(toPage:animated:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scroll(topage:animated:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/handlePageChange(notification:)":{"role":"symbol","title":"handlePageChange(notification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePageChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/handlePageChange(notification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handlePageChangeWithNotification:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/handlepagechange(notification:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/disableInteraction()":{"role":"symbol","title":"disableInteraction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableInteraction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/disableInteraction()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/disableinteraction()"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/init(withDocument:withView:withMetadata:delegate:elementsActive:)":{"role":"symbol","title":"init(withDocument:withView:withMetadata:delegate:elementsActive:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDocument","preciseIdentifier":"c:objc(cs)PDFDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFView","preciseIdentifier":"c:objc(cs)PDFView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PdfDocumentMetaData","preciseIdentifier":"s:10CSHub_Test19PdfDocumentMetaDataC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PdfDocumentComponentsDrawerDelegate","preciseIdentifier":"s:10CSHub_Test35PdfDocumentComponentsDrawerDelegateP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elementsActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/init(withDocument:withView:withMetadata:delegate:elementsActive:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/init(withdocument:withview:withmetadata:delegate:elementsactive:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/viewForZooming(in:)":{"role":"symbol","title":"viewForZooming(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/viewForZooming(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewForZoomingInScrollView:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/viewforzooming(in:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidScrollToTop(_:)":{"role":"symbol","title":"scrollViewDidScrollToTop(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScrollToTop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidScrollToTop(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScrollToTop:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidscrolltotop(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidEndScrollingAnimation(_:)":{"role":"symbol","title":"scrollViewDidEndScrollingAnimation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndScrollingAnimation(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidendscrollinganimation(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/pdfAnnotations":{"role":"symbol","title":"pdfAnnotations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfAnnotations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PDFAnnotation","preciseIdentifier":"c:objc(cs)PDFAnnotation"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/pdfAnnotations","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/pdfannotations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/convertElementPosition(_:)":{"role":"symbol","title":"convertElementPosition(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertElementPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PdfKitDrawingElement","preciseIdentifier":"s:10CSHub_Test20PdfKitDrawingElementC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/convertElementPosition(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/convertelementposition(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/metadata":{"role":"symbol","title":"metadata","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PdfDocumentMetaData","preciseIdentifier":"s:10CSHub_Test19PdfDocumentMetaDataC"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/metadata","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/metadata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidEndDecelerating(_:)":{"role":"symbol","title":"scrollViewDidEndDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndDecelerating(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidenddecelerating(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewShouldScrollToTop(_:)":{"role":"symbol","title":"scrollViewShouldScrollToTop(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewShouldScrollToTop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewShouldScrollToTop(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewShouldScrollToTop:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewshouldscrolltotop(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/fieldTypePushButton":{"role":"symbol","title":"fieldTypePushButton","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldTypePushButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypePushButton","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/fieldtypepushbutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidScroll(_:)":{"role":"symbol","title":"scrollViewDidScroll(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidScroll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidScroll(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidScroll:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidscroll(_:)"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer":{"role":"symbol","title":"PdfDocumentComponentsDrawer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/convertElementSize(_:)":{"role":"symbol","title":"convertElementSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertElementSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/convertElementSize(_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/convertelementsize(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/signButtonAction(_:)":{"role":"symbol","title":"signButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/signButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signButtonAction:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/signbuttonaction(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewwillbegindragging(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/buttonFontSize":{"role":"symbol","title":"buttonFontSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonFontSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/buttonFontSize","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/buttonfontsize"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/fieldTypeCheckbox":{"role":"symbol","title":"fieldTypeCheckbox","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldTypeCheckbox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypeCheckbox","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/fieldtypecheckbox"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/fieldTypeText":{"role":"symbol","title":"fieldTypeText","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldTypeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypeText","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/fieldtypetext"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewWillBeginDecelerating(_:)":{"role":"symbol","title":"scrollViewWillBeginDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginDecelerating(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDecelerating:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewwillbegindecelerating(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/originalDelegate":{"role":"symbol","title":"originalDelegate","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollViewDelegate","preciseIdentifier":"c:objc(pl)UIScrollViewDelegate"},{"kind":"text","text":"??"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/originalDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/originaldelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewWillBeginZooming(_:with:)":{"role":"symbol","title":"scrollViewWillBeginZooming(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginZooming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginZooming(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginZooming:withView:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewwillbeginzooming(_:with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/fieldTypeSignature":{"role":"symbol","title":"fieldTypeSignature","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldTypeSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/fieldTypeSignature","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/fieldtypesignature"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PdfDocumentComponentsDrawerDelegate","preciseIdentifier":"s:10CSHub_Test35PdfDocumentComponentsDrawerDelegateP"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/delegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/checkboxButtonAction(_:)":{"role":"symbol","title":"checkboxButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkboxButtonAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/checkboxButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkboxButtonAction:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/checkboxbuttonaction(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollView":{"role":"symbol","title":"scrollView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/scrollViewDidChangeAdjustedContentInset(_:)":{"role":"symbol","title":"scrollViewDidChangeAdjustedContentInset(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidChangeAdjustedContentInset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidChangeAdjustedContentInset(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidChangeAdjustedContentInset:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/scrollviewdidchangeadjustedcontentinset(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PdfDocumentComponentsDrawer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/checkboxButtonAction(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/handlePageChange(notification:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/init()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidChangeAdjustedContentInset(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndDecelerating(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndDragging(_:willDecelerate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndScrollingAnimation(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidScroll(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidScrollToTop(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewDidZoom(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewShouldScrollToTop(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginDecelerating(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginDragging(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillBeginZooming(_:with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/signButtonAction(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/viewForZooming(in:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PdfDocumentComponentsDrawer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndDragging(_:willDecelerate:)\/title","value":"scrollViewDidEndDragging:willDecelerate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidZoom(_:)\/title","value":"scrollViewDidZoom:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidZoom(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidZoom:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndZooming(_:with:atScale:)\/title","value":"scrollViewDidEndZooming:withView:atScale:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndZooming(_:with:atScale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/title","value":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillEndDragging:withVelocity:targetContentOffset:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1handlePageChange(notification:)\/title","value":"handlePageChangeWithNotification:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1handlePageChange(notification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePageChangeWithNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1viewForZooming(in:)\/title","value":"viewForZoomingInScrollView:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1viewForZooming(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForZoomingInScrollView:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidScrollToTop(_:)\/title","value":"scrollViewDidScrollToTop:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidScrollToTop(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScrollToTop:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndScrollingAnimation(_:)\/title","value":"scrollViewDidEndScrollingAnimation:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndScrollingAnimation(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndScrollingAnimation:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewShouldScrollToTop(_:)\/title","value":"scrollViewShouldScrollToTop:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewShouldScrollToTop(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewShouldScrollToTop:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidScroll(_:)\/title","value":"scrollViewDidScroll:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidScroll(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidScroll:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer\/title","value":"PdfDocumentComponentsDrawer"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer\/fragments","value":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1signButtonAction(_:)\/title","value":"signButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1signButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillBeginDecelerating(_:)\/title","value":"scrollViewWillBeginDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillBeginDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDecelerating:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillBeginZooming(_:with:)\/title","value":"scrollViewWillBeginZooming:withView:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewWillBeginZooming(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginZooming:withView:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1checkboxButtonAction(_:)\/title","value":"checkboxButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1checkboxButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkboxButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidChangeAdjustedContentInset(_:)\/title","value":"scrollViewDidChangeAdjustedContentInset:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1scrollViewDidChangeAdjustedContentInset(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidChangeAdjustedContentInset:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}