{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PercentualWidth"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/percentualwidth"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementHeaderView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowLandscapeCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PercentualWidth","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PercentualWidth\/setPercentualWidth(portrait:viewWidth:labels:)-1wvyt"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PercentualWidth"}],"title":"PercentualWidth","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test15PercentualWidthP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"PercentualWidth"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementRowCell":{"role":"symbol","title":"ManagementRowCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementRowCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementRowCell"}],"url":"\/documentation\/cshub_test\/managementrowcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PercentualWidth":{"role":"symbol","title":"PercentualWidth","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PercentualWidth"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PercentualWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PercentualWidth"}],"url":"\/documentation\/cshub_test\/percentualwidth"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementHeaderView":{"role":"symbol","title":"ManagementHeaderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementHeaderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementHeaderView"}],"url":"\/documentation\/cshub_test\/managementheaderview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementRowLandscapeCell":{"role":"symbol","title":"ManagementRowLandscapeCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementRowLandscapeCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowLandscapeCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementRowLandscapeCell"}],"url":"\/documentation\/cshub_test\/managementrowlandscapecell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PercentualWidth/setPercentualWidth(portrait:viewWidth:labels:)-1wvyt":{"defaultImplementations":1,"role":"symbol","title":"setPercentualWidth(portrait:viewWidth:labels:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPercentualWidth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"portrait"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SteviaAttribute","preciseIdentifier":"s:6Stevia0A9AttributeV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"labels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PercentualWidth\/setPercentualWidth(portrait:viewWidth:labels:)-1wvyt","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/percentualwidth\/setpercentualwidth(portrait:viewwidth:labels:)-1wvyt"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowCell\/title","value":"ManagementRowCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowCell\/fragments","value":[{"kind":"identifier","text":"ManagementRowCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementHeaderView\/title","value":"ManagementHeaderView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementHeaderView\/fragments","value":[{"kind":"identifier","text":"ManagementHeaderView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowLandscapeCell\/title","value":"ManagementRowLandscapeCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowLandscapeCell\/fragments","value":[{"kind":"identifier","text":"ManagementRowLandscapeCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}