{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIAppBio"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/pkiappbio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/pkiappbio"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/addRecipientCert(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/base64Decode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/base64Encode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/decryptDataPBE(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/derEncode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/encryptDataPBE(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/envelopeDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getErrorMsg()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getFromKeyStorage(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getPKCS12Certificates(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/loginIOSDevice(_:withBioSignDelegate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/loginPKCS12(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/logout()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/put(inKeyStorage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/remove(fromKeyStorage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/resetRecipients()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/signData(_:withPrivateKey:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/signDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/unwrapDataBase64(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIAppBio"}],"title":"PKIAppBio","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)PKIAppBio","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"PKIAppBio"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/getErrorMsg()":{"role":"symbol","title":"getErrorMsg()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getErrorMsg"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getErrorMsg()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getErrorMsg"}],"url":"\/documentation\/cshub_test\/pkiappbio\/geterrormsg()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/put(inKeyStorage:)":{"role":"symbol","title":"put(inKeyStorage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"put"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inKeyStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/put(inKeyStorage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"putInKeyStorage:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/put(inkeystorage:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/base64Decode(_:)":{"role":"symbol","title":"base64Decode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"base64Decode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/base64Decode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"base64Decode:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/base64decode(_:)"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/decryptDataPBE(_:)":{"role":"symbol","title":"decryptDataPBE(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptDataPBE"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/decryptDataPBE(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decryptDataPBE:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/decryptdatapbe(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/envelopeDataBase64(_:)":{"role":"symbol","title":"envelopeDataBase64(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"envelopeDataBase64"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/envelopeDataBase64(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"envelopeDataBase64:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/envelopedatabase64(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/derEncode(_:)":{"role":"symbol","title":"derEncode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"derEncode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/derEncode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"derEncode:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/derencode(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/remove(fromKeyStorage:)":{"role":"symbol","title":"remove(fromKeyStorage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromKeyStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/remove(fromKeyStorage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFromKeyStorage:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/remove(fromkeystorage:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/loginPKCS12(_:)":{"role":"symbol","title":"loginPKCS12(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginPKCS12"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/loginPKCS12(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginPKCS12:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/loginpkcs12(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/encryptDataPBE(_:)":{"role":"symbol","title":"encryptDataPBE(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptDataPBE"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/encryptDataPBE(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encryptDataPBE:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/encryptdatapbe(_:)"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio":{"role":"symbol","title":"PKIAppBio","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIAppBio"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PKIAppBio"}],"url":"\/documentation\/cshub_test\/pkiappbio"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/signDataBase64(_:)":{"role":"symbol","title":"signDataBase64(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signDataBase64"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/signDataBase64(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signDataBase64:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/signdatabase64(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/logout()":{"role":"symbol","title":"logout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/logout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logout"}],"url":"\/documentation\/cshub_test\/pkiappbio\/logout()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/m_pPKIManager":{"role":"symbol","title":"m_pPKIManager","fragments":[{"kind":"identifier","text":"m_pPKIManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/m_pPKIManager","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/pkiappbio\/m_ppkimanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/addRecipientCert(_:)":{"role":"symbol","title":"addRecipientCert(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRecipientCert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/addRecipientCert(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRecipientCert:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/addrecipientcert(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/resetRecipients()":{"role":"symbol","title":"resetRecipients()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetRecipients"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/resetRecipients()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetRecipients"}],"url":"\/documentation\/cshub_test\/pkiappbio\/resetrecipients()"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/loginIOSDevice(_:withBioSignDelegate:)":{"role":"symbol","title":"loginIOSDevice(_:withBioSignDelegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loginIOSDevice"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withBioSignDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/loginIOSDevice(_:withBioSignDelegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginIOSDevice:withBioSignDelegate:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/loginiosdevice(_:withbiosigndelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/getPKCS12Certificates(_:)":{"role":"symbol","title":"getPKCS12Certificates(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPKCS12Certificates"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getPKCS12Certificates(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPKCS12Certificates:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/getpkcs12certificates(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/unwrapDataBase64(_:)":{"role":"symbol","title":"unwrapDataBase64(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unwrapDataBase64"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/unwrapDataBase64(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unwrapDataBase64:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/unwrapdatabase64(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/base64Encode(_:)":{"role":"symbol","title":"base64Encode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"base64Encode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/base64Encode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"base64Encode:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/base64encode(_:)"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/signData(_:withPrivateKey:)":{"role":"symbol","title":"signData(_:withPrivateKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withPrivateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/signData(_:withPrivateKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"signData:withPrivateKey:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/signdata(_:withprivatekey:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PKIAppBio/getFromKeyStorage(_:)":{"role":"symbol","title":"getFromKeyStorage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFromKeyStorage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getFromKeyStorage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFromKeyStorage:"}],"url":"\/documentation\/cshub_test\/pkiappbio\/getfromkeystorage(_:)"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PKIAppBio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PKIAppBio"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PKIAppBio"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Variables","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/m_pPKIManager"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/addRecipientCert(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/base64Decode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/base64Encode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/decryptDataPBE(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/derEncode(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/encryptDataPBE(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/envelopeDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getErrorMsg()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getFromKeyStorage(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/getPKCS12Certificates(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/loginIOSDevice(_:withBioSignDelegate:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/loginPKCS12(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/logout()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/put(inKeyStorage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/remove(fromKeyStorage:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/resetRecipients()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/signData(_:withPrivateKey:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/signDataBase64(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PKIAppBio\/unwrapDataBase64(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKIAppBio"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getErrorMsg()\/title","value":"getErrorMsg"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getErrorMsg()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getErrorMsg"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1put(inKeyStorage:)\/title","value":"putInKeyStorage:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1put(inKeyStorage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"putInKeyStorage:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1base64Decode(_:)\/title","value":"base64Decode:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1base64Decode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"base64Decode:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1decryptDataPBE(_:)\/title","value":"decryptDataPBE:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1decryptDataPBE(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decryptDataPBE:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1envelopeDataBase64(_:)\/title","value":"envelopeDataBase64:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1envelopeDataBase64(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"envelopeDataBase64:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1derEncode(_:)\/title","value":"derEncode:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1derEncode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"derEncode:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1remove(fromKeyStorage:)\/title","value":"removeFromKeyStorage:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1remove(fromKeyStorage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFromKeyStorage:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1loginPKCS12(_:)\/title","value":"loginPKCS12:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1loginPKCS12(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginPKCS12:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1encryptDataPBE(_:)\/title","value":"encryptDataPBE:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1encryptDataPBE(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encryptDataPBE:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio\/title","value":"PKIAppBio"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio\/fragments","value":[{"kind":"identifier","text":"PKIAppBio"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1signDataBase64(_:)\/title","value":"signDataBase64:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1signDataBase64(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signDataBase64:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1logout()\/title","value":"logout"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1logout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logout"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1addRecipientCert(_:)\/title","value":"addRecipientCert:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1addRecipientCert(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRecipientCert:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1resetRecipients()\/title","value":"resetRecipients"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1resetRecipients()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetRecipients"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1loginIOSDevice(_:withBioSignDelegate:)\/title","value":"loginIOSDevice:withBioSignDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1loginIOSDevice(_:withBioSignDelegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginIOSDevice:withBioSignDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getPKCS12Certificates(_:)\/title","value":"getPKCS12Certificates:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getPKCS12Certificates(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPKCS12Certificates:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1unwrapDataBase64(_:)\/title","value":"unwrapDataBase64:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1unwrapDataBase64(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unwrapDataBase64:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1base64Encode(_:)\/title","value":"base64Encode:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1base64Encode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"base64Encode:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1signData(_:withPrivateKey:)\/title","value":"signData:withPrivateKey:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1signData(_:withPrivateKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signData:withPrivateKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getFromKeyStorage(_:)\/title","value":"getFromKeyStorage:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PKIAppBio~1getFromKeyStorage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFromKeyStorage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}