{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presentable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/presentable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Flow"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApiBaseViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplicationFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsManagerFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BankerAuthViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometricModule","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CCIFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CDMFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CSHubBaseViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ClDocFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentConfirmationController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsListController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/HostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KycFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRCameraViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PencilAlertViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRScannerViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SafariApplicationFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserApplicationFlow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable\/dismissed-79ici","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable\/visible-1vx74"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presentable"}],"title":"Presentable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test11PresentableP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"Presentable"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CDMFlow":{"role":"symbol","title":"CDMFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CDMFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CDMFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CDMFlow"}],"url":"\/documentation\/cshub_test\/cdmflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IdentificationUIHostingController":{"role":"symbol","title":"IdentificationUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentificationUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentificationUIHostingController"}],"url":"\/documentation\/cshub_test\/identificationuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/QRScannerViewController":{"role":"symbol","title":"QRScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QRScannerViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QRScannerViewController"}],"url":"\/documentation\/cshub_test\/qrscannerviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentFlow":{"role":"symbol","title":"AppointmentFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentFlow"}],"url":"\/documentation\/cshub_test\/appointmentflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserApplicationFlow":{"role":"symbol","title":"WebBrowserApplicationFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserApplicationFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserApplicationFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebBrowserApplicationFlow"}],"url":"\/documentation\/cshub_test\/webbrowserapplicationflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CSHubBaseViewController":{"role":"symbol","title":"CSHubBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CSHubBaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CSHubBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CSHubBaseViewController"}],"url":"\/documentation\/cshub_test\/cshubbaseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PairingUIHostingViewController":{"role":"symbol","title":"PairingUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PairingUIHostingViewController"}],"url":"\/documentation\/cshub_test\/pairinguihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentManagementViewController":{"role":"symbol","title":"AppointmentManagementViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentManagementViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentManagementViewController"}],"url":"\/documentation\/cshub_test\/appointmentmanagementviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BiometricModule":{"role":"symbol","title":"BiometricModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometricModule"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometricModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BiometricModule"}],"url":"\/documentation\/cshub_test\/biometricmodule"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentsUIHostingController":{"role":"symbol","title":"AppointmentsUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentsUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentsUIHostingController"}],"url":"\/documentation\/cshub_test\/appointmentsuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentConfirmationController":{"role":"symbol","title":"DocumentConfirmationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentConfirmationController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentConfirmationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentConfirmationController"}],"url":"\/documentation\/cshub_test\/documentconfirmationcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentViewController":{"role":"symbol","title":"AppointmentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentViewController"}],"url":"\/documentation\/cshub_test\/appointmentviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController":{"role":"symbol","title":"BioSignatureOverlayController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignatureOverlayController"}],"url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRCameraViewController":{"role":"symbol","title":"OCRCameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRCameraViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRCameraViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRCameraViewController"}],"url":"\/documentation\/cshub_test\/ocrcameraviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryViewController":{"role":"symbol","title":"ZenIDSummaryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSummaryViewController"}],"url":"\/documentation\/cshub_test\/zenidsummaryviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewController":{"role":"symbol","title":"SignpadViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewController"}],"url":"\/documentation\/cshub_test\/signpadviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListController":{"role":"symbol","title":"E2eDocumentListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentListController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentListController"}],"url":"\/documentation\/cshub_test\/e2edocumentlistcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationFlow":{"role":"symbol","title":"WebApplicationFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationFlow"}],"url":"\/documentation\/cshub_test\/webapplicationflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SafariApplicationFlow":{"role":"symbol","title":"SafariApplicationFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SafariApplicationFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SafariApplicationFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SafariApplicationFlow"}],"url":"\/documentation\/cshub_test\/safariapplicationflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BankerAuthViewController":{"role":"symbol","title":"BankerAuthViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BankerAuthViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BankerAuthViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BankerAuthViewController"}],"url":"\/documentation\/cshub_test\/bankerauthviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController":{"role":"symbol","title":"FaqViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqViewController"}],"url":"\/documentation\/cshub_test\/faqviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/HostingController":{"role":"symbol","title":"HostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/HostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HostingController"}],"url":"\/documentation\/cshub_test\/hostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRFlow":{"role":"symbol","title":"OCRFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRFlow"}],"url":"\/documentation\/cshub_test\/ocrflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/KycFlow":{"role":"symbol","title":"KycFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KycFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KycFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KycFlow"}],"url":"\/documentation\/cshub_test\/kycflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDContactInfoViewController":{"role":"symbol","title":"ZenIDContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidcontactinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BiometrySignFlow":{"role":"symbol","title":"BiometrySignFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometrySignFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BiometrySignFlow"}],"url":"\/documentation\/cshub_test\/biometrysignflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignatureOverlayViewController":{"role":"symbol","title":"SignatureOverlayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignatureOverlayViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignatureOverlayViewController"}],"url":"\/documentation\/cshub_test\/signatureoverlayviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewController":{"role":"symbol","title":"CameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewController"}],"abstract":[{"type":"text","text":"Credits: https:\/\/www.objc.io\/issues\/21-camera-and-photos\/camera-capture-on-ios\/"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewController"}],"url":"\/documentation\/cshub_test\/cameraviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PairingFlow":{"role":"symbol","title":"PairingFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PairingFlow"}],"url":"\/documentation\/cshub_test\/pairingflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Flow":{"role":"symbol","title":"Flow","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Flow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Flow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Flow"}],"url":"\/documentation\/cshub_test\/flow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PencilAlertViewController":{"role":"symbol","title":"PencilAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PencilAlertViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PencilAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PencilAlertViewController"}],"url":"\/documentation\/cshub_test\/pencilalertviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApiBaseViewController":{"role":"symbol","title":"ApiBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApiBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApiBaseViewController"}],"url":"\/documentation\/cshub_test\/apibaseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LegalizationFlow":{"role":"symbol","title":"LegalizationFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegalizationFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegalizationFlow"}],"url":"\/documentation\/cshub_test\/legalizationflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApplicationFlow":{"role":"symbol","title":"ApplicationFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplicationFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApplicationFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplicationFlow"}],"url":"\/documentation\/cshub_test\/applicationflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BiometrySignViewController":{"role":"symbol","title":"BiometrySignViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometrySignViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BiometrySignViewController"}],"url":"\/documentation\/cshub_test\/biometrysignviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Presentable/dismissed-79ici":{"defaultImplementations":2,"role":"symbol","title":"dismissed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable\/dismissed-79ici","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/presentable\/dismissed-79ici"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentsManagerFlow":{"role":"symbol","title":"AppointmentsManagerFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentsManagerFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsManagerFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentsManagerFlow"}],"url":"\/documentation\/cshub_test\/appointmentsmanagerflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DashboardFlow":{"role":"symbol","title":"DashboardFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DashboardFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DashboardFlow"}],"url":"\/documentation\/cshub_test\/dashboardflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDViewController":{"role":"symbol","title":"ZenIDViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDViewController"}],"url":"\/documentation\/cshub_test\/zenidviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CCIFlow":{"role":"symbol","title":"CCIFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCIFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CCIFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CCIFlow"}],"url":"\/documentation\/cshub_test\/cciflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LegalizationUIHostingController":{"role":"symbol","title":"LegalizationUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegalizationUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegalizationUIHostingController"}],"url":"\/documentation\/cshub_test\/legalizationuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DashboardUIHostingViewController":{"role":"symbol","title":"DashboardUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DashboardUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DashboardUIHostingViewController"}],"url":"\/documentation\/cshub_test\/dashboarduihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqUIHostingViewController":{"role":"symbol","title":"FaqUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqUIHostingViewController"}],"url":"\/documentation\/cshub_test\/faquihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingController":{"role":"symbol","title":"EmailCollectingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCollectingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmailCollectingController"}],"url":"\/documentation\/cshub_test\/emailcollectingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRUIHostingViewController":{"role":"symbol","title":"OCRUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRUIHostingViewController"}],"url":"\/documentation\/cshub_test\/ocruihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BaseViewController":{"conformance":{"constraints":[{"type":"codeVoice","code":"VM"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"IViewModel"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/cshub_test\/baseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoViewController":{"role":"symbol","title":"ZenIDPersonalInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Presentable/visible-1vx74":{"defaultImplementations":2,"role":"symbol","title":"visible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable\/visible-1vx74","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/presentable\/visible-1vx74"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OnlineMeetingsUIHostingController":{"role":"symbol","title":"OnlineMeetingsUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnlineMeetingsUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnlineMeetingsUIHostingController"}],"url":"\/documentation\/cshub_test\/onlinemeetingsuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Presentable":{"role":"symbol","title":"Presentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presentable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Presentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Presentable"}],"url":"\/documentation\/cshub_test\/presentable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentsListController":{"role":"symbol","title":"DocumentsListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentsListController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentsListController"}],"url":"\/documentation\/cshub_test\/documentslistcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IdentificationFlow":{"role":"symbol","title":"IdentificationFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentificationFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentificationFlow"}],"url":"\/documentation\/cshub_test\/identificationflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ClDocFlow":{"role":"symbol","title":"ClDocFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClDocFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ClDocFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClDocFlow"}],"url":"\/documentation\/cshub_test\/cldocflow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OnlineMeetingsFlow":{"role":"symbol","title":"OnlineMeetingsFlow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnlineMeetingsFlow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnlineMeetingsFlow"}],"url":"\/documentation\/cshub_test\/onlinemeetingsflow"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BiometricModule\/title","value":"BiometricModule"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BiometricModule\/fragments","value":[{"kind":"identifier","text":"BiometricModule"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/title","value":"FaqViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/fragments","value":[{"kind":"identifier","text":"FaqViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}