{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Reusable"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/reusable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApiBaseViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BankerAuthViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CSHubBaseViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CalendarTableRow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentConfirmationController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsListController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowLandscapeCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRCameraViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsUIHostingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingUIHostingViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PencilAlertViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRScannerViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RoundedCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ShadowCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCountryCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenResultCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Reusable","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Reusable\/identifier-5yvxq"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Reusable"}],"title":"Reusable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test8ReusableP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"Reusable"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PencilAlertViewController":{"role":"symbol","title":"PencilAlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PencilAlertViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PencilAlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PencilAlertViewController"}],"url":"\/documentation\/cshub_test\/pencilalertviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentManagementViewController":{"role":"symbol","title":"AppointmentManagementViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentManagementViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentManagementViewController"}],"url":"\/documentation\/cshub_test\/appointmentmanagementviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IdentificationUIHostingController":{"role":"symbol","title":"IdentificationUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentificationUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentificationUIHostingController"}],"url":"\/documentation\/cshub_test\/identificationuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentCell":{"role":"symbol","title":"DocumentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentCell"}],"abstract":[{"type":"text","text":"cell representing the captured page located under the camera"},{"type":"text","text":" "},{"type":"text","text":"capture"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentCell"}],"url":"\/documentation\/cshub_test\/documentcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentCell":{"role":"symbol","title":"E2eDocumentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentCell"}],"abstract":[{"type":"text","text":"cell with image of first pdf file page"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentCell"}],"url":"\/documentation\/cshub_test\/e2edocumentcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RoundedCell":{"role":"symbol","title":"RoundedCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundedCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RoundedCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoundedCell"}],"url":"\/documentation\/cshub_test\/roundedcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRCameraViewController":{"role":"symbol","title":"OCRCameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRCameraViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRCameraViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRCameraViewController"}],"url":"\/documentation\/cshub_test\/ocrcameraviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentConfirmationController":{"role":"symbol","title":"DocumentConfirmationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentConfirmationController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentConfirmationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentConfirmationController"}],"url":"\/documentation\/cshub_test\/documentconfirmationcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentCell":{"role":"symbol","title":"ZenIDDocumentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDDocumentCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDDocumentCell"}],"url":"\/documentation\/cshub_test\/zeniddocumentcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenResultCell":{"role":"symbol","title":"ZenResultCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenResultCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenResultCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenResultCell"}],"url":"\/documentation\/cshub_test\/zenresultcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ApiBaseViewController":{"role":"symbol","title":"ApiBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApiBaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ApiBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApiBaseViewController"}],"url":"\/documentation\/cshub_test\/apibaseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListController":{"role":"symbol","title":"E2eDocumentListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentListController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentListController"}],"url":"\/documentation\/cshub_test\/e2edocumentlistcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentsUIHostingController":{"role":"symbol","title":"AppointmentsUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentsUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentsUIHostingController"}],"url":"\/documentation\/cshub_test\/appointmentsuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController":{"role":"symbol","title":"BioSignatureOverlayController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignatureOverlayController"}],"url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDContactInfoViewController":{"role":"symbol","title":"ZenIDContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidcontactinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqCell":{"role":"symbol","title":"FaqCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqCell"}],"url":"\/documentation\/cshub_test\/faqcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OnlineMeetingsUIHostingController":{"role":"symbol","title":"OnlineMeetingsUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnlineMeetingsUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnlineMeetingsUIHostingController"}],"url":"\/documentation\/cshub_test\/onlinemeetingsuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CalendarTableRow":{"role":"symbol","title":"CalendarTableRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalendarTableRow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CalendarTableRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalendarTableRow"}],"url":"\/documentation\/cshub_test\/calendartablerow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraViewController":{"role":"symbol","title":"CameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraViewController"}],"abstract":[{"type":"text","text":"Credits: https:\/\/www.objc.io\/issues\/21-camera-and-photos\/camera-capture-on-ios\/"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraViewController"}],"url":"\/documentation\/cshub_test\/cameraviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentsListController":{"role":"symbol","title":"DocumentsListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentsListController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentsListController"}],"url":"\/documentation\/cshub_test\/documentslistcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqUIHostingViewController":{"role":"symbol","title":"FaqUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqUIHostingViewController"}],"url":"\/documentation\/cshub_test\/faquihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoViewController":{"role":"symbol","title":"ZenIDPersonalInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BiometrySignViewController":{"role":"symbol","title":"BiometrySignViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometrySignViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BiometrySignViewController"}],"url":"\/documentation\/cshub_test\/biometrysignviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BaseViewController":{"role":"symbol","title":"BaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseViewController"}],"url":"\/documentation\/cshub_test\/baseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressCell":{"role":"symbol","title":"ZenIDAddressCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDAddressCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDAddressCell"}],"url":"\/documentation\/cshub_test\/zenidaddresscell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/QRScannerViewController":{"role":"symbol","title":"QRScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QRScannerViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QRScannerViewController"}],"url":"\/documentation\/cshub_test\/qrscannerviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDViewController":{"role":"symbol","title":"ZenIDViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDViewController"}],"url":"\/documentation\/cshub_test\/zenidviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentViewController":{"role":"symbol","title":"AppointmentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentViewController"}],"url":"\/documentation\/cshub_test\/appointmentviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DashboardUIHostingViewController":{"role":"symbol","title":"DashboardUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DashboardUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DashboardUIHostingViewController"}],"url":"\/documentation\/cshub_test\/dashboarduihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryViewController":{"role":"symbol","title":"ZenIDSummaryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSummaryViewController"}],"url":"\/documentation\/cshub_test\/zenidsummaryviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewController":{"role":"symbol","title":"SignpadViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewController"}],"url":"\/documentation\/cshub_test\/signpadviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CSHubBaseViewController":{"role":"symbol","title":"CSHubBaseViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CSHubBaseViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CSHubBaseViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CSHubBaseViewController"}],"url":"\/documentation\/cshub_test\/cshubbaseviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRUIHostingViewController":{"role":"symbol","title":"OCRUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRUIHostingViewController"}],"url":"\/documentation\/cshub_test\/ocruihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignatureOverlayViewController":{"role":"symbol","title":"SignatureOverlayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignatureOverlayViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignatureOverlayViewController"}],"url":"\/documentation\/cshub_test\/signatureoverlayviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCountryCell":{"role":"symbol","title":"ZenIDCountryCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCountryCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCountryCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCountryCell"}],"url":"\/documentation\/cshub_test\/zenidcountrycell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Reusable":{"role":"symbol","title":"Reusable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Reusable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Reusable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Reusable"}],"url":"\/documentation\/cshub_test\/reusable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingController":{"role":"symbol","title":"EmailCollectingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCollectingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmailCollectingController"}],"url":"\/documentation\/cshub_test\/emailcollectingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentItemCell":{"role":"symbol","title":"DocumentItemCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentItemCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentItemCell"}],"url":"\/documentation\/cshub_test\/documentitemcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BankerAuthViewController":{"role":"symbol","title":"BankerAuthViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BankerAuthViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BankerAuthViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BankerAuthViewController"}],"url":"\/documentation\/cshub_test\/bankerauthviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PairingUIHostingViewController":{"role":"symbol","title":"PairingUIHostingViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingUIHostingViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingUIHostingViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PairingUIHostingViewController"}],"url":"\/documentation\/cshub_test\/pairinguihostingviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingCell":{"role":"symbol","title":"EmailCollectingCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCollectingCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmailCollectingCell"}],"url":"\/documentation\/cshub_test\/emailcollectingcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementRowCell":{"role":"symbol","title":"ManagementRowCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementRowCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementRowCell"}],"url":"\/documentation\/cshub_test\/managementrowcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LegalizationUIHostingController":{"role":"symbol","title":"LegalizationUIHostingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegalizationUIHostingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationUIHostingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegalizationUIHostingController"}],"url":"\/documentation\/cshub_test\/legalizationuihostingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ShadowCell":{"role":"symbol","title":"ShadowCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShadowCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ShadowCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShadowCell"}],"url":"\/documentation\/cshub_test\/shadowcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Reusable/identifier-5yvxq":{"defaultImplementations":2,"role":"symbol","title":"identifier","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Reusable\/identifier-5yvxq","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/reusable\/identifier-5yvxq"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementRowLandscapeCell":{"role":"symbol","title":"ManagementRowLandscapeCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementRowLandscapeCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowLandscapeCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementRowLandscapeCell"}],"url":"\/documentation\/cshub_test\/managementrowlandscapecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentCell\/title","value":"DocumentCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentCell\/fragments","value":[{"kind":"identifier","text":"DocumentCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentCell\/title","value":"E2eDocumentCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentCell\/fragments","value":[{"kind":"identifier","text":"E2eDocumentCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RoundedCell\/title","value":"RoundedCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RoundedCell\/fragments","value":[{"kind":"identifier","text":"RoundedCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentCell\/title","value":"ZenIDDocumentCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentCell\/fragments","value":[{"kind":"identifier","text":"ZenIDDocumentCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenResultCell\/title","value":"ZenResultCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenResultCell\/fragments","value":[{"kind":"identifier","text":"ZenResultCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/title","value":"FaqCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/fragments","value":[{"kind":"identifier","text":"FaqCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CalendarTableRow\/title","value":"CalendarTableRow"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CalendarTableRow\/fragments","value":[{"kind":"identifier","text":"CalendarTableRow"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressCell\/title","value":"ZenIDAddressCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressCell\/fragments","value":[{"kind":"identifier","text":"ZenIDAddressCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCountryCell\/title","value":"ZenIDCountryCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCountryCell\/fragments","value":[{"kind":"identifier","text":"ZenIDCountryCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentItemCell\/title","value":"DocumentItemCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentItemCell\/fragments","value":[{"kind":"identifier","text":"DocumentItemCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingCell\/title","value":"EmailCollectingCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingCell\/fragments","value":[{"kind":"identifier","text":"EmailCollectingCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowCell\/title","value":"ManagementRowCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowCell\/fragments","value":[{"kind":"identifier","text":"ManagementRowCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ShadowCell\/title","value":"ShadowCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ShadowCell\/fragments","value":[{"kind":"identifier","text":"ShadowCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowLandscapeCell\/title","value":"ManagementRowLandscapeCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowLandscapeCell\/fragments","value":[{"kind":"identifier","text":"ManagementRowLandscapeCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}