{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/signpadviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/signpadviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendCallback(withPayload:forFunction:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendReturn(withPayload:withCallId:forFunction:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/showAlert(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/signpadSizeCoefficient()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"title":"SignpadViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SignpadViewControllerDelegate","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate/showAlert(_:)":{"navigatorTitle":[{"kind":"identifier","text":"showAlert:"}],"role":"symbol","title":"showAlert(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAlert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/showAlert(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/showalert(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate/sendReturn(withPayload:withCallId:forFunction:)":{"navigatorTitle":[{"kind":"identifier","text":"sendReturnWithPayload:withCallId:forFunction:"}],"role":"symbol","title":"sendReturn(withPayload:withCallId:forFunction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendReturn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withCallId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forFunction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendReturn(withPayload:withCallId:forFunction:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/sendreturn(withpayload:withcallid:forfunction:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate/signpadSizeCoefficient()":{"navigatorTitle":[{"kind":"identifier","text":"signpadSizeCoefficient"}],"role":"symbol","title":"signpadSizeCoefficient()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signpadSizeCoefficient"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/signpadSizeCoefficient()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/signpadsizecoefficient()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate":{"role":"symbol","title":"SignpadViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewControllerDelegate/sendCallback(withPayload:forFunction:)":{"navigatorTitle":[{"kind":"identifier","text":"sendCallbackWithPayload:forFunction:"}],"role":"symbol","title":"sendCallback(withPayload:forFunction:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCallback"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"forFunction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendCallback(withPayload:forFunction:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/signpadviewcontrollerdelegate\/sendcallback(withpayload:forfunction:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewModel":{"role":"symbol","title":"SignpadViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewModel"}],"url":"\/documentation\/cshub_test\/signpadviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SignpadViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendCallback(withPayload:forFunction:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/sendReturn(withPayload:withCallId:forFunction:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/showAlert(_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewControllerDelegate\/signpadSizeCoefficient()"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewControllerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1showAlert(_:)\/title","value":"showAlert:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1showAlert(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAlert:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1sendReturn(withPayload:withCallId:forFunction:)\/title","value":"sendReturnWithPayload:withCallId:forFunction:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1sendReturn(withPayload:withCallId:forFunction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendReturnWithPayload:withCallId:forFunction:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1signpadSizeCoefficient()\/title","value":"signpadSizeCoefficient"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1signpadSizeCoefficient()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"signpadSizeCoefficient"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/title","value":"SignpadViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SignpadViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1sendCallback(withPayload:forFunction:)\/title","value":"sendCallbackWithPayload:forFunction:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1SignpadViewControllerDelegate~1sendCallback(withPayload:forFunction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendCallbackWithPayload:forFunction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}