{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stepper"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/stepper"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppStateViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppStepper"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentCoordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsManagementApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CCIViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CDMApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CLDocCoordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ClDocApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultAlertViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultAppStepper","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultStepper","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationCoordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KycApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KycViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationCoordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NoneStepper","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRCameraViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OneStepper","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PencilAlertViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PushAlertViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRCodeScannerViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SafariApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SafariApplicationFlow\/SFSafariDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SplashViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/VersionCheckViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserApplication","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper\/initialStep-85agc","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper\/steps"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper\/readyToEmitSteps()-7o0h"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stepper"}],"title":"Stepper","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test7StepperP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"Stepper"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CDMApplication":{"role":"symbol","title":"CDMApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CDMApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CDMApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CDMApplication"}],"url":"\/documentation\/cshub_test\/cdmapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRCameraViewModel":{"role":"symbol","title":"OCRCameraViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRCameraViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRCameraViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRCameraViewModel"}],"url":"\/documentation\/cshub_test\/ocrcameraviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultStepper":{"role":"symbol","title":"DefaultStepper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultStepper"}],"abstract":[{"type":"text","text":"A Simple Stepper that has one goal: emit a first default step equal to FlowStep.home"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultStepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultStepper"}],"url":"\/documentation\/cshub_test\/defaultstepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentViewController":{"role":"symbol","title":"AppointmentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentViewController"}],"url":"\/documentation\/cshub_test\/appointmentviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultAlertViewModel":{"role":"symbol","title":"DefaultAlertViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAlertViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultAlertViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultAlertViewModel"}],"url":"\/documentation\/cshub_test\/defaultalertviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper/readyToEmitSteps()-7o0h":{"defaultImplementations":1,"role":"symbol","title":"readyToEmitSteps()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToEmitSteps"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper\/readyToEmitSteps()-7o0h","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/stepper\/readytoemitsteps()-7o0h"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController":{"role":"symbol","title":"FaqViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqViewController"}],"url":"\/documentation\/cshub_test\/faqviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/NoneStepper":{"role":"symbol","title":"NoneStepper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NoneStepper"}],"abstract":[{"type":"text","text":"a Stepper that triggers NoStep."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/NoneStepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NoneStepper"}],"url":"\/documentation\/cshub_test\/nonestepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper/initialStep-85agc":{"defaultImplementations":1,"role":"symbol","title":"initialStep","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialStep"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Step","preciseIdentifier":"s:10CSHub_Test4StepP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper\/initialStep-85agc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/stepper\/initialstep-85agc"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IdentificationApplication":{"role":"symbol","title":"IdentificationApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentificationApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentificationApplication"}],"url":"\/documentation\/cshub_test\/identificationapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentsManagementApplication":{"role":"symbol","title":"AppointmentsManagementApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentsManagementApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentsManagementApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentsManagementApplication"}],"url":"\/documentation\/cshub_test\/appointmentsmanagementapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/VersionCheckViewModel":{"role":"symbol","title":"VersionCheckViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VersionCheckViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/VersionCheckViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VersionCheckViewModel"}],"url":"\/documentation\/cshub_test\/versioncheckviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BiometrySignApplication":{"role":"symbol","title":"BiometrySignApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometrySignApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BiometrySignApplication"}],"url":"\/documentation\/cshub_test\/biometrysignapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper":{"role":"symbol","title":"Stepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stepper"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Stepper"}],"url":"\/documentation\/cshub_test\/stepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListViewModel":{"role":"symbol","title":"E2eDocumentListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentListViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentListViewModel"}],"url":"\/documentation\/cshub_test\/e2edocumentlistviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentCoordinator":{"role":"symbol","title":"AppointmentCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentCoordinator"}],"url":"\/documentation\/cshub_test\/appointmentcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryViewController":{"role":"symbol","title":"ZenIDSummaryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSummaryViewController"}],"url":"\/documentation\/cshub_test\/zenidsummaryviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel":{"role":"symbol","title":"WebBrowserViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebBrowserViewModel"}],"url":"\/documentation\/cshub_test\/webbrowserviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDViewController":{"role":"symbol","title":"ZenIDViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDViewController"}],"url":"\/documentation\/cshub_test\/zenidviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoViewController":{"role":"symbol","title":"ZenIDPersonalInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PairingViewModel":{"role":"symbol","title":"PairingViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PairingViewModel"}],"url":"\/documentation\/cshub_test\/pairingviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/QRCodeScannerViewModel":{"role":"symbol","title":"QRCodeScannerViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QRCodeScannerViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRCodeScannerViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QRCodeScannerViewModel"}],"url":"\/documentation\/cshub_test\/qrcodescannerviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ClDocApplication":{"role":"symbol","title":"ClDocApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClDocApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ClDocApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClDocApplication"}],"url":"\/documentation\/cshub_test\/cldocapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SplashViewModel":{"role":"symbol","title":"SplashViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SplashViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SplashViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SplashViewModel"}],"url":"\/documentation\/cshub_test\/splashviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OneStepper":{"role":"symbol","title":"OneStepper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OneStepper"}],"abstract":[{"type":"text","text":"A Simple Stepper that has one goal: emit a single Step once initialized"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OneStepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OneStepper"}],"url":"\/documentation\/cshub_test\/onestepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OnlineMeetingsViewModel":{"role":"symbol","title":"OnlineMeetingsViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnlineMeetingsViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnlineMeetingsViewModel"}],"url":"\/documentation\/cshub_test\/onlinemeetingsviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DashboardViewModel":{"role":"symbol","title":"DashboardViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DashboardViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DashboardViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DashboardViewModel"}],"url":"\/documentation\/cshub_test\/dashboardviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CLDocCoordinator":{"role":"symbol","title":"CLDocCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLDocCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CLDocCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CLDocCoordinator"}],"url":"\/documentation\/cshub_test\/cldoccoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SafariApplication":{"role":"symbol","title":"SafariApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SafariApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SafariApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SafariApplication"}],"url":"\/documentation\/cshub_test\/safariapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CCIViewModel":{"role":"symbol","title":"CCIViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCIViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CCIViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CCIViewModel"}],"url":"\/documentation\/cshub_test\/cciviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultAppStepper":{"role":"symbol","title":"DefaultAppStepper","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAppStepper"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultAppStepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultAppStepper"}],"url":"\/documentation\/cshub_test\/defaultappstepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplication":{"role":"symbol","title":"WebApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplication"}],"url":"\/documentation\/cshub_test\/webapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/KycApplication":{"role":"symbol","title":"KycApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KycApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KycApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KycApplication"}],"url":"\/documentation\/cshub_test\/kycapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OCRViewModel":{"role":"symbol","title":"OCRViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OCRViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OCRViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OCRViewModel"}],"url":"\/documentation\/cshub_test\/ocrviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PairingApplication":{"role":"symbol","title":"PairingApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PairingApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PairingApplication"}],"url":"\/documentation\/cshub_test\/pairingapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PushAlertViewModel":{"role":"symbol","title":"PushAlertViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushAlertViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PushAlertViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushAlertViewModel"}],"url":"\/documentation\/cshub_test\/pushalertviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppStepper":{"role":"symbol","title":"AppStepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppStepper"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppStepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppStepper"}],"url":"\/documentation\/cshub_test\/appstepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentManagementViewModel":{"role":"symbol","title":"AppointmentManagementViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentManagementViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentManagementViewModel"}],"url":"\/documentation\/cshub_test\/appointmentmanagementviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppStateViewModel":{"role":"symbol","title":"AppStateViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppStateViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppStateViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppStateViewModel"}],"url":"\/documentation\/cshub_test\/appstateviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/KycViewModel":{"role":"symbol","title":"KycViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KycViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/KycViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KycViewModel"}],"url":"\/documentation\/cshub_test\/kycviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LegalizationCoordinator":{"role":"symbol","title":"LegalizationCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegalizationCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegalizationCoordinator"}],"url":"\/documentation\/cshub_test\/legalizationcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/LegalizationApplication":{"role":"symbol","title":"LegalizationApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LegalizationApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/LegalizationApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LegalizationApplication"}],"url":"\/documentation\/cshub_test\/legalizationapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SafariApplicationFlow/SFSafariDelegate":{"role":"symbol","title":"SafariApplicationFlow.SFSafariDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSafariDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SafariApplicationFlow\/SFSafariDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SFSafariDelegate"}],"url":"\/documentation\/cshub_test\/safariapplicationflow\/sfsafaridelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IdentificationCoordinator":{"role":"symbol","title":"IdentificationCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentificationCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IdentificationCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentificationCoordinator"}],"url":"\/documentation\/cshub_test\/identificationcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDContactInfoViewController":{"role":"symbol","title":"ZenIDContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidcontactinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper/steps":{"role":"symbol","title":"steps","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"steps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Step","preciseIdentifier":"s:10CSHub_Test4StepP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper\/steps","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/stepper\/steps"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PencilAlertViewModel":{"role":"symbol","title":"PencilAlertViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PencilAlertViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PencilAlertViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PencilAlertViewModel"}],"url":"\/documentation\/cshub_test\/pencilalertviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BiometrySignViewModel":{"role":"symbol","title":"BiometrySignViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BiometrySignViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BiometrySignViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BiometrySignViewModel"}],"url":"\/documentation\/cshub_test\/biometrysignviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentApplication":{"role":"symbol","title":"AppointmentApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentApplication"}],"url":"\/documentation\/cshub_test\/appointmentapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel":{"role":"symbol","title":"WebApplicationViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationViewModel"}],"url":"\/documentation\/cshub_test\/webapplicationviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/OnlineMeetingsApplication":{"role":"symbol","title":"OnlineMeetingsApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OnlineMeetingsApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/OnlineMeetingsApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OnlineMeetingsApplication"}],"url":"\/documentation\/cshub_test\/onlinemeetingsapplication"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserApplication":{"role":"symbol","title":"WebBrowserApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserApplication"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebBrowserApplication"}],"url":"\/documentation\/cshub_test\/webbrowserapplication"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/title","value":"FaqViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/fragments","value":[{"kind":"identifier","text":"FaqViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel\/title","value":"WebBrowserViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel\/fragments","value":[{"kind":"identifier","text":"WebBrowserViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/title","value":"WebApplicationViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/fragments","value":[{"kind":"identifier","text":"WebApplicationViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}