{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapGestureRecognizer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/tapgesturerecognizer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/tapgesturerecognizer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UITapGestureRecognizer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/TapGestureRecognizer","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/TapGestureRecognizer\/indexPath"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapGestureRecognizer"}],"title":"TapGestureRecognizer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)TapGestureRecognizer","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"TapGestureRecognizer"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/TapGestureRecognizer/initWithTarget:action:":{"role":"symbol","title":"initWithTarget:action:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTarget:action:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/TapGestureRecognizer\/initWithTarget:action:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTarget:action:"}],"url":"\/documentation\/cshub_test\/tapgesturerecognizer\/initwithtarget:action:"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/TapGestureRecognizer/indexPath":{"role":"symbol","title":"indexPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/TapGestureRecognizer\/indexPath","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/tapgesturerecognizer\/indexpath"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(cs)UITapGestureRecognizer":{"type":"unresolvable","title":"UITapGestureRecognizer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UITapGestureRecognizer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/TapGestureRecognizer":{"role":"symbol","title":"TapGestureRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapGestureRecognizer"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/TapGestureRecognizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TapGestureRecognizer"}],"url":"\/documentation\/cshub_test\/tapgesturerecognizer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TapGestureRecognizer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TapGestureRecognizer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TapGestureRecognizer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/TapGestureRecognizer\/initWithTarget:action:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UITapGestureRecognizer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapGestureRecognizer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1TapGestureRecognizer\/title","value":"TapGestureRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1TapGestureRecognizer\/fragments","value":[{"kind":"identifier","text":"TapGestureRecognizer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}