{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Task"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"is obtained after PushNotification is received and handled in"},{"type":"text","text":" "},{"type":"text","text":"↳ "},{"type":"codeVoice","code":"AppDelegate"},{"type":"text","text":" "},{"type":"codeVoice","code":"messaging(_ messaging:, didReceive remoteMessage:)"},{"type":"text","text":" "},{"type":"text","text":"↳ "},{"type":"codeVoice","code":"PushNotificationHelpers"},{"type":"text","text":" "},{"type":"codeVoice","code":"evaluatePushNotification(userInfo:)"},{"type":"text","text":" "},{"type":"codeVoice","code":"ensureUserSessionIsValid(_ closure:)"},{"type":"text","text":" "},{"type":"text","text":"↳ "},{"type":"codeVoice","code":"UserSession"},{"type":"text","text":" "},{"type":"codeVoice","code":"pushNewTasks(withFilteredId taskId:)"},{"type":"text","text":" "},{"type":"codeVoice","code":"loadAnotherTasks(success:, failure:)"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/task"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/task"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper12BaseMappableP","doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper8MappableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/Se","doc:\/\/cz.csas.app.cshub.test\/SE","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"object received from NOBE representing action for the consultant"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Task"}],"title":"Task","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)Task","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"Task"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(coder:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(from:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(map:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(taskId:appId:timeCreated:sourceSystemId:taskName:params:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/appId","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/debugDescription","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/params","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/sourceSystemId","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/taskId","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/taskName","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/timeCreated","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/timeCreatedDate"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/encode(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/mapping(map:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/taskAppName()"]},{"title":"Type Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/e2eTask(for:callback:pairs:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/BaseMappable-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/Mappable-Implementations"],"generated":true}],"references":{"doc://cz.csas.app.cshub.test/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/cz.csas.app.cshub.test\/Se"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/12ObjectMapper8MappableP":{"type":"unresolvable","title":"ObjectMapper.Mappable","identifier":"doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper8MappableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/encode(with:)":{"role":"symbol","title":"encode(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/encode(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"url":"\/documentation\/cshub_test\/task\/encode(with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task":{"role":"symbol","title":"Task","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Task"}],"abstract":[{"type":"text","text":"object received from NOBE representing action for the consultant"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Task"}],"url":"\/documentation\/cshub_test\/task"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/Mappable-Implementations":{"role":"collectionGroup","title":"Mappable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/Mappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/task\/mappable-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/e2eTask(for:callback:pairs:)":{"role":"symbol","title":"e2eTask(for:callback:pairs:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"e2eTask"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pairs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Pair","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Pair"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Future","preciseIdentifier":"s:10CSHub_Test6FutureC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Task","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Task"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"creates mock "},{"type":"codeVoice","code":"Task"},{"type":"text","text":" from query data obtained via intercepted "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"codeVoice","code":"cshub:\/\/"},{"type":"text","text":" scheme during E2E process nextFlow handling"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/e2eTask(for:callback:pairs:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/e2etask(for:callback:pairs:)"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/taskId":{"role":"symbol","title":"taskId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/taskId","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/taskid"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/mapping(map:)":{"role":"symbol","title":"mapping(map:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapping"},{"kind":"text","text":"("},{"kind":"externalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:12ObjectMapper3MapC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/mapping(map:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/mapping(map:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/sourceSystemId":{"role":"symbol","title":"sourceSystemId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceSystemId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/sourceSystemId","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/sourcesystemid"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/appId":{"role":"symbol","title":"appId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/appId","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/appid"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/12ObjectMapper12BaseMappableP":{"type":"unresolvable","title":"ObjectMapper.BaseMappable","identifier":"doc:\/\/cz.csas.app.cshub.test\/12ObjectMapper12BaseMappableP"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/timeCreated":{"role":"symbol","title":"timeCreated","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeCreated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/timeCreated","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/timecreated"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/params":{"role":"symbol","title":"params","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Pair","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Pair"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/params","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/params"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/init(taskId:appId:timeCreated:sourceSystemId:taskName:params:)":{"role":"symbol","title":"init(taskId:appId:timeCreated:sourceSystemId:taskName:params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"taskId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeCreated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceSystemId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"taskName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Pair","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)Pair"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(taskId:appId:timeCreated:sourceSystemId:taskName:params:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/init(taskid:appid:timecreated:sourcesystemid:taskname:params:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/taskName":{"role":"symbol","title":"taskName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/taskName","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/taskname"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/debugDescription":{"role":"symbol","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/debugDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"url":"\/documentation\/cshub_test\/task\/debugdescription"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/init(map:)":{"role":"symbol","title":"init(map:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Map","preciseIdentifier":"s:12ObjectMapper3MapC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(map:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/init(map:)"},"doc://cz.csas.app.cshub.test/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SE"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/taskAppName()":{"role":"symbol","title":"taskAppName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskAppName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/taskAppName()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/taskappname()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/task\/init(coder:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/timeCreatedDate":{"role":"symbol","title":"timeCreatedDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeCreatedDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/timeCreatedDate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/timecreateddate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/BaseMappable-Implementations":{"role":"collectionGroup","title":"BaseMappable Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/BaseMappable-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/task\/basemappable-implementations"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Task/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/task\/init(from:)"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Task"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Task"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Task"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/debugDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/encode(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Task\/init(coder:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Task"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task~1encode(with:)\/title","value":"encodeWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task~1encode(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task\/title","value":"Task"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task\/fragments","value":[{"kind":"identifier","text":"Task"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Task~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}