{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIReusable"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/uireusable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CalendarTableRow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowLandscapeCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RoundedCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ShadowCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCountryCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenResultCell"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/UIReusable","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/UIReusable\/reuseIdentifier"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIReusable"}],"title":"UIReusable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test10UIReusableP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"UIReusable"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenResultCell":{"role":"symbol","title":"ZenResultCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenResultCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenResultCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenResultCell"}],"url":"\/documentation\/cshub_test\/zenresultcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/UIReusable/reuseIdentifier":{"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"reuseIdentifier","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"variable that allows further code simplifications"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/UIReusable\/reuseIdentifier","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/uireusable\/reuseidentifier"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressCell":{"role":"symbol","title":"ZenIDAddressCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDAddressCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDAddressCell"}],"url":"\/documentation\/cshub_test\/zenidaddresscell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ShadowCell":{"role":"symbol","title":"ShadowCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShadowCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ShadowCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShadowCell"}],"url":"\/documentation\/cshub_test\/shadowcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/UIReusable":{"role":"symbol","title":"UIReusable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIReusable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/UIReusable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIReusable"}],"url":"\/documentation\/cshub_test\/uireusable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCountryCell":{"role":"symbol","title":"ZenIDCountryCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCountryCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCountryCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCountryCell"}],"url":"\/documentation\/cshub_test\/zenidcountrycell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementRowCell":{"role":"symbol","title":"ManagementRowCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementRowCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementRowCell"}],"url":"\/documentation\/cshub_test\/managementrowcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentCell":{"role":"symbol","title":"ZenIDDocumentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDDocumentCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDDocumentCell"}],"url":"\/documentation\/cshub_test\/zeniddocumentcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RoundedCell":{"role":"symbol","title":"RoundedCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundedCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RoundedCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoundedCell"}],"url":"\/documentation\/cshub_test\/roundedcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CalendarTableRow":{"role":"symbol","title":"CalendarTableRow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalendarTableRow"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CalendarTableRow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalendarTableRow"}],"url":"\/documentation\/cshub_test\/calendartablerow"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentItemCell":{"role":"symbol","title":"DocumentItemCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentItemCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentItemCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentItemCell"}],"url":"\/documentation\/cshub_test\/documentitemcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingCell":{"role":"symbol","title":"EmailCollectingCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCollectingCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmailCollectingCell"}],"url":"\/documentation\/cshub_test\/emailcollectingcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ManagementRowLandscapeCell":{"role":"symbol","title":"ManagementRowLandscapeCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ManagementRowLandscapeCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ManagementRowLandscapeCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ManagementRowLandscapeCell"}],"url":"\/documentation\/cshub_test\/managementrowlandscapecell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqCell":{"role":"symbol","title":"FaqCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqCell"}],"url":"\/documentation\/cshub_test\/faqcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenResultCell\/title","value":"ZenResultCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenResultCell\/fragments","value":[{"kind":"identifier","text":"ZenResultCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressCell\/title","value":"ZenIDAddressCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressCell\/fragments","value":[{"kind":"identifier","text":"ZenIDAddressCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ShadowCell\/title","value":"ShadowCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ShadowCell\/fragments","value":[{"kind":"identifier","text":"ShadowCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCountryCell\/title","value":"ZenIDCountryCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCountryCell\/fragments","value":[{"kind":"identifier","text":"ZenIDCountryCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowCell\/title","value":"ManagementRowCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowCell\/fragments","value":[{"kind":"identifier","text":"ManagementRowCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentCell\/title","value":"ZenIDDocumentCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentCell\/fragments","value":[{"kind":"identifier","text":"ZenIDDocumentCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RoundedCell\/title","value":"RoundedCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RoundedCell\/fragments","value":[{"kind":"identifier","text":"RoundedCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CalendarTableRow\/title","value":"CalendarTableRow"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CalendarTableRow\/fragments","value":[{"kind":"identifier","text":"CalendarTableRow"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentItemCell\/title","value":"DocumentItemCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DocumentItemCell\/fragments","value":[{"kind":"identifier","text":"DocumentItemCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingCell\/title","value":"EmailCollectingCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingCell\/fragments","value":[{"kind":"identifier","text":"EmailCollectingCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowLandscapeCell\/title","value":"ManagementRowLandscapeCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ManagementRowLandscapeCell\/fragments","value":[{"kind":"identifier","text":"ManagementRowLandscapeCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/title","value":"FaqCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/fragments","value":[{"kind":"identifier","text":"FaqCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}