{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewControllerStyleable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/viewcontrollerstyleable"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BusyViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentConfirmationController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsListController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ErrorViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRScannerViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCameraViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable\/setDefaultAttributesFor(style:for:)-8vm9g","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable\/setDefaultAttributesFor(style:for:title:)-6rmnv","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable\/setStyle()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewControllerStyleable"}],"title":"ViewControllerStyleable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test23ViewControllerStyleableP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"ViewControllerStyleable"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCameraViewController":{"role":"symbol","title":"ZenIDCameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCameraViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCameraViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCameraViewController"}],"url":"\/documentation\/cshub_test\/zenidcameraviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ViewControllerStyleable":{"role":"symbol","title":"ViewControllerStyleable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewControllerStyleable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewControllerStyleable"}],"url":"\/documentation\/cshub_test\/viewcontrollerstyleable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingController":{"role":"symbol","title":"EmailCollectingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCollectingController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmailCollectingController"}],"url":"\/documentation\/cshub_test\/emailcollectingcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/QRScannerViewController":{"role":"symbol","title":"QRScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QRScannerViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/QRScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QRScannerViewController"}],"url":"\/documentation\/cshub_test\/qrscannerviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignatureOverlayViewController":{"role":"symbol","title":"SignatureOverlayViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignatureOverlayViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignatureOverlayViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignatureOverlayViewController"}],"url":"\/documentation\/cshub_test\/signatureoverlayviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BusyViewController":{"role":"symbol","title":"BusyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusyViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BusyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BusyViewController"}],"url":"\/documentation\/cshub_test\/busyviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentViewController":{"role":"symbol","title":"AppointmentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentViewController"}],"url":"\/documentation\/cshub_test\/appointmentviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/SignpadViewController":{"role":"symbol","title":"SignpadViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignpadViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/SignpadViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignpadViewController"}],"url":"\/documentation\/cshub_test\/signpadviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ErrorViewController":{"role":"symbol","title":"ErrorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ErrorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorViewController"}],"url":"\/documentation\/cshub_test\/errorviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BioSignatureOverlayController":{"role":"symbol","title":"BioSignatureOverlayController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BioSignatureOverlayController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BioSignatureOverlayController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BioSignatureOverlayController"}],"url":"\/documentation\/cshub_test\/biosignatureoverlaycontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ViewControllerStyleable/setStyle()":{"role":"symbol","title":"setStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStyle"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable\/setStyle()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/viewcontrollerstyleable\/setstyle()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ViewControllerStyleable/setDefaultAttributesFor(style:for:)-8vm9g":{"defaultImplementations":1,"role":"symbol","title":"setDefaultAttributesFor(style:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultAttributesFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppStyle","preciseIdentifier":"s:10CSHub_Test8AppStyleV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable\/setDefaultAttributesFor(style:for:)-8vm9g","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/viewcontrollerstyleable\/setdefaultattributesfor(style:for:)-8vm9g"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppointmentManagementViewController":{"role":"symbol","title":"AppointmentManagementViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppointmentManagementViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppointmentManagementViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppointmentManagementViewController"}],"url":"\/documentation\/cshub_test\/appointmentmanagementviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDContactInfoViewController":{"role":"symbol","title":"ZenIDContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDContactInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidcontactinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BaseInfoViewController":{"role":"symbol","title":"BaseInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BaseInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseInfoViewController"}],"url":"\/documentation\/cshub_test\/baseinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentsListController":{"role":"symbol","title":"DocumentsListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentsListController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentsListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentsListController"}],"url":"\/documentation\/cshub_test\/documentslistcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListController":{"role":"symbol","title":"E2eDocumentListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentListController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentListController"}],"url":"\/documentation\/cshub_test\/e2edocumentlistcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DocumentConfirmationController":{"role":"symbol","title":"DocumentConfirmationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentConfirmationController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DocumentConfirmationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentConfirmationController"}],"url":"\/documentation\/cshub_test\/documentconfirmationcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryViewController":{"role":"symbol","title":"ZenIDSummaryViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSummaryViewController"}],"url":"\/documentation\/cshub_test\/zenidsummaryviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ViewControllerStyleable/setDefaultAttributesFor(style:for:title:)-6rmnv":{"defaultImplementations":1,"role":"symbol","title":"setDefaultAttributesFor(style:for:title:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultAttributesFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppStyle","preciseIdentifier":"s:10CSHub_Test8AppStyleV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ViewControllerStyleable\/setDefaultAttributesFor(style:for:title:)-6rmnv","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/viewcontrollerstyleable\/setdefaultattributesfor(style:for:title:)-6rmnv"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoViewController":{"role":"symbol","title":"ZenIDPersonalInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoViewController"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfoviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqViewController":{"role":"symbol","title":"FaqViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqViewController"}],"url":"\/documentation\/cshub_test\/faqviewcontroller"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDViewController":{"role":"symbol","title":"ZenIDViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDViewController"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDViewController"}],"url":"\/documentation\/cshub_test\/zenidviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCameraViewController\/title","value":"ZenIDCameraViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCameraViewController\/fragments","value":[{"kind":"identifier","text":"ZenIDCameraViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BusyViewController\/title","value":"BusyViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BusyViewController\/fragments","value":[{"kind":"identifier","text":"BusyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ErrorViewController\/title","value":"ErrorViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ErrorViewController\/fragments","value":[{"kind":"identifier","text":"ErrorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BaseInfoViewController\/title","value":"BaseInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BaseInfoViewController\/fragments","value":[{"kind":"identifier","text":"BaseInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/title","value":"FaqViewController"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqViewController\/fragments","value":[{"kind":"identifier","text":"FaqViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}