{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationCoordinator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webapplicationcoordinator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/webapplicationcoordinator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKNavigationDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKUIDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/init(universalLinkCatcher:appLinkTypeResolver:appliationURL:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/isLoading","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/onClose","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/onRefreshTasks","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:createWebViewWith:for:windowFeatures:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:decidePolicyFor:decisionHandler:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didFail:withError:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didFinish:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didStartProvisionalNavigation:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationCoordinator"}],"title":"WebApplicationCoordinator","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)WebApplicationCoordinator","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"WebApplicationCoordinator"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/webView(_:didStartProvisionalNavigation:)":{"role":"symbol","title":"webView(_:didStartProvisionalNavigation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartProvisionalNavigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didStartProvisionalNavigation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:didstartprovisionalnavigation:)"},"doc://cz.csas.app.cshub.test/objc(pl)WKNavigationDelegate":{"type":"unresolvable","title":"WebKit.WKNavigationDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKNavigationDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/webView(_:didFail:withError:)":{"role":"symbol","title":"webView(_:didFail:withError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didFail:withError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:didfail:witherror:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/webView(_:createWebViewWith:for:windowFeatures:)":{"role":"symbol","title":"webView(_:createWebViewWith:for:windowFeatures:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createWebViewWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebViewConfiguration","preciseIdentifier":"c:objc(cs)WKWebViewConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"windowFeatures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWindowFeatures","preciseIdentifier":"c:objc(cs)WKWindowFeatures"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:createWebViewWith:for:windowFeatures:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:createwebviewwith:for:windowfeatures:)"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/init(universalLinkCatcher:appLinkTypeResolver:appliationURL:)":{"role":"symbol","title":"init(universalLinkCatcher:appLinkTypeResolver:appliationURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"universalLinkCatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UniversalLinkCatcher","preciseIdentifier":"s:10CSHub_Test20UniversalLinkCatcherP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appLinkTypeResolver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AppLinkTypeResolver","preciseIdentifier":"s:10CSHub_Test19AppLinkTypeResolverP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appliationURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/init(universalLinkCatcher:appLinkTypeResolver:appliationURL:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationcoordinator\/init(universallinkcatcher:applinktyperesolver:appliationurl:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/url","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationcoordinator\/url"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/webView(_:decidePolicyFor:decisionHandler:)":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:decidePolicyFor:decisionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:decidepolicyfor:decisionhandler:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewCoordinator":{"role":"symbol","title":"WebViewCoordinator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebViewCoordinator"}],"url":"\/documentation\/cshub_test\/webviewcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator":{"role":"symbol","title":"WebApplicationCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationCoordinator"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/onClose":{"role":"symbol","title":"onClose","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/onClose","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationcoordinator\/onclose"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/webView(_:didFinish:)":{"role":"symbol","title":"webView(_:didFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didFinish:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator\/webview(_:didfinish:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/objc(pl)WKUIDelegate":{"type":"unresolvable","title":"WebKit.WKUIDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKUIDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/onRefreshTasks":{"role":"symbol","title":"onRefreshTasks","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRefreshTasks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/onRefreshTasks","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationcoordinator\/onrefreshtasks"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CurrentValueSubject","preciseIdentifier":"s:7Combine19CurrentValueSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/isLoading","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationcoordinator\/isloading"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WebApplicationCoordinator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WebApplicationCoordinator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WebApplicationCoordinator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:createWebViewWith:for:windowFeatures:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:decidePolicyFor:decisionHandler:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didFail:withError:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didFinish:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator\/webView(_:didStartProvisionalNavigation:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationCoordinator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:didStartProvisionalNavigation:)\/title","value":"webView:didStartProvisionalNavigation:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:didStartProvisionalNavigation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:didFail:withError:)\/title","value":"webView:didFailNavigation:withError:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:didFail:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:createWebViewWith:for:windowFeatures:)\/title","value":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:createWebViewWith:for:windowFeatures:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:createWebViewWithConfiguration:forNavigationAction:windowFeatures:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:decidePolicyFor:decisionHandler:)\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator\/title","value":"WebApplicationCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator\/fragments","value":[{"kind":"identifier","text":"WebApplicationCoordinator"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:didFinish:)\/title","value":"webView:didFinishNavigation:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator~1webView(_:didFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFinishNavigation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}