{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webapplicationviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/webapplicationviewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/7Combine16ObservableObjectP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/init(url:repository:taskManager:webView:coordinator:onHomeAction:onBackAction:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/canGoBack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/canGoForward","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/coordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/isLoading","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/loadingProgress","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/onBack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/onHome","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/repository","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/returnUrl","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/showNavBar","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/steps","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/taskManager","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/title","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/url","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/urlComposer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/webView"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/backwardNavigation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/forwardNavigation()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/observeValue(forKeyPath:of:change:context:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/ObservableObject-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/Stepper-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"}],"title":"WebApplicationViewModel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)WebApplicationViewModel","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"WebApplicationViewModel"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/webView":{"role":"symbol","title":"webView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/webView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/webview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/observeValue(forKeyPath:of:change:context:)":{"role":"symbol","title":"observeValue(forKeyPath:of:change:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/observeValue(forKeyPath:of:change:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"url":"\/documentation\/cshub_test\/webapplicationviewmodel\/observevalue(forkeypath:of:change:context:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/init(url:repository:taskManager:webView:coordinator:onHomeAction:onBackAction:)":{"role":"symbol","title":"init(url:repository:taskManager:webView:coordinator:onHomeAction:onBackAction:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"repository"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebApplicationRepository","preciseIdentifier":"s:10CSHub_Test24WebApplicationRepositoryP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"taskManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TaskManager","preciseIdentifier":"s:10CSHub_Test11TaskManagerP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebViewCoordinator","preciseIdentifier":"s:10CSHub_Test18WebViewCoordinatorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onHomeAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionType","preciseIdentifier":"s:10CSHub_Test10ActionTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onBackAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActionType","preciseIdentifier":"s:10CSHub_Test10ActionTypeO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/init(url:repository:taskManager:webView:coordinator:onHomeAction:onBackAction:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/init(url:repository:taskmanager:webview:coordinator:onhomeaction:onbackaction:)"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/onHome":{"role":"symbol","title":"onHome","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onHome"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/onHome","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/onhome"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/url","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/url"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/Stepper-Implementations":{"role":"collectionGroup","title":"Stepper Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/Stepper-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/stepper-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/forwardNavigation()":{"role":"symbol","title":"forwardNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"forwardNavigation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/forwardNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/forwardnavigation()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/canGoForward":{"role":"symbol","title":"canGoForward","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canGoForward"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/canGoForward","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/cangoforward"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/steps":{"role":"symbol","title":"steps","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"steps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Step","preciseIdentifier":"s:10CSHub_Test4StepP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/steps","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/steps"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/coordinator":{"role":"symbol","title":"coordinator","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebViewCoordinator","preciseIdentifier":"s:10CSHub_Test18WebViewCoordinatorP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/coordinator","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/coordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/returnUrl":{"role":"symbol","title":"returnUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/returnUrl","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/returnurl"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/onBack":{"role":"symbol","title":"onBack","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/onBack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/onback"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel":{"role":"symbol","title":"WebViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebViewModel"}],"url":"\/documentation\/cshub_test\/webviewmodel"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/showNavBar":{"role":"symbol","title":"showNavBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNavBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/showNavBar","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/shownavbar"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/urlComposer":{"role":"symbol","title":"urlComposer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlComposer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLComposer","preciseIdentifier":"s:10CSHub_Test11URLComposerP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/urlComposer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/urlcomposer"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/ObservableObject-Implementations":{"role":"collectionGroup","title":"ObservableObject Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/ObservableObject-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/observableobject-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/loadingProgress":{"role":"symbol","title":"loadingProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/loadingProgress","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/loadingprogress"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/taskManager":{"role":"symbol","title":"taskManager","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"taskManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TaskManager","preciseIdentifier":"s:10CSHub_Test11TaskManagerP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/taskManager","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/taskmanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/title","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/title"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/repository":{"role":"symbol","title":"repository","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"repository"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebApplicationRepository","preciseIdentifier":"s:10CSHub_Test24WebApplicationRepositoryP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/repository","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/repository"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper":{"role":"symbol","title":"Stepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stepper"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Stepper"}],"url":"\/documentation\/cshub_test\/stepper"},"doc://cz.csas.app.cshub.test/7Combine16ObservableObjectP":{"type":"unresolvable","title":"Combine.ObservableObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/7Combine16ObservableObjectP"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/isLoading","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/isloading"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel":{"role":"symbol","title":"WebApplicationViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationViewModel"}],"url":"\/documentation\/cshub_test\/webapplicationviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/canGoBack":{"role":"symbol","title":"canGoBack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canGoBack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/canGoBack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/cangoback"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/backwardNavigation()":{"role":"symbol","title":"backwardNavigation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backwardNavigation"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/backwardNavigation()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webapplicationviewmodel\/backwardnavigation()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WebApplicationViewModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WebApplicationViewModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WebApplicationViewModel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/observeValue(forKeyPath:of:change:context:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel~1observeValue(forKeyPath:of:change:context:)\/title","value":"observeValueForKeyPath:ofObject:change:context:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel~1observeValue(forKeyPath:of:change:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/title","value":"WebApplicationViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/fragments","value":[{"kind":"identifier","text":"WebApplicationViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}