{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserViewModel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webbrowserviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/webbrowserviewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/7Combine16ObservableObjectP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/init(url:urlBuilder:webView:coordinator:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/canGoBack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/canGoForward","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/coordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/inputText","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/isLoading","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/loadingProgress","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onCommit","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onGoBack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onGoForward","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onHome","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onHomeUrl","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/steps","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/url","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/webView"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/observeValue(forKeyPath:of:change:context:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/ObservableObject-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/Stepper-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserViewModel"}],"title":"WebBrowserViewModel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)WebBrowserViewModel","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"WebBrowserViewModel"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/onGoBack":{"role":"symbol","title":"onGoBack","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGoBack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onGoBack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/ongoback"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/onGoForward":{"role":"symbol","title":"onGoForward","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGoForward"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onGoForward","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/ongoforward"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/loadingProgress":{"role":"symbol","title":"loadingProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/loadingProgress","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/loadingprogress"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel":{"role":"symbol","title":"WebViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebViewModel"}],"url":"\/documentation\/cshub_test\/webviewmodel"},"doc://cz.csas.app.cshub.test/7Combine16ObservableObjectP":{"type":"unresolvable","title":"Combine.ObservableObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/7Combine16ObservableObjectP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/webView":{"role":"symbol","title":"webView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/webView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/webview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/canGoBack":{"role":"symbol","title":"canGoBack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canGoBack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/canGoBack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/cangoback"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/url","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/url"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/inputText":{"role":"symbol","title":"inputText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/inputText","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/inputtext"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/onHome":{"role":"symbol","title":"onHome","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onHome"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onHome","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/onhome"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/steps":{"role":"symbol","title":"steps","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"steps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Step","preciseIdentifier":"s:10CSHub_Test4StepP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/steps","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/steps"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/ObservableObject-Implementations":{"role":"collectionGroup","title":"ObservableObject Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/ObservableObject-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/observableobject-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Stepper":{"role":"symbol","title":"Stepper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Stepper"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Stepper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Stepper"}],"url":"\/documentation\/cshub_test\/stepper"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/Stepper-Implementations":{"role":"collectionGroup","title":"Stepper Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/Stepper-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/stepper-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/observeValue(forKeyPath:of:change:context:)":{"role":"symbol","title":"observeValue(forKeyPath:of:change:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/observeValue(forKeyPath:of:change:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"url":"\/documentation\/cshub_test\/webbrowserviewmodel\/observevalue(forkeypath:of:change:context:)"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/isLoading","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/isloading"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/coordinator":{"role":"symbol","title":"coordinator","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebViewCoordinator","preciseIdentifier":"s:10CSHub_Test18WebViewCoordinatorP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/coordinator","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/coordinator"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel":{"role":"symbol","title":"WebBrowserViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebBrowserViewModel"}],"url":"\/documentation\/cshub_test\/webbrowserviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/canGoForward":{"role":"symbol","title":"canGoForward","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canGoForward"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/canGoForward","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/cangoforward"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/onCommit":{"role":"symbol","title":"onCommit","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCommit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onCommit","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/oncommit"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/onHomeUrl":{"role":"symbol","title":"onHomeUrl","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onHomeUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/onHomeUrl","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/onhomeurl"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel/init(url:urlBuilder:webView:coordinator:)":{"role":"symbol","title":"init(url:urlBuilder:webView:coordinator:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"urlBuilder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebBrowserUrlBuilder","preciseIdentifier":"s:10CSHub_Test20WebBrowserUrlBuilderP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebViewCoordinator","preciseIdentifier":"s:10CSHub_Test18WebViewCoordinatorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/init(url:urlBuilder:webView:coordinator:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/webbrowserviewmodel\/init(url:urlbuilder:webview:coordinator:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WebBrowserViewModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WebBrowserViewModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WebBrowserViewModel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel\/observeValue(forKeyPath:of:change:context:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserViewModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel~1observeValue(forKeyPath:of:change:context:)\/title","value":"observeValueForKeyPath:ofObject:change:context:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel~1observeValue(forKeyPath:of:change:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel\/title","value":"WebBrowserViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel\/fragments","value":[{"kind":"identifier","text":"WebBrowserViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}