{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ObservableObject","preciseIdentifier":"s:7Combine16ObservableObjectP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webviewmodel"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/7Combine16ObservableObjectP"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/canGoBack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/canGoForward","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/coordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/isLoading","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/loadingProgress","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/url","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/webView"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewModel"}],"title":"WebViewModel","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test12WebViewModelP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"WebViewModel"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebBrowserViewModel":{"role":"symbol","title":"WebBrowserViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebBrowserViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebBrowserViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebBrowserViewModel"}],"url":"\/documentation\/cshub_test\/webbrowserviewmodel"},"doc://cz.csas.app.cshub.test/7Combine16ObservableObjectP":{"type":"unresolvable","title":"Combine.ObservableObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/7Combine16ObservableObjectP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/canGoForward":{"role":"symbol","title":"canGoForward","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canGoForward"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/canGoForward","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/cangoforward"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel":{"role":"symbol","title":"WebApplicationViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationViewModel"}],"url":"\/documentation\/cshub_test\/webapplicationviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel":{"role":"symbol","title":"WebViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebViewModel"}],"url":"\/documentation\/cshub_test\/webviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/loadingProgress":{"role":"symbol","title":"loadingProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/loadingProgress","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/loadingprogress"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/canGoBack":{"role":"symbol","title":"canGoBack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canGoBack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/canGoBack","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/cangoback"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/url","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/url"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/isLoading","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/isloading"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/coordinator":{"role":"symbol","title":"coordinator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebViewCoordinator","preciseIdentifier":"s:10CSHub_Test18WebViewCoordinatorP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/coordinator","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/coordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewModel/webView":{"role":"symbol","title":"webView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewModel\/webView","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewmodel\/webview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel\/title","value":"WebBrowserViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebBrowserViewModel\/fragments","value":[{"kind":"identifier","text":"WebBrowserViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/title","value":"WebApplicationViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/fragments","value":[{"kind":"identifier","text":"WebApplicationViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}