{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewCoordinator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WKNavigationDelegate","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WKUIDelegate","preciseIdentifier":"c:objc(pl)WKUIDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webviewcoordinator"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKNavigationDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKUIDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultWebViewCoordinator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/isLoading","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/onClose-8egtc","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/onRefreshTasks-88075","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/url"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewCoordinator"}],"title":"WebViewCoordinator","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:10CSHub_Test18WebViewCoordinatorP","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"WebViewCoordinator"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewCoordinator":{"role":"symbol","title":"WebViewCoordinator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebViewCoordinator"}],"url":"\/documentation\/cshub_test\/webviewcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewCoordinator/onClose-8egtc":{"defaultImplementations":1,"role":"symbol","title":"onClose","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/onClose-8egtc","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewcoordinator\/onclose-8egtc"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewCoordinator/isLoading":{"role":"symbol","title":"isLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CurrentValueSubject","preciseIdentifier":"s:7Combine19CurrentValueSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/isLoading","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewcoordinator\/isloading"},"doc://cz.csas.app.cshub.test/objc(pl)WKNavigationDelegate":{"type":"unresolvable","title":"WebKit.WKNavigationDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKNavigationDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)WKUIDelegate":{"type":"unresolvable","title":"WebKit.WKUIDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)WKUIDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewCoordinator/onRefreshTasks-88075":{"defaultImplementations":1,"role":"symbol","title":"onRefreshTasks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRefreshTasks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/onRefreshTasks-88075","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewcoordinator\/onrefreshtasks-88075"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebViewCoordinator/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebViewCoordinator\/url","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cshub_test\/webviewcoordinator\/url"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationCoordinator":{"role":"symbol","title":"WebApplicationCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationCoordinator"}],"url":"\/documentation\/cshub_test\/webapplicationcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultWebViewCoordinator":{"role":"symbol","title":"DefaultWebViewCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultWebViewCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultWebViewCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultWebViewCoordinator"}],"url":"\/documentation\/cshub_test\/defaultwebviewcoordinator"},"doc://cz.csas.app.cshub.test/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator\/title","value":"WebApplicationCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationCoordinator\/fragments","value":[{"kind":"identifier","text":"WebApplicationCoordinator"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultWebViewCoordinator\/title","value":"DefaultWebViewCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultWebViewCoordinator\/fragments","value":[{"kind":"identifier","text":"DefaultWebViewCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}