{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenButton"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zenbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/init(coder:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/backgroundColor","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/cornerRadius","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/intrinsicContentSize","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/isHighlighted","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/outline","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/outlineColor","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/size","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/textColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/setupView()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenButton"}],"title":"ZenButton","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)ZenButton","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"ZenButton"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/outlineColor":{"role":"symbol","title":"outlineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outlineColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/outlineColor","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenbutton\/outlinecolor"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/cornerRadius":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/cornerRadius","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenbutton\/cornerradius"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/objc(cs)UIButton":{"type":"unresolvable","title":"UIButton","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIButton"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/cshub_test\/zenbutton\/intrinsiccontentsize"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/setupView()":{"role":"symbol","title":"setupView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupView"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/setupView()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenbutton\/setupview()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/textColor":{"role":"symbol","title":"textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/textColor","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenbutton\/textcolor"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/zenbutton\/init(frame:)"},"doc://cz.csas.app.cshub.test/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/outline":{"role":"symbol","title":"outline","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/outline","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenbutton\/outline"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/backgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"url":"\/documentation\/cshub_test\/zenbutton\/backgroundcolor"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/size","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenbutton\/size"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/zenbutton\/init(coder:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton":{"role":"symbol","title":"ZenButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenButton"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenButton"}],"url":"\/documentation\/cshub_test\/zenbutton"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenButton/isHighlighted":{"role":"symbol","title":"isHighlighted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/isHighlighted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"url":"\/documentation\/cshub_test\/zenbutton\/ishighlighted"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIContextMenuInteractionDelegate"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZenButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZenButton"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZenButton"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/backgroundColor","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/intrinsicContentSize","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/isHighlighted"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/init(coder:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenButton\/init(frame:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenButton"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton\/title","value":"ZenButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton\/fragments","value":[{"kind":"identifier","text":"ZenButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1isHighlighted\/title","value":"highlighted"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenButton~1isHighlighted\/fragments","value":[{"kind":"identifier","text":"highlighted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}