{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidaddressselectionpopupview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zenidaddressselectionpopupview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDataSource","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDelegate","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/action","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/addressType","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/buttonConfirm","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/cellData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/contentView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/footerView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/headerView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/parentDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/selectedAddress","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/addAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/backAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/confirmAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/dismissAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/searchAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/setupBindings(with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/UITableViewDataSource-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/UITableViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}],"title":"ZenIDAddressSelectionPopupView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)ZenIDAddressSelectionPopupView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/buttonConfirm":{"role":"symbol","title":"buttonConfirm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonConfirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/buttonConfirm","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/buttonconfirm"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/confirmAction()":{"role":"symbol","title":"confirmAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/confirmAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmAction"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/confirmaction()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/cellData":{"role":"symbol","title":"cellData","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<["},{"kind":"typeIdentifier","text":"AddressCellData","preciseIdentifier":"s:10CSHub_Test15AddressCellDataV"},{"kind":"text","text":"]>"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/cellData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/celldata"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDataSource"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/parentDelegate":{"role":"symbol","title":"parentDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDAddressPopupDelegate","preciseIdentifier":"s:10CSHub_Test25ZenIDAddressPopupDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/parentDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/parentdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/setupBindings(with:)":{"role":"symbol","title":"setupBindings(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CDMViewModel","preciseIdentifier":"s:10CSHub_Test12CDMViewModelC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Disposable","preciseIdentifier":"s:13ReactiveSwift10DisposableP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/setupBindings(with:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/setupbindings(with:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/UITableViewDelegate-Implementations":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/UITableViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/uitableviewdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/backAction()":{"role":"symbol","title":"backAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/backAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backAction"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/backaction()"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/addAction()":{"role":"symbol","title":"addAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/addAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addAction"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/addaction()"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/headerView":{"role":"symbol","title":"headerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/headerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/headerview"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView":{"role":"symbol","title":"ZenIDAddressSelectionPopupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/tableView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/tableview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/contentView":{"role":"symbol","title":"contentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/contentView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/contentview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/dismissAction()":{"role":"symbol","title":"dismissAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/dismissAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissAction"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/dismissaction()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/searchAction()":{"role":"symbol","title":"searchAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/searchAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchAction"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/searchaction()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/selectedAddress":{"role":"symbol","title":"selectedAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/selectedAddress","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/selectedaddress"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/initwithcoder:"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/addressType":{"role":"symbol","title":"addressType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CDMAddressType","preciseIdentifier":"s:10CSHub_Test14CDMAddressTypeO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/addressType","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/addresstype"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/footerView":{"role":"symbol","title":"footerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/footerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/footerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/init()"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIScrollViewDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITableViewDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/uitableviewdatasource-implementations"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/initwithframe:"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDAddressSelectionPopupView/action":{"role":"symbol","title":"action","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/action","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidaddressselectionpopupview\/action"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZenIDAddressSelectionPopupView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/addAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/backAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/confirmAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/dismissAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/init()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/initWithCoder:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/initWithFrame:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/searchAction()"]},{"title":"Default Implementations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/UITableViewDataSource-Implementations","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDAddressSelectionPopupView\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1confirmAction()\/title","value":"confirmAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1confirmAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1backAction()\/title","value":"backAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1backAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1addAction()\/title","value":"addAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1addAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView\/title","value":"ZenIDAddressSelectionPopupView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView\/fragments","value":[{"kind":"identifier","text":"ZenIDAddressSelectionPopupView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1dismissAction()\/title","value":"dismissAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1dismissAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1searchAction()\/title","value":"searchAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1searchAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDAddressSelectionPopupView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}