{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDRightView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidrightview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zenidrightview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/init(delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/badMinerView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/bottomView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/cameraButton","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/dateOfBirthTextField","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/defaultView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/expiredDocument","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extended","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearchArrow","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearchAttributedString","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearchLabel","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/nameTextField","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/nationalIDNumberTextField","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/parentDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/separator","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/showExtendedSearchView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/surnameTextField"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedLayout()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearch()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/layout()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/setupBindings(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/unextendedLayout()"]},{"title":"Enumerations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/Actions"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDRightView"}],"title":"ZenIDRightView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)ZenIDRightView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"ZenIDRightView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/Actions":{"role":"symbol","title":"ZenIDRightView.Actions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Actions"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/Actions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Actions"}],"url":"\/documentation\/cshub_test\/zenidrightview\/actions"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extendedLayout()":{"role":"symbol","title":"extendedLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedLayout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedLayout()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extendedlayout()"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/parentDelegate":{"role":"symbol","title":"parentDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDViewController","preciseIdentifier":"s:10CSHub_Test19ZenIDViewControllerC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/parentDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/parentdelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/showExtendedSearchView":{"role":"symbol","title":"showExtendedSearchView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showExtendedSearchView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/showExtendedSearchView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/showextendedsearchview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/nameTextField":{"role":"symbol","title":"nameTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/nameTextField","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/nametextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extendedView":{"role":"symbol","title":"extendedView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extendedview"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/expiredDocument":{"role":"symbol","title":"expiredDocument","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiredDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/expiredDocument","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/expireddocument"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/layout()":{"role":"symbol","title":"layout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/layout()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/layout()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView":{"role":"symbol","title":"ZenIDRightView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDRightView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDRightView"}],"url":"\/documentation\/cshub_test\/zenidrightview"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/setupBindings(with:)":{"role":"symbol","title":"setupBindings(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDViewModel","preciseIdentifier":"s:10CSHub_Test14ZenIDViewModelC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Disposable","preciseIdentifier":"s:13ReactiveSwift10DisposableP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/setupBindings(with:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/setupbindings(with:)"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extendedSearchLabel":{"role":"symbol","title":"extendedSearchLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedSearchLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearchLabel","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extendedsearchlabel"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extendedSearch()":{"role":"symbol","title":"extendedSearch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedSearch"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearch()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extendedsearch()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDViewController","preciseIdentifier":"s:10CSHub_Test19ZenIDViewControllerC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/init(delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/init(delegate:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/cameraButton":{"role":"symbol","title":"cameraButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraButton"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/cameraButton","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/camerabutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extendedSearchAttributedString":{"role":"symbol","title":"extendedSearchAttributedString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedSearchAttributedString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearchAttributedString","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extendedsearchattributedstring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extendedSearchArrow":{"role":"symbol","title":"extendedSearchArrow","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedSearchArrow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extendedSearchArrow","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extendedsearcharrow"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/badMinerView":{"role":"symbol","title":"badMinerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badMinerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/badMinerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/badminerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/extended":{"role":"symbol","title":"extended","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extended"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/extended","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/extended"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/unextendedLayout()":{"role":"symbol","title":"unextendedLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unextendedLayout"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/unextendedLayout()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/unextendedlayout()"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/separator":{"role":"symbol","title":"separator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"separator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/separator","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/separator"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/nationalIDNumberTextField":{"role":"symbol","title":"nationalIDNumberTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationalIDNumberTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/nationalIDNumberTextField","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/nationalidnumbertextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/bottomView":{"role":"symbol","title":"bottomView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDBottomRightView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDBottomRightView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/bottomView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/bottomview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/surnameTextField":{"role":"symbol","title":"surnameTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"surnameTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/surnameTextField","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/surnametextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/defaultView":{"role":"symbol","title":"defaultView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/defaultView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/defaultview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/dateOfBirthTextField":{"role":"symbol","title":"dateOfBirthTextField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirthTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BorderedTextField","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/dateOfBirthTextField","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/dateofbirthtextfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZenIDRightView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZenIDRightView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZenIDRightView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDRightView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDRightView\/title","value":"ZenIDRightView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDRightView\/fragments","value":[{"kind":"identifier","text":"ZenIDRightView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}