{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","interfaceLanguage":"swift"},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/Item","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldData"]},{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/init(data:txtFieldDelegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/action","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/address","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthDate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthNumber","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthPlace","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/citizenshipCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentHeaderView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentItems","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentItemsNeedReviews","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentItemsStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/firstInit","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/footerView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/fullName","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/gender","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/headerAuto","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/headerView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/horizontalSpacing","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardIssuer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardIssuerCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardNumber","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardType","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardValidUntil","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/parentDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/personalItems","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/personalItemsNeedReviews","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/personalItemsStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/selectionView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAllSelectView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showNeededSelectView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showingAll","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/taxResidencyCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/textFieldDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/textFields","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/useAddressActionProperty","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/verticalSpacing"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/addRecordedValueView(_:_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/addressSearchButtonTap()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/continueAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/layoutConstraints()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/layoutItemView(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/makeBasicItem(category:type:withPickerArrow:title:data:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/render()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/setDocumentItemsNeedReviews()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/setPersonalItemsNeedReviews()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/setupBindings(with:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAll()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showReviews()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/twoColumnLine(_:_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/ItemCategory","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldType"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"title":"ZenIDPersonalInfoCardView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)ZenIDPersonalInfoCardView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/twoColumnLine(_:_:)":{"role":"symbol","title":"twoColumnLine(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"twoColumnLine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/twoColumnLine(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/twocolumnline(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/verticalSpacing":{"role":"symbol","title":"verticalSpacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/verticalSpacing","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/verticalspacing"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/firstInit":{"role":"symbol","title":"firstInit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstInit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/firstInit","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/firstinit"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/birthCountry":{"role":"symbol","title":"birthCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/birthcountry"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/addressSearchButtonTap()":{"role":"symbol","title":"addressSearchButtonTap()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressSearchButtonTap"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/addressSearchButtonTap()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addressSearchButtonTap"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/addresssearchbuttontap()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/birthPlace":{"role":"symbol","title":"birthPlace","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthPlace","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/birthplace"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/headerAuto":{"role":"symbol","title":"headerAuto","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerAuto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/headerAuto","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/headerauto"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/address":{"role":"symbol","title":"address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/address","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/address"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showingAll":{"role":"symbol","title":"showingAll","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showingAll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showingAll","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showingall"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/render()":{"role":"symbol","title":"render()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/render()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/render()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/setDocumentItemsNeedReviews()":{"role":"symbol","title":"setDocumentItemsNeedReviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDocumentItemsNeedReviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/setDocumentItemsNeedReviews()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/setdocumentitemsneedreviews()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/personalItems":{"role":"symbol","title":"personalItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ZenIDPersonalInfoCardView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDPersonalInfoCardView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/personalItems","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/personalitems"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/documentItemsStack":{"role":"symbol","title":"documentItemsStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentItemsStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentItemsStack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/documentitemsstack"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/addRecordedValueView(_:_:_:)":{"role":"symbol","title":"addRecordedValueView(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRecordedValueView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> (view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", button"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/addRecordedValueView(_:_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/addrecordedvalueview(_:_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/setupBindings(with:)":{"role":"symbol","title":"setupBindings(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CDMViewModel","preciseIdentifier":"s:10CSHub_Test12CDMViewModelC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Disposable","preciseIdentifier":"s:13ReactiveSwift10DisposableP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/setupBindings(with:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/setupbindings(with:)"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/textFieldDelegate":{"role":"symbol","title":"textFieldDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextFieldDelegate","preciseIdentifier":"c:objc(pl)UITextFieldDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/textFieldDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfielddelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/gender":{"role":"symbol","title":"gender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/gender","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/gender"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showAll()":{"role":"symbol","title":"showAll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAll"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAll()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showAll"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showall()"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/ItemCategory":{"role":"symbol","title":"ZenIDPersonalInfoCardView.ItemCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ItemCategory"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/ItemCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ItemCategory"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/itemcategory"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/continueAction()":{"role":"symbol","title":"continueAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/continueAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"continueAction"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/continueaction()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/initwithcoder:"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/idCardIssuerCountry":{"role":"symbol","title":"idCardIssuerCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardIssuerCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardIssuerCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/idcardissuercountry"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/documentItems":{"role":"symbol","title":"documentItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ZenIDPersonalInfoCardView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDPersonalInfoCardView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentItems","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/documentitems"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/Item":{"role":"symbol","title":"ZenIDPersonalInfoCardView.Item","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/Item","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Item"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/item"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/parentDelegate":{"role":"symbol","title":"parentDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDPersonalInfoViewController","preciseIdentifier":"s:10CSHub_Test31ZenIDPersonalInfoViewControllerC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/parentDelegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/parentdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/fullName":{"role":"symbol","title":"fullName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/fullName","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/fullname"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/idCardType":{"role":"symbol","title":"idCardType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardType","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/idcardtype"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/initwithframe:"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/headerView":{"role":"symbol","title":"headerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/headerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/headerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/idCardValidUntil":{"role":"symbol","title":"idCardValidUntil","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardValidUntil"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardValidUntil","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/idcardvaliduntil"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/layoutItemView(_:_:)":{"role":"symbol","title":"layoutItemView(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutItemView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/layoutItemView(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/layoutitemview(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/footerView":{"role":"symbol","title":"footerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/footerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/footerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/selectionView":{"role":"symbol","title":"selectionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/selectionView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/selectionview"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showReviews()":{"role":"symbol","title":"showReviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showReviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showReviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showReviews"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showreviews()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/personalItemsNeedReviews":{"role":"symbol","title":"personalItemsNeedReviews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalItemsNeedReviews"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/personalItemsNeedReviews","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/personalitemsneedreviews"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/personalItemsStack":{"role":"symbol","title":"personalItemsStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalItemsStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/personalItemsStack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/personalitemsstack"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/birthNumber":{"role":"symbol","title":"birthNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthNumber","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/birthnumber"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/TextFieldData":{"role":"symbol","title":"ZenIDPersonalInfoCardView.TextFieldData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldData"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldData"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfielddata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/birthDate":{"role":"symbol","title":"birthDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/birthDate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/birthdate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView":{"role":"symbol","title":"ZenIDPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/layoutConstraints()":{"role":"symbol","title":"layoutConstraints()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutConstraints"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/layoutConstraints()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/layoutconstraints()"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/action":{"role":"symbol","title":"action","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/action","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/action"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/taxResidencyCountry":{"role":"symbol","title":"taxResidencyCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taxResidencyCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/taxResidencyCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/taxresidencycountry"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/idCardNumber":{"role":"symbol","title":"idCardNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardNumber","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/idcardnumber"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/idCardIssuer":{"role":"symbol","title":"idCardIssuer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardIssuer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/idCardIssuer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/idcardissuer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/documentHeaderView":{"role":"symbol","title":"documentHeaderView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentHeaderView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/documentheaderview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/init(data:txtFieldDelegate:)":{"role":"symbol","title":"init(data:txtFieldDelegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"TextFieldData","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC13TextFieldDataV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"txtFieldDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextFieldDelegate","preciseIdentifier":"c:objc(pl)UITextFieldDelegate"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/init(data:txtFieldDelegate:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/init(data:txtfielddelegate:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/documentItemsNeedReviews":{"role":"symbol","title":"documentItemsNeedReviews","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentItemsNeedReviews"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/documentItemsNeedReviews","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/documentitemsneedreviews"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/setPersonalItemsNeedReviews()":{"role":"symbol","title":"setPersonalItemsNeedReviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPersonalItemsNeedReviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/setPersonalItemsNeedReviews()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/setpersonalitemsneedreviews()"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/textFields":{"role":"symbol","title":"textFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"TextFieldData","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC13TextFieldDataV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/textFields","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfields"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showNeededSelectView":{"role":"symbol","title":"showNeededSelectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNeededSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showNeededSelectView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showneededselectview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/makeBasicItem(category:type:withPickerArrow:title:data:)":{"role":"symbol","title":"makeBasicItem(category:type:withPickerArrow:title:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeBasicItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ItemCategory","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC12ItemCategoryO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextFieldType","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC13TextFieldTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPickerArrow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextFieldData","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC13TextFieldDataV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/makeBasicItem(category:type:withPickerArrow:title:data:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/makebasicitem(category:type:withpickerarrow:title:data:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/citizenshipCountry":{"role":"symbol","title":"citizenshipCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citizenshipCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Item","preciseIdentifier":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC4ItemV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/citizenshipCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/citizenshipcountry"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/TextFieldType":{"role":"symbol","title":"ZenIDPersonalInfoCardView.TextFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextFieldType"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/TextFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TextFieldType"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/textfieldtype"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/horizontalSpacing":{"role":"symbol","title":"horizontalSpacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/horizontalSpacing","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/horizontalspacing"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showAllSelectView":{"role":"symbol","title":"showAllSelectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAllSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAllSelectView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showallselectview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/useAddressActionProperty":{"role":"symbol","title":"useAddressActionProperty","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"useAddressActionProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/useAddressActionProperty","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/useaddressactionproperty"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZenIDPersonalInfoCardView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/addressSearchButtonTap()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/continueAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/initWithCoder:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/initWithFrame:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAll()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showReviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1addressSearchButtonTap()\/title","value":"addressSearchButtonTap"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1addressSearchButtonTap()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addressSearchButtonTap"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1showAll()\/title","value":"showAll"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1showAll()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAll"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1continueAction()\/title","value":"continueAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1continueAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continueAction"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1showReviews()\/title","value":"showReviews"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1showReviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showReviews"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/title","value":"ZenIDPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}