{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryCardView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidsummarycardview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zenidsummarycardview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject","doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate","doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP","doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP","doc:\/\/cz.csas.app.cshub.test\/SQ","doc:\/\/cz.csas.app.cshub.test\/SH","doc:\/\/cz.csas.app.cshub.test\/s8SendableP","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment","doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/init(personalData:productData:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/action","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/address","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/anotherEmail","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/anotherPhone","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/backToStep","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthDate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthName","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthNumber","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthPlace","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/citizenshipCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/contactAddress","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/contactsHeaderView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/contactsStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/documentHeaderView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/documentStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/email","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/footerView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/gender","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardIssuer","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardIssuerCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardNumber","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardType","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardValidUntil","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/name","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/personalData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/personalHeaderView","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/personalStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/phone","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/productData","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/productsStack","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/taxResidencyCountry","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/verticalSpacing"]},{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/continueAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/editContacts()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/editInfo()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/layoutConstraints()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/makeLine(title:value:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/makeProductHeader(_:_:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/render()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/setupBindings(with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryCardView"}],"title":"ZenIDSummaryCardView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CSHub_Test@objc(cs)ZenIDSummaryCardView","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"ZenIDSummaryCardView"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/citizenshipCountry":{"role":"symbol","title":"citizenshipCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citizenshipCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/citizenshipCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/citizenshipcountry"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/editInfo()":{"role":"symbol","title":"editInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editInfo"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/editInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editInfo"}],"url":"\/documentation\/cshub_test\/zenidsummarycardview\/editinfo()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Runnable":{"role":"symbol","title":"Runnable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Runnable"}],"abstract":[{"type":"text","text":"Kotlin-like scope function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Runnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Runnable"}],"url":"\/documentation\/cshub_test\/runnable"},"doc://cz.csas.app.cshub.test/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAccessibilityIdentification"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/personalHeaderView":{"role":"symbol","title":"personalHeaderView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/personalHeaderView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/personalheaderview"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearanceContainer"},"doc://cz.csas.app.cshub.test/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UILargeContentViewerItem"},"doc://cz.csas.app.cshub.test/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)CALayerDelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/layoutConstraints()":{"role":"symbol","title":"layoutConstraints()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutConstraints"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/layoutConstraints()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/layoutconstraints()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/gender":{"role":"symbol","title":"gender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/gender","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/gender"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/birthDate":{"role":"symbol","title":"birthDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthDate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/birthdate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cshub_test\/zenidsummarycardview\/initwithframe:"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView":{"role":"symbol","title":"ZenIDSummaryCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSummaryCardView"}],"url":"\/documentation\/cshub_test\/zenidsummarycardview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/verticalSpacing":{"role":"symbol","title":"verticalSpacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalSpacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/verticalSpacing","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/verticalspacing"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/email":{"role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/email","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/email"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/anotherEmail":{"role":"symbol","title":"anotherEmail","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anotherEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/anotherEmail","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/anotheremail"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/phone":{"role":"symbol","title":"phone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/phone","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/phone"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/address":{"role":"symbol","title":"address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/address","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/address"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/init(personalData:productData:)":{"role":"symbol","title":"init(personalData:productData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"personalData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : (text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, isChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?)], "},{"kind":"externalParam","text":"productData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ProductsSummaryData","preciseIdentifier":"s:10CSHub_Test19ProductsSummaryDataV"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/init(personalData:productData:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/init(personaldata:productdata:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/render()":{"role":"symbol","title":"render()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"render"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/render()","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/render()"},"doc://cz.csas.app.cshub.test/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPasteConfigurationSupporting"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/birthName":{"role":"symbol","title":"birthName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthName","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/birthname"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/taxResidencyCountry":{"role":"symbol","title":"taxResidencyCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taxResidencyCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/taxResidencyCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/taxresidencycountry"},"doc://cz.csas.app.cshub.test/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s23CustomStringConvertibleP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/productsStack":{"role":"symbol","title":"productsStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"productsStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/productsStack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/productsstack"},"doc://cz.csas.app.cshub.test/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cz.csas.app.cshub.test\/s7CVarArgP"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/backToStep":{"role":"symbol","title":"backToStep","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backToStep"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/backToStep","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/backtostep"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/contactsHeaderView":{"role":"symbol","title":"contactsHeaderView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactsHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/contactsHeaderView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/contactsheaderview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/personalStack":{"role":"symbol","title":"personalStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/personalStack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/personalstack"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/makeProductHeader(_:_:)":{"role":"symbol","title":"makeProductHeader(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeProductHeader"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/makeProductHeader(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/makeproductheader(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/name","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/name"},"doc://cz.csas.app.cshub.test/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SQ"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/idCardType":{"role":"symbol","title":"idCardType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardType","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/idcardtype"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/documentStack":{"role":"symbol","title":"documentStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/documentStack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/documentstack"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/birthPlace":{"role":"symbol","title":"birthPlace","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthPlace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthPlace","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/birthplace"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/idCardNumber":{"role":"symbol","title":"idCardNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardNumber","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/idcardnumber"},"doc://cz.csas.app.cshub.test/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSObject"},"doc://cz.csas.app.cshub.test/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cz.csas.app.cshub.test\/s28CustomDebugStringConvertibleP"},"doc://cz.csas.app.cshub.test/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIUserActivityRestoring"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItem"},"doc://cz.csas.app.cshub.test/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIDynamicItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/editContacts()":{"role":"symbol","title":"editContacts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editContacts"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/editContacts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editContacts"}],"url":"\/documentation\/cshub_test\/zenidsummarycardview\/editcontacts()"},"doc://cz.csas.app.cshub.test/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/productData":{"role":"symbol","title":"productData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"productData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ProductsSummaryData","preciseIdentifier":"s:10CSHub_Test19ProductsSummaryDataV"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/productData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/productdata"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/birthCountry":{"role":"symbol","title":"birthCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/birthcountry"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/contactsStack":{"role":"symbol","title":"contactsStack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactsStack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/contactsStack","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/contactsstack"},"doc://cz.csas.app.cshub.test/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIResponderStandardEditActions"},"doc://cz.csas.app.cshub.test/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)NSCoding"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/idCardIssuerCountry":{"role":"symbol","title":"idCardIssuerCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardIssuerCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardIssuerCountry","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/idcardissuercountry"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/makeLine(title:value:)":{"role":"symbol","title":"makeLine(title:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeLine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": (text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, isChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?)?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/makeLine(title:value:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/makeline(title:value:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/setupBindings(with:)":{"role":"symbol","title":"setupBindings(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupBindings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CDMViewModel","preciseIdentifier":"s:10CSHub_Test12CDMViewModelC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Disposable","preciseIdentifier":"s:13ReactiveSwift10DisposableP"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/setupBindings(with:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/setupbindings(with:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/anotherPhone":{"role":"symbol","title":"anotherPhone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anotherPhone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/anotherPhone","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/anotherphone"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/idCardValidUntil":{"role":"symbol","title":"idCardValidUntil","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardValidUntil"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardValidUntil","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/idcardvaliduntil"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Configurable":{"role":"symbol","title":"Configurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configurable"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Configurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configurable"}],"url":"\/documentation\/cshub_test\/configurable"},"doc://cz.csas.app.cshub.test/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIAppearance"},"doc://cz.csas.app.cshub.test/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/contactAddress":{"role":"symbol","title":"contactAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/contactAddress","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/contactaddress"},"doc://cz.csas.app.cshub.test/13ReactiveSwift0A18ExtensionsProviderP":{"type":"unresolvable","title":"ReactiveSwift.ReactiveExtensionsProvider","identifier":"doc:\/\/cz.csas.app.cshub.test\/13ReactiveSwift0A18ExtensionsProviderP"},"doc://cz.csas.app.cshub.test/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cz.csas.app.cshub.test\/s8SendableP"},"doc://cz.csas.app.cshub.test/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cz.csas.app.cshub.test\/SH"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/birthNumber":{"role":"symbol","title":"birthNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/birthNumber","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/birthnumber"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/footerView":{"role":"symbol","title":"footerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/footerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/footerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/action":{"role":"symbol","title":"action","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MutableProperty","preciseIdentifier":"s:13ReactiveSwift15MutablePropertyC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/action","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/action"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/personalData":{"role":"symbol","title":"personalData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : (text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, isChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?)]"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/personalData","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/personaldata"},"doc://cz.csas.app.cshub.test/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UICoordinateSpace"},"doc://cz.csas.app.cshub.test/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UITraitEnvironment"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cshub_test\/zenidsummarycardview\/initwithcoder:"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/idCardIssuer":{"role":"symbol","title":"idCardIssuer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardIssuer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/idCardIssuer","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/idcardissuer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/documentHeaderView":{"role":"symbol","title":"documentHeaderView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/documentHeaderView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidsummarycardview\/documentheaderview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSummaryCardView/continueAction()":{"role":"symbol","title":"continueAction()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueAction"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/continueAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"continueAction"}],"url":"\/documentation\/cshub_test\/zenidsummarycardview\/continueaction()"},"doc://cz.csas.app.cshub.test/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cz.csas.app.cshub.test/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cz.csas.app.cshub.test\/objc(pl)UIFocusItemContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZenIDSummaryCardView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZenIDSummaryCardView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZenIDSummaryCardView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/continueAction()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/editContacts()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/editInfo()","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/initWithCoder:","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSummaryCardView\/initWithFrame:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cz.csas.app.cshub.test\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSummaryCardView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView~1editInfo()\/title","value":"editInfo"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView~1editInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView\/title","value":"ZenIDSummaryCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView\/fragments","value":[{"kind":"identifier","text":"ZenIDSummaryCardView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView~1editContacts()\/title","value":"editContacts"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView~1editContacts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editContacts"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView~1continueAction()\/title","value":"continueAction"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSummaryCardView~1continueAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continueAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}