{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentSelectionPopupView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDDocumentSelectionPopupView","text":"ZenIDDocumentSelectionPopupView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zeniddocumentcell\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDDocumentSelectionPopupView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDDocumentSelectionPopupView"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test17ZenIDDocumentCellC8delegateAA0cD18SelectionPopupViewCSgvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentCell/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDDocumentSelectionPopupView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDDocumentSelectionPopupView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zeniddocumentcell\/delegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentCell":{"role":"symbol","title":"ZenIDDocumentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDDocumentCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDDocumentCell"}],"url":"\/documentation\/cshub_test\/zeniddocumentcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDDocumentSelectionPopupView":{"role":"symbol","title":"ZenIDDocumentSelectionPopupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDDocumentSelectionPopupView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDDocumentSelectionPopupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDDocumentSelectionPopupView"}],"url":"\/documentation\/cshub_test\/zeniddocumentselectionpopupview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentCell\/title","value":"ZenIDDocumentCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentCell\/fragments","value":[{"kind":"identifier","text":"ZenIDDocumentCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentSelectionPopupView\/title","value":"ZenIDDocumentSelectionPopupView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDDocumentSelectionPopupView\/fragments","value":[{"kind":"identifier","text":"ZenIDDocumentSelectionPopupView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}