{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"model"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CustomDataSource","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CustomDataSource","text":"CustomDataSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/e2ecollection\/model"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eCollection\/model","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"model"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomDataSource","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CustomDataSource"}],"title":"model","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test13E2eCollectionC5modelAA16CustomDataSourceCvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eCollection"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CustomDataSource":{"role":"symbol","title":"CustomDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDataSource"}],"abstract":[{"type":"text","text":"generic object conforming to "},{"type":"codeVoice","code":"UITableViewDataSource"},{"type":"text","text":" used to populate the "},{"type":"codeVoice","code":"UITableViews"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CustomDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomDataSource"}],"url":"\/documentation\/cshub_test\/customdatasource"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eCollection/model":{"role":"symbol","title":"model","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"model"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CustomDataSource","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CustomDataSource"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eCollection\/model","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/e2ecollection\/model"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eCollection":{"role":"symbol","title":"E2eCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eCollection"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eCollection"}],"url":"\/documentation\/cshub_test\/e2ecollection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CustomDataSource\/title","value":"CustomDataSource"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CustomDataSource\/fragments","value":[{"kind":"identifier","text":"CustomDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eCollection\/title","value":"E2eCollection"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eCollection\/fragments","value":[{"kind":"identifier","text":"E2eCollection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}