{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView","text":"ZenIDCardFooterView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview\/footerview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/footerView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"title":"footerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC06footerG0AA0c12IDCardFooterG0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCardFooterView":{"role":"symbol","title":"ZenIDCardFooterView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCardFooterView"}],"url":"\/documentation\/cshub_test\/zenidcardfooterview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView":{"role":"symbol","title":"ZenIDPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/footerView":{"role":"symbol","title":"footerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/footerView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/footerview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardFooterView\/title","value":"ZenIDCardFooterView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardFooterView\/fragments","value":[{"kind":"identifier","text":"ZenIDCardFooterView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/title","value":"ZenIDPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}