{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAllSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView","text":"ZenIDSelectableView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview\/showallselectview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAllSelectView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAllSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"title":"showAllSelectView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test25ZenIDPersonalInfoCardViewC013showAllSelectG0AA0c12IDSelectableG0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showAllSelectView":{"role":"symbol","title":"showAllSelectView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAllSelectView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDSelectableView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAllSelectView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showallselectview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDSelectableView":{"role":"symbol","title":"ZenIDSelectableView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDSelectableView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDSelectableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDSelectableView"}],"url":"\/documentation\/cshub_test\/zenidselectableview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView":{"role":"symbol","title":"ZenIDPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSelectableView\/title","value":"ZenIDSelectableView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDSelectableView\/fragments","value":[{"kind":"identifier","text":"ZenIDSelectableView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/title","value":"ZenIDPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}