{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAll"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview\/showall()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/zenidpersonalinfocardview\/showall()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAll()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAll"},{"kind":"text","text":"()"}],"title":"showAll()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)ZenIDPersonalInfoCardView(im)showAll","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"showAll"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView/showAll()":{"role":"symbol","title":"showAll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAll"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView\/showAll()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showAll"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview\/showall()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPersonalInfoCardView":{"role":"symbol","title":"ZenIDPersonalInfoCardView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPersonalInfoCardView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}],"url":"\/documentation\/cshub_test\/zenidpersonalinfocardview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showAll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAll"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showAll"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1showAll()\/title","value":"showAll"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView~1showAll()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAll"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/title","value":"ZenIDPersonalInfoCardView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPersonalInfoCardView\/fragments","value":[{"kind":"identifier","text":"ZenIDPersonalInfoCardView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}