{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ibBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DigiCameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)DigiCameraButton","text":"DigiCameraButton"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"task is used to specifically init the style of the CommonWebViewController"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/e2edocumentlistview\/ibbtn"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView\/ibBtn","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"button allowing to append document from other internet bank web"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ibBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigiCameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)DigiCameraButton"}],"title":"ibBtn","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test19E2eDocumentListViewC5ibBtnAA16DigiCameraButtonCvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DigiCameraButton":{"role":"symbol","title":"DigiCameraButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigiCameraButton"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DigiCameraButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigiCameraButton"}],"url":"\/documentation\/cshub_test\/digicamerabutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListView/ibBtn":{"role":"symbol","title":"ibBtn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ibBtn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigiCameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)DigiCameraButton"}],"abstract":[{"type":"text","text":"button allowing to append document from other internet bank web"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView\/ibBtn","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/e2edocumentlistview\/ibbtn"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListView":{"role":"symbol","title":"E2eDocumentListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentListView"}],"abstract":[{"type":"text","text":"wrapper view responsible for the shadow drawing"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentListView"}],"url":"\/documentation\/cshub_test\/e2edocumentlistview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DigiCameraButton\/title","value":"DigiCameraButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DigiCameraButton\/fragments","value":[{"kind":"identifier","text":"DigiCameraButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentListView\/title","value":"E2eDocumentListView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentListView\/fragments","value":[{"kind":"identifier","text":"E2eDocumentListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}