{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/e2edocumentlistview\/layoutifneeded()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/e2edocumentlistview\/layoutifneeded()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView\/layoutIfNeeded()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":"()"}],"title":"layoutIfNeeded()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)E2eDocumentListView(im)layoutIfNeeded","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"layoutIfNeeded"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListView/layoutIfNeeded()":{"role":"symbol","title":"layoutIfNeeded()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView\/layoutIfNeeded()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutIfNeeded"}],"url":"\/documentation\/cshub_test\/e2edocumentlistview\/layoutifneeded()"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/E2eDocumentListView":{"role":"symbol","title":"E2eDocumentListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"E2eDocumentListView"}],"abstract":[{"type":"text","text":"wrapper view responsible for the shadow drawing"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/E2eDocumentListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"E2eDocumentListView"}],"url":"\/documentation\/cshub_test\/e2edocumentlistview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"layoutIfNeeded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutIfNeeded"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentListView~1layoutIfNeeded()\/title","value":"layoutIfNeeded"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentListView~1layoutIfNeeded()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutIfNeeded"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentListView\/title","value":"E2eDocumentListView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1E2eDocumentListView\/fragments","value":[{"kind":"identifier","text":"E2eDocumentListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}