{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/emailcollectingtableviewdatasourcedelegate\/textfieldshouldreturn(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/emailcollectingtableviewdatasourcedelegate\/textfieldshouldreturn(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingTableViewDataSourceDelegate\/textFieldShouldReturn(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextFieldDelegate.textFieldShouldReturn(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"textFieldShouldReturn(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)EmailCollectingTableViewDataSourceDelegate(im)textFieldShouldReturn:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingTableViewDataSourceDelegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingTableViewDataSourceDelegate/textFieldShouldReturn(_:)":{"role":"symbol","title":"textFieldShouldReturn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingTableViewDataSourceDelegate\/textFieldShouldReturn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}],"url":"\/documentation\/cshub_test\/emailcollectingtableviewdatasourcedelegate\/textfieldshouldreturn(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/EmailCollectingTableViewDataSourceDelegate":{"role":"symbol","title":"EmailCollectingTableViewDataSourceDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCollectingTableViewDataSourceDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/EmailCollectingTableViewDataSourceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmailCollectingTableViewDataSourceDelegate"}],"url":"\/documentation\/cshub_test\/emailcollectingtableviewdatasourcedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textFieldShouldReturn:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldReturn:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"textFieldShouldReturn:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"textField"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingTableViewDataSourceDelegate~1textFieldShouldReturn(_:)\/title","value":"textFieldShouldReturn:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingTableViewDataSourceDelegate~1textFieldShouldReturn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldReturn:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingTableViewDataSourceDelegate\/title","value":"EmailCollectingTableViewDataSourceDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1EmailCollectingTableViewDataSourceDelegate\/fragments","value":[{"kind":"identifier","text":"EmailCollectingTableViewDataSourceDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}