{"variants":[{"paths":["\/documentation\/cshub_test\/camerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/camerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureOutput(_:didOutput:from:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession/captureOutput(_:didOutput:from:)":{"role":"symbol","title":"captureOutput(_:didOutput:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"sets the "},{"type":"codeVoice","code":"imageProperty"},{"type":"text","text":" value that fires reactive observer in "},{"type":"codeVoice","code":"CameraViewController"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureOutput(_:didOutput:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}],"url":"\/documentation\/cshub_test\/camerasession\/captureoutput(_:didoutput:from:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraSession":{"role":"symbol","title":"CameraSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraSession"}],"abstract":[{"type":"text","text":"setups a video camera session"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"url":"\/documentation\/cshub_test\/camerasession"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraSession\/captureOutput(_:didOutput:from:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession~1captureOutput(_:didOutput:from:)\/title","value":"captureOutput:didOutputSampleBuffer:fromConnection:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession~1captureOutput(_:didOutput:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession\/title","value":"CameraSession"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraSession\/fragments","value":[{"kind":"identifier","text":"CameraSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}