{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCryptData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ipkimobilemanager\/preparecryptdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ipkimobilemanager\/preparecryptdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/prepareCryptData()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Prepare crypto data like RSA keypair for later certificate request generation."},{"type":"text","text":" "},{"type":"text","text":"This function opens a new background thread with a low priority and finishes immediately,"},{"type":"text","text":" "},{"type":"text","text":"the mobile application can continue its operation."},{"type":"text","text":" "},{"type":"text","text":"This function call should be preceded at least by a call specifying the key size - i.e."},{"type":"text","text":" "},{"type":"text","text":"clearPolicyParams"},{"type":"text","text":" and "},{"type":"text","text":"addPolicyParam(“keySize”, 2048)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCryptData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"prepareCryptData()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)IPKIMobileManager(im)prepareCryptData","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"prepareCryptData"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager":{"role":"symbol","title":"IPKIMobileManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPKIMobileManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IPKIMobileManager"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/prepareCryptData()":{"role":"symbol","title":"prepareCryptData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareCryptData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Prepare crypto data like RSA keypair for later certificate request generation."},{"type":"text","text":" "},{"type":"text","text":"This function opens a new background thread with a low priority and finishes immediately,"},{"type":"text","text":" "},{"type":"text","text":"the mobile application can continue its operation."},{"type":"text","text":" "},{"type":"text","text":"This function call should be preceded at least by a call specifying the key size - i.e."},{"type":"text","text":" "},{"type":"text","text":"clearPolicyParams"},{"type":"text","text":" and "},{"type":"text","text":"addPolicyParam(“keySize”, 2048)"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/prepareCryptData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareCryptData"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/preparecryptdata()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prepareCryptData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareCryptData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareCryptData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager\/title","value":"IPKIMobileManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager\/fragments","value":[{"kind":"identifier","text":"IPKIMobileManager"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1prepareCryptData()\/title","value":"prepareCryptData"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1prepareCryptData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareCryptData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}