{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomSignDataHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"customSignDataHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CustomSignDataHandler","preciseIdentifier":"c:IPKIMobileManager.h@T@CustomSignDataHandler","text":"CustomSignDataHandler"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pAuxData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ipkimobilemanager\/setcustomsigndatahandler(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/ipkimobilemanager\/setcustomsigndatahandler(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setCustomSignDataHandler(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the handler to sign function"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomSignDataHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CustomSignDataHandler","preciseIdentifier":"c:IPKIMobileManager.h@T@CustomSignDataHandler"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"setCustomSignDataHandler(_:_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)IPKIMobileManager(im)setCustomSignDataHandler::","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"setCustomSignDataHandler::"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager":{"role":"symbol","title":"IPKIMobileManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPKIMobileManager"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IPKIMobileManager"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CustomSignDataHandler":{"role":"symbol","title":"CustomSignDataHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomSignDataHandler"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CustomSignDataHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomSignDataHandler"}],"url":"\/documentation\/cshub_test\/customsigndatahandler"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/IPKIMobileManager/setCustomSignDataHandler(_:_:)":{"role":"symbol","title":"setCustomSignDataHandler(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCustomSignDataHandler"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CustomSignDataHandler","preciseIdentifier":"c:IPKIMobileManager.h@T@CustomSignDataHandler"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set the handler to sign function"}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/IPKIMobileManager\/setCustomSignDataHandler(_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCustomSignDataHandler::"}],"url":"\/documentation\/cshub_test\/ipkimobilemanager\/setcustomsigndatahandler(_:_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setCustomSignDataHandler::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomSignDataHandler::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCustomSignDataHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (void *, const unsigned char *, unsigned int, unsigned char **, unsigned int *)","preciseIdentifier":"c:Fv(#*v#*1c#i#**c#*i)"},{"kind":"text","text":"( *)"},{"kind":"internalParam","text":"customSignDataHandler"},{"kind":"text","text":") "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"pAuxData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager\/title","value":"IPKIMobileManager"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager\/fragments","value":[{"kind":"identifier","text":"IPKIMobileManager"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CustomSignDataHandler\/title","value":"CustomSignDataHandler"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CustomSignDataHandler\/fragments","value":[{"kind":"identifier","text":"CustomSignDataHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setCustomSignDataHandler(_:_:)\/title","value":"setCustomSignDataHandler::"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1IPKIMobileManager~1setCustomSignDataHandler(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCustomSignDataHandler::"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}