{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":" "},{"kind":"internalParam","text":"keyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/webapplicationviewmodel\/observevalue(forkeypath:of:change:context:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/webapplicationviewmodel\/observevalue(forkeypath:of:change:context:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/observeValue(forKeyPath:of:change:context:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?)"}],"title":"observeValue(forKeyPath:of:change:context:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)WebApplicationViewModel(im)observeValueForKeyPath:ofObject:change:context:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel/observeValue(forKeyPath:of:change:context:)":{"role":"symbol","title":"observeValue(forKeyPath:of:change:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel\/observeValue(forKeyPath:of:change:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"url":"\/documentation\/cshub_test\/webapplicationviewmodel\/observevalue(forkeypath:of:change:context:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/WebApplicationViewModel":{"role":"symbol","title":"WebApplicationViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebApplicationViewModel"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/WebApplicationViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebApplicationViewModel"}],"url":"\/documentation\/cshub_test\/webapplicationviewmodel"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"observeValueForKeyPath:ofObject:change:context:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"observeValueForKeyPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"keyPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"ofObject:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"object"},{"kind":"text","text":" "},{"kind":"identifier","text":"change:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"change"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel~1observeValue(forKeyPath:of:change:context:)\/title","value":"observeValueForKeyPath:ofObject:change:context:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel~1observeValue(forKeyPath:of:change:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/title","value":"WebApplicationViewModel"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1WebApplicationViewModel\/fragments","value":[{"kind":"identifier","text":"WebApplicationViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}