{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerformAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/datepickeruitextfield\/canperformaction(_:withsender:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/datepickeruitextfield\/canperformaction(_:withsender:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield\/canPerformAction(_:withSender:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerformAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"canPerformAction(_:withSender:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)DatePickerUITextfield(im)canPerformAction:withSender:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"canPerformAction:withSender:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DatePickerUITextfield/canPerformAction(_:withSender:)":{"role":"symbol","title":"canPerformAction(_:withSender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerformAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield\/canPerformAction(_:withSender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canPerformAction:withSender:"}],"url":"\/documentation\/cshub_test\/datepickeruitextfield\/canperformaction(_:withsender:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DatePickerUITextfield":{"role":"symbol","title":"DatePickerUITextfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DatePickerUITextfield"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DatePickerUITextfield"}],"url":"\/documentation\/cshub_test\/datepickeruitextfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canPerformAction:withSender:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerformAction:withSender:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canPerformAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SEL","preciseIdentifier":"c:e"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"action"},{"kind":"text","text":" "},{"kind":"identifier","text":"withSender:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield~1canPerformAction(_:withSender:)\/title","value":"canPerformAction:withSender:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield~1canPerformAction(_:withSender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerformAction:withSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield\/title","value":"DatePickerUITextfield"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield\/fragments","value":[{"kind":"identifier","text":"DatePickerUITextfield"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}