{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/datepickeruitextfield\/datechanged(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/datepickeruitextfield\/datechanged(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield\/dateChanged(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":")"}],"title":"dateChanged(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)DatePickerUITextfield(im)dateChanged:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"dateChanged:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DatePickerUITextfield/dateChanged(_:)":{"role":"symbol","title":"dateChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield\/dateChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateChanged:"}],"url":"\/documentation\/cshub_test\/datepickeruitextfield\/datechanged(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DatePickerUITextfield":{"role":"symbol","title":"DatePickerUITextfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DatePickerUITextfield"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DatePickerUITextfield","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DatePickerUITextfield"}],"url":"\/documentation\/cshub_test\/datepickeruitextfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dateChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dateChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dateChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield~1dateChanged(_:)\/title","value":"dateChanged:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield~1dateChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dateChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield\/title","value":"DatePickerUITextfield"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DatePickerUITextfield\/fragments","value":[{"kind":"identifier","text":"DatePickerUITextfield"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}