{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faqtaX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqtaX","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqtaX","text":"FaqtaX"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/faqcell\/faqtax"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell\/faqtaX","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faqtaX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqtaX","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqtaX"}],"title":"faqtaX","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test7FaqCellC6faqtaXAA6FaqtaXCvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqCell/faqtaX":{"role":"symbol","title":"faqtaX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"faqtaX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaqtaX","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)FaqtaX"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell\/faqtaX","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/faqcell\/faqtax"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqCell":{"role":"symbol","title":"FaqCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqCell"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqCell"}],"url":"\/documentation\/cshub_test\/faqcell"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/FaqtaX":{"role":"symbol","title":"FaqtaX","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaqtaX"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/FaqtaX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaqtaX"}],"url":"\/documentation\/cshub_test\/faqtax"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/title","value":"FaqCell"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqCell\/fragments","value":[{"kind":"identifier","text":"FaqCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqtaX\/title","value":"FaqtaX"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1FaqtaX\/fragments","value":[{"kind":"identifier","text":"FaqtaX"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}