{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"datePickerChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/borderedtextfield\/datepickerchanged(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/borderedtextfield\/datepickerchanged(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/datePickerChanged(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"datePickerChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":")"}],"title":"datePickerChanged(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)BorderedTextField(im)datePickerChanged:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"datePickerChanged:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/datePickerChanged(_:)":{"role":"symbol","title":"datePickerChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"datePickerChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/datePickerChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"datePickerChanged:"}],"url":"\/documentation\/cshub_test\/borderedtextfield\/datepickerchanged(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField":{"role":"symbol","title":"BorderedTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BorderedTextField"}],"url":"\/documentation\/cshub_test\/borderedtextfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"datePickerChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"datePickerChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"datePickerChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDatePicker","preciseIdentifier":"c:objc(cs)UIDatePicker"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1datePickerChanged(_:)\/title","value":"datePickerChanged:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1datePickerChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"datePickerChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/title","value":"BorderedTextField"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/fragments","value":[{"kind":"identifier","text":"BorderedTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}