{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfComponents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pickerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/borderedtextfield\/numberofcomponents(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/borderedtextfield\/numberofcomponents(in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/numberOfComponents(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPickerViewDataSource.numberOfComponents(in:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfComponents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfComponents(in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)BorderedTextField(im)numberOfComponentsInPickerView:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"numberOfComponentsInPickerView:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/UIPickerViewDataSource-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField":{"role":"symbol","title":"BorderedTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BorderedTextField"}],"url":"\/documentation\/cshub_test\/borderedtextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/UIPickerViewDataSource-Implementations":{"role":"collectionGroup","title":"UIPickerViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/UIPickerViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/borderedtextfield\/uipickerviewdatasource-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/numberOfComponents(in:)":{"role":"symbol","title":"numberOfComponents(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfComponents"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/numberOfComponents(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfComponentsInPickerView:"}],"url":"\/documentation\/cshub_test\/borderedtextfield\/numberofcomponents(in:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"numberOfComponentsInPickerView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfComponentsInPickerView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"numberOfComponentsInPickerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"pickerView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/title","value":"BorderedTextField"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/fragments","value":[{"kind":"identifier","text":"BorderedTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1numberOfComponents(in:)\/title","value":"numberOfComponentsInPickerView:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1numberOfComponents(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfComponentsInPickerView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}