{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pickerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForRow"},{"kind":"text","text":" "},{"kind":"internalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"component"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/borderedtextfield\/pickerview(_:titleforrow:forcomponent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/borderedtextfield\/pickerview(_:titleforrow:forcomponent:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:titleForRow:forComponent:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPickerViewDelegate.pickerView(_:titleForRow:forComponent:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"pickerView(_:titleForRow:forComponent:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)BorderedTextField(im)pickerView:titleForRow:forComponent:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/UIPickerViewDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/UIPickerViewDelegate-Implementations":{"role":"collectionGroup","title":"UIPickerViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/UIPickerViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/borderedtextfield\/uipickerviewdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/pickerView(_:titleForRow:forComponent:)":{"role":"symbol","title":"pickerView(_:titleForRow:forComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:titleForRow:forComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}],"url":"\/documentation\/cshub_test\/borderedtextfield\/pickerview(_:titleforrow:forcomponent:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField":{"role":"symbol","title":"BorderedTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BorderedTextField"}],"url":"\/documentation\/cshub_test\/borderedtextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pickerView:titleForRow:forComponent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pickerView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"pickerView"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleForRow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"row"},{"kind":"text","text":" "},{"kind":"identifier","text":"forComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"component"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1pickerView(_:titleForRow:forComponent:)\/title","value":"pickerView:titleForRow:forComponent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1pickerView(_:titleForRow:forComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/title","value":"BorderedTextField"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/fragments","value":[{"kind":"identifier","text":"BorderedTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}