{"variants":[{"paths":["\/documentation\/cshub_test\/borderedtextfield\/uipickerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/borderedtextfield\/uipickerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/UIPickerViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:didSelectRow:inComponent:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:titleForRow:forComponent:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"UIPickerViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/pickerView(_:titleForRow:forComponent:)":{"role":"symbol","title":"pickerView(_:titleForRow:forComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:titleForRow:forComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}],"url":"\/documentation\/cshub_test\/borderedtextfield\/pickerview(_:titleforrow:forcomponent:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField/pickerView(_:didSelectRow:inComponent:)":{"role":"symbol","title":"pickerView(_:didSelectRow:inComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:didSelectRow:inComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}],"url":"\/documentation\/cshub_test\/borderedtextfield\/pickerview(_:didselectrow:incomponent:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/BorderedTextField":{"role":"symbol","title":"BorderedTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BorderedTextField"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BorderedTextField"}],"url":"\/documentation\/cshub_test\/borderedtextfield"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:didSelectRow:inComponent:)","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/BorderedTextField\/pickerView(_:titleForRow:forComponent:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1pickerView(_:titleForRow:forComponent:)\/title","value":"pickerView:titleForRow:forComponent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1pickerView(_:titleForRow:forComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1pickerView(_:didSelectRow:inComponent:)\/title","value":"pickerView:didSelectRow:inComponent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField~1pickerView(_:didSelectRow:inComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:didSelectRow:inComponent:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/title","value":"BorderedTextField"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1BorderedTextField\/fragments","value":[{"kind":"identifier","text":"BorderedTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}