{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamExpandableProductView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CiamExpandableProductView","text":"CiamExpandableProductView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/ciamspzproductview\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSPZProductView\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CIAMProductView.delegate"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CiamExpandableProductView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CiamExpandableProductView"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test18CiamSPZProductViewC8delegateAA0c17ExpandableProductE0CSgvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSPZProductView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamExpandableProductView":{"role":"symbol","title":"CiamExpandableProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamExpandableProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamExpandableProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamExpandableProductView"}],"url":"\/documentation\/cshub_test\/ciamexpandableproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamSPZProductView":{"role":"symbol","title":"CiamSPZProductView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CiamSPZProductView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSPZProductView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CiamSPZProductView"}],"url":"\/documentation\/cshub_test\/ciamspzproductview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CiamSPZProductView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CiamExpandableProductView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CiamExpandableProductView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CiamSPZProductView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/ciamspzproductview\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamExpandableProductView\/title","value":"CiamExpandableProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamExpandableProductView\/fragments","value":[{"kind":"identifier","text":"CiamExpandableProductView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSPZProductView\/title","value":"CiamSPZProductView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CiamSPZProductView\/fragments","value":[{"kind":"identifier","text":"CiamSPZProductView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}