{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/delegate\/urlsession(_:task:didreceive:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/delegate\/urlsession(_:task:didreceive:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/urlSession(_:task:didReceive:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"urlSession(_:task:didReceive:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)Delegate(im)URLSession:task:didReceiveChallenge:completionHandler:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Delegate/urlSession(_:task:didReceive:completionHandler:)":{"role":"symbol","title":"urlSession(_:task:didReceive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate\/urlSession(_:task:didReceive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}],"url":"\/documentation\/cshub_test\/delegate\/urlsession(_:task:didreceive:completionhandler:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/Delegate":{"role":"symbol","title":"Delegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Delegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/Delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Delegate"}],"url":"\/documentation\/cshub_test\/delegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"URLSession:task:didReceiveChallenge:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"URLSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"task:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"task"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum NSURLSessionAuthChallengeDisposition, NSURLCredential *)","preciseIdentifier":"c:BFv(#$@E@NSURLSessionAuthChallengeDisposition#*$objc(cs)NSURLCredential)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate~1urlSession(_:task:didReceive:completionHandler:)\/title","value":"URLSession:task:didReceiveChallenge:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate~1urlSession(_:task:didReceive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate\/title","value":"Delegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1Delegate\/fragments","value":[{"kind":"identifier","text":"Delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}