{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/defaultwebviewcoordinator\/webview(_:didfail:witherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/defaultwebviewcoordinator\/webview(_:didfail:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultWebViewCoordinator\/webView(_:didFail:withError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:didFail:withError:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"webView(_:didFail:withError:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)DefaultWebViewCoordinator(im)webView:didFailNavigation:withError:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"webView:didFailNavigation:withError:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultWebViewCoordinator"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultWebViewCoordinator":{"role":"symbol","title":"DefaultWebViewCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultWebViewCoordinator"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultWebViewCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultWebViewCoordinator"}],"url":"\/documentation\/cshub_test\/defaultwebviewcoordinator"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/DefaultWebViewCoordinator/webView(_:didFail:withError:)":{"role":"symbol","title":"webView(_:didFail:withError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/DefaultWebViewCoordinator\/webView(_:didFail:withError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"url":"\/documentation\/cshub_test\/defaultwebviewcoordinator\/webview(_:didfail:witherror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:didFailNavigation:withError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailNavigation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultWebViewCoordinator\/title","value":"DefaultWebViewCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultWebViewCoordinator\/fragments","value":[{"kind":"identifier","text":"DefaultWebViewCoordinator"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultWebViewCoordinator~1webView(_:didFail:withError:)\/title","value":"webView:didFailNavigation:withError:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1DefaultWebViewCoordinator~1webView(_:didFail:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}