{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"called right after the applicationDidBecomeActive"}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appdelegate\/applicationwillenterforeground(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/appdelegate\/applicationwillenterforeground(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillEnterForeground(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called as part of the transition from the background to the active state; here you can"},{"type":"text","text":" "},{"type":"text","text":"undo many of the changes made on entering the background."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"title":"applicationWillEnterForeground(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)AppDelegate(im)applicationWillEnterForeground:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/applicationWillEnterForeground(_:)":{"role":"symbol","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called as part of the transition from the background to the active state; here you can"},{"type":"text","text":" "},{"type":"text","text":"undo many of the changes made on entering the background."}],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/applicationWillEnterForeground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"url":"\/documentation\/cshub_test\/appdelegate\/applicationwillenterforeground(_:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/cshub_test\/appdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"applicationWillEnterForeground:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"_"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillEnterForeground(_:)\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1applicationWillEnterForeground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}