{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedInterfaceOrientationsFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appdelegate\/application(_:supportedinterfaceorientationsfor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/appdelegate\/application(_:supportedinterfaceorientationsfor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:supportedInterfaceOrientationsFor:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedInterfaceOrientationsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"title":"application(_:supportedInterfaceOrientationsFor:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)AppDelegate(im)application:supportedInterfaceOrientationsForWindow:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/cshub_test\/appdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/application(_:supportedInterfaceOrientationsFor:)":{"role":"symbol","title":"application(_:supportedInterfaceOrientationsFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"supportedInterfaceOrientationsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:supportedInterfaceOrientationsFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}],"url":"\/documentation\/cshub_test\/appdelegate\/application(_:supportedinterfaceorientationsfor:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:supportedInterfaceOrientationsForWindow:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedInterfaceOrientationsForWindow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"window"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/title","value":"application:supportedInterfaceOrientationsForWindow:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:supportedInterfaceOrientationsFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:supportedInterfaceOrientationsForWindow:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}