{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appdelegate\/application(_:didreceiveremotenotification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/appdelegate\/application(_:didreceiveremotenotification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didReceiveRemoteNotification:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:didReceiveRemoteNotification:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}],"role":"symbol","title":"application(_:didReceiveRemoteNotification:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)AppDelegate(im)application:didReceiveRemoteNotification:","extendedModule":"CSHub_Test","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/application(_:didReceiveRemoteNotification:)":{"role":"symbol","title":"application(_:didReceiveRemoteNotification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didReceiveRemoteNotification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}],"url":"\/documentation\/cshub_test\/appdelegate\/application(_:didreceiveremotenotification:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/cshub_test\/appdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/UIApplicationDelegate-Implementations":{"role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/uiapplicationdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:didReceiveRemoteNotification:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:didReceiveRemoteNotification:)\/title","value":"application:didReceiveRemoteNotification:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:didReceiveRemoteNotification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}