{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/appdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:didReceiveRemoteNotification:fetchCompletionHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"role":"symbol","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)AppDelegate(im)application:didReceiveRemoteNotification:fetchCompletionHandler:","extendedModule":"CSHub_Test","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/cshub_test\/appdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/UIApplicationDelegate-Implementations":{"role":"collectionGroup","title":"UIApplicationDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/UIApplicationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/uiapplicationdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"role":"symbol","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"fetchCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}],"url":"\/documentation\/cshub_test\/appdelegate\/application(_:didreceiveremotenotification:fetchcompletionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum UIBackgroundFetchResult)","preciseIdentifier":"c:BFv(#$@E@UIBackgroundFetchResult)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/title","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:fetchCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}