{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fcmToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/appdelegate\/messaging(_:didreceiveregistrationtoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/appdelegate\/messaging(_:didreceiveregistrationtoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/messaging(_:didReceiveRegistrationToken:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessagingDelegate.messaging(_:didReceiveRegistrationToken:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}],"role":"symbol","title":"messaging(_:didReceiveRegistrationToken:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@CSHub_Test@objc(cs)AppDelegate(im)messaging:didReceiveRegistrationToken:","extendedModule":"CSHub_Test","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/MessagingDelegate-Implementations"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/MessagingDelegate-Implementations":{"role":"collectionGroup","title":"MessagingDelegate Implementations","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/MessagingDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cshub_test\/appdelegate\/messagingdelegate-implementations"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/cshub_test\/appdelegate"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/AppDelegate/messaging(_:didReceiveRegistrationToken:)":{"role":"symbol","title":"messaging(_:didReceiveRegistrationToken:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messaging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Messaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRegistrationToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/AppDelegate\/messaging(_:didReceiveRegistrationToken:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}],"url":"\/documentation\/cshub_test\/appdelegate\/messaging(_:didreceiveregistrationtoken:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messaging:didReceiveRegistrationToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messaging:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FIRMessaging","preciseIdentifier":"c:objc(cs)FIRMessaging"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messaging"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRegistrationToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"fcmToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1messaging(_:didReceiveRegistrationToken:)\/title","value":"messaging:didReceiveRegistrationToken:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1AppDelegate~1messaging(_:didReceiveRegistrationToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messaging:didReceiveRegistrationToken:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}