{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"header"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView","text":"ZenIDCardHeaderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView","text":"ZenIDCardFooterView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidpopupview\/init(header:content:footer:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPopupView\/init(header:content:footer:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"header"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"},{"kind":"text","text":")"}],"title":"init(header:content:footer:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:10CSHub_Test14ZenIDPopupViewC6header7content6footerAcA0c12IDCardHeaderE0C_So6UIViewCAA0ci6FooterE0Ctcfc","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPopupView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPopupView/init(header:content:footer:)":{"role":"symbol","title":"init(header:content:footer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"header"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardHeaderView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardHeaderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDCardFooterView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDCardFooterView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPopupView\/init(header:content:footer:)","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidpopupview\/init(header:content:footer:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDPopupView":{"role":"symbol","title":"ZenIDPopupView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDPopupView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDPopupView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDPopupView"}],"url":"\/documentation\/cshub_test\/zenidpopupview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCardHeaderView":{"role":"symbol","title":"ZenIDCardHeaderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCardHeaderView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardHeaderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCardHeaderView"}],"url":"\/documentation\/cshub_test\/zenidcardheaderview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDCardFooterView":{"role":"symbol","title":"ZenIDCardFooterView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDCardFooterView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDCardFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDCardFooterView"}],"url":"\/documentation\/cshub_test\/zenidcardfooterview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPopupView\/title","value":"ZenIDPopupView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDPopupView\/fragments","value":[{"kind":"identifier","text":"ZenIDPopupView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardHeaderView\/title","value":"ZenIDCardHeaderView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardHeaderView\/fragments","value":[{"kind":"identifier","text":"ZenIDCardHeaderView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardFooterView\/title","value":"ZenIDCardFooterView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDCardFooterView\/fragments","value":[{"kind":"identifier","text":"ZenIDCardFooterView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}