{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePageChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/handlepagechange(notification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/handlepagechange(notification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/handlePageChange(notification:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePageChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"title":"handlePageChange(notification:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CSHub_Test@objc(cs)PdfDocumentComponentsDrawer(im)handlePageChangeWithNotification:","modules":[{"name":"CSHub_Test"}],"navigatorTitle":[{"kind":"identifier","text":"handlePageChangeWithNotification:"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer":{"role":"symbol","title":"PdfDocumentComponentsDrawer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/PdfDocumentComponentsDrawer/handlePageChange(notification:)":{"role":"symbol","title":"handlePageChange(notification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePageChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/PdfDocumentComponentsDrawer\/handlePageChange(notification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handlePageChangeWithNotification:"}],"url":"\/documentation\/cshub_test\/pdfdocumentcomponentsdrawer\/handlepagechange(notification:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handlePageChangeWithNotification:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePageChangeWithNotification:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"handlePageChangeWithNotification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer\/title","value":"PdfDocumentComponentsDrawer"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer\/fragments","value":[{"kind":"identifier","text":"PdfDocumentComponentsDrawer"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1handlePageChange(notification:)\/title","value":"handlePageChangeWithNotification:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1PdfDocumentComponentsDrawer~1handlePageChange(notification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePageChangeWithNotification:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}