{"variants":[{"paths":["\/documentation\/cshub_test\/recapitulationviewstep2\/uipickerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/recapitulationviewstep2\/uipickerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/UIPickerViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/pickerView(_:titleForRow:forComponent:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"UIPickerViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RecapitulationViewStep2":{"role":"symbol","title":"RecapitulationViewStep2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecapitulationViewStep2"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecapitulationViewStep2"}],"url":"\/documentation\/cshub_test\/recapitulationviewstep2"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RecapitulationViewStep2/pickerView(_:titleForRow:forComponent:)":{"role":"symbol","title":"pickerView(_:titleForRow:forComponent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pickerView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPickerView","preciseIdentifier":"c:objc(cs)UIPickerView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/pickerView(_:titleForRow:forComponent:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}],"url":"\/documentation\/cshub_test\/recapitulationviewstep2\/pickerview(_:titleforrow:forcomponent:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/pickerView(_:titleForRow:forComponent:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2\/title","value":"RecapitulationViewStep2"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2\/fragments","value":[{"kind":"identifier","text":"RecapitulationViewStep2"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2~1pickerView(_:titleForRow:forComponent:)\/title","value":"pickerView:titleForRow:forComponent:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2~1pickerView(_:titleForRow:forComponent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pickerView:titleForRow:forComponent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}