{"variants":[{"paths":["\/documentation\/cshub_test\/recapitulationviewstep2\/uitextfielddelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cshub_test\/recapitulationviewstep2\/uitextfielddelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/UITextFieldDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/textField(_:shouldChangeCharactersIn:replacementString:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"CSHub_Test"}],"role":"collectionGroup","title":"UITextFieldDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RecapitulationViewStep2/textField(_:shouldChangeCharactersIn:replacementString:)":{"role":"symbol","title":"textField(_:shouldChangeCharactersIn:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/textField(_:shouldChangeCharactersIn:replacementString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"url":"\/documentation\/cshub_test\/recapitulationviewstep2\/textfield(_:shouldchangecharactersin:replacementstring:)"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/RecapitulationViewStep2":{"role":"symbol","title":"RecapitulationViewStep2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecapitulationViewStep2"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecapitulationViewStep2"}],"url":"\/documentation\/cshub_test\/recapitulationviewstep2"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/RecapitulationViewStep2\/textField(_:shouldChangeCharactersIn:replacementString:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2\/title","value":"RecapitulationViewStep2"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1RecapitulationViewStep2\/fragments","value":[{"kind":"identifier","text":"RecapitulationViewStep2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}