{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDBottomRightView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDBottomRightView","text":"ZenIDBottomRightView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidrightview\/bottomview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/bottomView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDBottomRightView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDBottomRightView"}],"title":"bottomView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test14ZenIDRightViewC06bottomE0AA0c13IDBottomRightE0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView":{"role":"symbol","title":"ZenIDRightView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDRightView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDRightView"}],"url":"\/documentation\/cshub_test\/zenidrightview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/bottomView":{"role":"symbol","title":"bottomView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZenIDBottomRightView","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)ZenIDBottomRightView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/bottomView","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/bottomview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDBottomRightView":{"role":"symbol","title":"ZenIDBottomRightView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDBottomRightView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDBottomRightView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDBottomRightView"}],"url":"\/documentation\/cshub_test\/zenidbottomrightview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDRightView\/title","value":"ZenIDRightView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDRightView\/fragments","value":[{"kind":"identifier","text":"ZenIDRightView"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDBottomRightView\/title","value":"ZenIDBottomRightView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDBottomRightView\/fragments","value":[{"kind":"identifier","text":"ZenIDBottomRightView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}