{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraButton","text":"CameraButton"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cshub_test\/zenidrightview\/camerabutton"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/cameraButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraButton"}],"title":"cameraButton","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10CSHub_Test14ZenIDRightViewC12cameraButtonAA06CameraG0Cvp","modules":[{"name":"CSHub_Test"}]},"hierarchy":{"paths":[["doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView"]]},"references":{"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/CameraButton":{"role":"symbol","title":"CameraButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraButton"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/CameraButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraButton"}],"url":"\/documentation\/cshub_test\/camerabutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView/cameraButton":{"role":"symbol","title":"cameraButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraButton","preciseIdentifier":"c:@M@CSHub_Test@objc(cs)CameraButton"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView\/cameraButton","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test\/zenidrightview\/camerabutton"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test/ZenIDRightView":{"role":"symbol","title":"ZenIDRightView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZenIDRightView"}],"abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test\/ZenIDRightView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZenIDRightView"}],"url":"\/documentation\/cshub_test\/zenidrightview"},"doc://cz.csas.app.cshub.test/documentation/CSHub_Test":{"role":"collection","title":"CSHub_Test","abstract":[],"identifier":"doc:\/\/cz.csas.app.cshub.test\/documentation\/CSHub_Test","kind":"symbol","type":"topic","url":"\/documentation\/cshub_test"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraButton\/title","value":"CameraButton"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1CameraButton\/fragments","value":[{"kind":"identifier","text":"CameraButton"}]},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDRightView\/title","value":"ZenIDRightView"},{"op":"replace","path":"\/references\/doc:~1~1cz.csas.app.cshub.test~1documentation~1CSHub_Test~1ZenIDRightView\/fragments","value":[{"kind":"identifier","text":"ZenIDRightView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}